In [2]:
import pingouin as pg
import itertools
import pandas as pd
import numpy as np
from sklearn.metrics import roc_curve, auc
from tqdm import tqdm
import csv
import gzip
import glob

In [3]:
def print_full(x):
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', 2000)
    pd.set_option('display.float_format', '{:20,.2f}'.format)
    pd.set_option('display.max_colwidth', None)
    print(x)
    pd.reset_option('display.max_rows')
    pd.reset_option('display.max_columns')
    pd.reset_option('display.width')
    pd.reset_option('display.float_format')
    pd.reset_option('display.max_colwidth')

def display_full(x):
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', 2000)
    pd.set_option('display.float_format', '{:20,.2f}'.format)
    pd.set_option('display.max_colwidth', None)
    display(x)
    pd.reset_option('display.max_rows')
    pd.reset_option('display.max_columns')
    pd.reset_option('display.width')
    pd.reset_option('display.float_format')
    pd.reset_option('display.max_colwidth')

In [4]:
def to_auc_dict(data, print_best_fpr = False):
 auc_dict = {}
 for detector in selected:
  temp = data.copy()#[data.split == 'test'].reset_index(drop=True)
  labels = [1 if (x == "machine") or (str(x) == "1") else 0 for x in temp.label]
  temp = temp.dropna()
  temp['prediction_probs'] = temp[detector].fillna(0.0).replace(-np.inf, np.finfo('float16').min).replace(np.inf, np.finfo('float16').max)
  fpr, tpr, thresholds = roc_curve(labels, temp['prediction_probs'])
  if len(pd.Series(labels).value_counts()) < 2:
     auc_dict[detector] = {'auc': -1, 'th_optim': -1, 'tpr_1%fpr': -1, 'tpr_5%fpr': -1, 'tpr_10%fpr': -1, 'tpr_20%fpr': -1, 'th_1%fpr': -1, 'th_3%fpr': -1, 'th_5%fpr': -1, 'th_10%fpr': -1, 'th_15%fpr': -1, 'th_20%fpr': -1, 'th_25%fpr': -1, 'th_30%fpr': -1, 'th_40%fpr': -1, 'th_50%fpr': -1}
  else:
     auc_dict[detector] = {'auc': auc(fpr, tpr), 'th_optim': thresholds[np.argmax(tpr - fpr)], 'tpr_1%fpr': tpr[fpr <= 0.01][-1], 'tpr_5%fpr': tpr[fpr <= 0.05][-1], 'th_1%fpr': thresholds[fpr <= 0.01][-1], 'th_3%fpr': thresholds[fpr <= 0.03][-1], 'th_5%fpr': thresholds[fpr <= 0.05][-1], 'th_10%fpr': thresholds[fpr <= 0.10][-1], 'th_15%fpr': thresholds[fpr <= 0.15][-1], 'th_20%fpr': thresholds[fpr <= 0.20][-1], 'th_25%fpr': thresholds[fpr <= 0.25][-1], 'th_30%fpr': thresholds[fpr <= 0.30][-1], 'th_40%fpr': thresholds[fpr <= 0.40][-1], 'th_50%fpr': thresholds[fpr <= 0.50][-1]}
  fpr_fully = len(temp[(temp['prediction_probs'] == 1.0) & (labels == 0)]) / len(temp[(temp['label'] == 0)])
  if print_best_fpr and (fpr_fully > 0.05):
    print('Best FPR:', detector, fpr_fully)
  if 'language' in temp.columns:
   for test_language in temp.language.unique():
    temp2 = temp[temp.language == test_language].reset_index(drop=True)
    labels = [1 if (x == "machine") or (str(x) == "1") else 0 for x in temp2.label]
    fpr, tpr, thresholds = roc_curve(labels, temp2['prediction_probs'])
    if len(pd.Series(labels).value_counts()) < 2:
        auc_dict[detector][test_language] = {'auc': -1, 'th_optim': -1, 'tpr_1%fpr': -1, 'tpr_5%fpr': -1, 'tpr_10%fpr': -1, 'tpr_20%fpr': -1, 'th_1%fpr': -1, 'th_3%fpr': -1, 'th_5%fpr': -1, 'th_10%fpr': -1, 'th_15%fpr': -1, 'th_20%fpr': -1, 'th_25%fpr': -1, 'th_30%fpr': -1, 'th_40%fpr': -1, 'th_50%fpr': -1}
    else:
        auc_dict[detector][test_language] = {'auc': auc(fpr, tpr), 'th_optim': thresholds[np.argmax(tpr - fpr)], 'tpr_1%fpr': tpr[fpr <= 0.01][-1] if len(tpr[fpr <= 0.01]) > 0 else -1, 'tpr_5%fpr': tpr[fpr <= 0.05][-1], 'tpr_10%fpr': tpr[fpr <= 0.1][-1], 'tpr_20%fpr': tpr[fpr <= 0.2][-1], 'th_1%fpr': thresholds[fpr <= 0.01][-1] if len(thresholds[fpr <= 0.01]) > 0 else -1, 'th_3%fpr': thresholds[fpr <= 0.03][-1], 'th_5%fpr': thresholds[fpr <= 0.05][-1], 'th_10%fpr': thresholds[fpr <= 0.10][-1], 'th_15%fpr': thresholds[fpr <= 0.15][-1], 'th_20%fpr': thresholds[fpr <= 0.20][-1], 'th_25%fpr': thresholds[fpr <= 0.25][-1], 'th_30%fpr': thresholds[fpr <= 0.30][-1], 'th_40%fpr': thresholds[fpr <= 0.40][-1], 'th_50%fpr': thresholds[fpr <= 0.50][-1]}
    temp2['label'] = labels
    fpr_fully = len(temp2[(temp2['prediction_probs'] == 1.0) & (temp2['label'] == 0)]) / len(temp2[(temp2['label'] == 0)])
    if print_best_fpr and (fpr_fully > 0.05):
      print('Best FPR:', detector, test_language, fpr_fully)
 domains = data.domain.unique()
 auc_dict['domains'] = domains
 return auc_dict  

def to_auc_dict_generator(data, print_best_fpr = False):
 auc_dict = {}
 for detector in selected:
  temp = data.copy()#[data.split == 'test'].reset_index(drop=True)
  labels = [1 if (x == "machine") or (str(x) == "1") else 0 for x in temp.label]
  temp = temp.dropna()
  temp['prediction_probs'] = temp[detector].fillna(0.0).replace(-np.inf, np.finfo('float16').min).replace(np.inf, np.finfo('float16').max)
  fpr, tpr, thresholds = roc_curve(labels, temp['prediction_probs'])
  if len(pd.Series(labels).value_counts()) < 2:
     auc_dict[detector] = {'auc': -1, 'th_optim': -1, 'tpr_1%fpr': -1, 'tpr_5%fpr': -1, 'tpr_10%fpr': -1, 'tpr_20%fpr': -1, 'th_1%fpr': -1, 'th_3%fpr': -1, 'th_5%fpr': -1, 'th_10%fpr': -1, 'th_15%fpr': -1, 'th_20%fpr': -1, 'th_25%fpr': -1, 'th_30%fpr': -1, 'th_40%fpr': -1, 'th_50%fpr': -1}
  else:
     auc_dict[detector] = {'auc': auc(fpr, tpr), 'th_optim': thresholds[np.argmax(tpr - fpr)], 'tpr_1%fpr': tpr[fpr <= 0.01][-1], 'tpr_5%fpr': tpr[fpr <= 0.05][-1], 'th_1%fpr': thresholds[fpr <= 0.01][-1], 'th_3%fpr': thresholds[fpr <= 0.03][-1], 'th_5%fpr': thresholds[fpr <= 0.05][-1], 'th_10%fpr': thresholds[fpr <= 0.10][-1], 'th_15%fpr': thresholds[fpr <= 0.15][-1], 'th_20%fpr': thresholds[fpr <= 0.20][-1], 'th_25%fpr': thresholds[fpr <= 0.25][-1], 'th_30%fpr': thresholds[fpr <= 0.30][-1], 'th_40%fpr': thresholds[fpr <= 0.40][-1], 'th_50%fpr': thresholds[fpr <= 0.50][-1]}
  fpr_fully = len(temp[(temp['prediction_probs'] == 1.0) & (labels == 0)]) / len(temp[(temp['label'] == 0)])
  if print_best_fpr and (fpr_fully > 0.05):
    print('Best FPR:', detector, fpr_fully)
  if 'multi_label' in temp.columns:
   for generator in [x for x in temp.multi_label.unique() if x != "human"]:
    temp2 = temp[temp.multi_label.isin(["human", generator])].reset_index(drop=True)
    labels = [1 if (x == "machine") or (str(x) == "1") else 0 for x in temp2.label]
    fpr, tpr, thresholds = roc_curve(labels, temp2['prediction_probs'])
    if len(pd.Series(labels).value_counts()) < 2:
        auc_dict[detector][generator] = {'auc': -1, 'th_optim': -1, 'tpr_1%fpr': -1, 'tpr_5%fpr': -1, 'tpr_10%fpr': -1, 'tpr_20%fpr': -1, 'th_1%fpr': -1, 'th_3%fpr': -1, 'th_5%fpr': -1, 'th_10%fpr': -1, 'th_15%fpr': -1, 'th_20%fpr': -1, 'th_25%fpr': -1, 'th_30%fpr': -1, 'th_40%fpr': -1, 'th_50%fpr': -1}
    else:
        auc_dict[detector][generator] = {'auc': auc(fpr, tpr), 'th_optim': thresholds[np.argmax(tpr - fpr)], 'tpr_1%fpr': tpr[fpr <= 0.01][-1] if len(tpr[fpr <= 0.01]) > 0 else -1, 'tpr_5%fpr': tpr[fpr <= 0.05][-1], 'tpr_10%fpr': tpr[fpr <= 0.1][-1], 'tpr_20%fpr': tpr[fpr <= 0.2][-1], 'th_1%fpr': thresholds[fpr <= 0.01][-1] if len(thresholds[fpr <= 0.01]) > 0 else -1, 'th_3%fpr': thresholds[fpr <= 0.03][-1], 'th_5%fpr': thresholds[fpr <= 0.05][-1], 'th_10%fpr': thresholds[fpr <= 0.10][-1], 'th_15%fpr': thresholds[fpr <= 0.15][-1], 'th_20%fpr': thresholds[fpr <= 0.20][-1], 'th_25%fpr': thresholds[fpr <= 0.25][-1], 'th_30%fpr': thresholds[fpr <= 0.30][-1], 'th_40%fpr': thresholds[fpr <= 0.40][-1], 'th_50%fpr': thresholds[fpr <= 0.50][-1]}
    temp2['label'] = labels
    fpr_fully = len(temp2[(temp2['prediction_probs'] == 1.0) & (temp2['label'] == 0)]) / len(temp2[(temp2['label'] == 0)])
    if print_best_fpr and (fpr_fully > 0.05):
      print('Best FPR:', detector, generator, fpr_fully)
 domains = data.domain.unique()
 auc_dict['domains'] = domains
 return auc_dict

#https://github.com/scikit-learn/scikit-learn/issues/26808
def report_np(y_true, y_pred, n_classes):

    classes = np.arange(n_classes)[None, :]
    supp = classes == y_true[:, None]
    tmp = classes == y_pred[:, None]
    hits = (tmp & supp).sum(axis=0)
    pred = tmp.sum(axis=0)
    n = y_true.shape[0]

    supp = supp.sum(axis=0)
    #https://stackoverflow.com/questions/26248654/how-to-return-0-with-divide-by-zero
    #prec = hits / pred
    pred_inv = np.array([1/i if i!=0 else 0 for i in pred])
    prec = hits * pred_inv
    #prec = np.divide(hits, pred, out=np.zeros(hits.shape, dtype=float), where=pred!=0)
    #rec = hits / supp
    supp_inv = np.array([1/i if i!=0 else 0 for i in supp])
    rec = hits * supp_inv
    #rec = np.divide(hits, supp, out=np.zeros(hits.shape, dtype=float), where=supp!=0)
    balanced_acc = rec.mean()
    prec_rec = prec + rec
    prec_rec_mult = 2 * prec * rec
    #f1 = prec_rec_mult / prec_rec
    prec_rec_inv = np.array([1/i if i!=0 else 0 for i in prec_rec])
    f1 = prec_rec_mult * prec_rec_inv
    #f1 = np.divide(prec_rec_mult, prec_rec, out=np.zeros(prec_rec_mult.shape, dtype=float), where=prec_rec!=0)
    acc = hits.sum() / n
    stacked = np.vstack([prec, rec, f1])
    macro = stacked.mean(axis=1)
    weighted = stacked @ supp / n

    return hits, pred - hits, acc, balanced_acc, supp, prec, rec, f1 , macro, weighted

def report_todict(hits, miss, acc, balanced_acc, supp, prec, rec, f1 , macro, weighted):
  report = {}
  TN = hits[0]
  FN = miss[0]
  TP = hits[1]
  FP = miss[1]
  report['fpr'] = FP/(FP+TN) if (FP+TN) > 0 else 0
  report['fnr'] = FN/(TP+FN) if (TP+FN) > 0 else 0
  human = {}
  human['precision'] = prec[0]
  human['recall'] = rec[0]
  human['f1-score'] = f1[0]
  human['support'] = supp[0]
  report['human'] = human
  machine = {}
  machine['precision'] = prec[1]
  machine['recall'] = rec[1]
  machine['f1-score'] = f1[1]
  machine['support'] = supp[1]
  report['machine'] = machine
  report['accuracy'] = acc
  report['balanced accuracy'] = balanced_acc
  macro_avg = {}
  macro_avg['precision'] = macro[0]
  macro_avg['recall'] = macro[1]
  macro_avg['f1-score'] = macro[2]
  report['macro avg'] = macro_avg
  weighted_avg = {}
  weighted_avg['precision'] = weighted[0]
  weighted_avg['recall'] = weighted[1]
  weighted_avg['f1-score'] = weighted[2]
  report['weighted avg'] = weighted_avg
  return report 

def highlight_categories(s):
    v = s['Category']
    color = 'background-color: #b6d7a8;' if v == 'F' else 'background-color: #f9cb9c;' if v == 'S' else 'background-color: #9fc5e8;'
    return [color for v in s]

def rename_detector(detector_name):
  detector_name = (detector_name
    .lower()
    .replace('nealcly-', '')
    .replace('hello-simpleai-', '')
    .replace('andreas122001-', '')
    .replace('llmdeviation', 'LLM-Deviation')
    .replace('xlm', 'XLM')
    .replace('roberta', 'RoBERTa')
    .replace('mdeberta', 'mDeBERTa')
    .replace('bert', 'BERT')
    .replace('bloomz', 'BLOOMZ')
    .replace('llama', 'Llama')
    .replace('detection-longformer', 'Detection-Longformer')
    .replace('fastdetectgpt', 'Fast-DetectGPT')
    .replace('chinese', 'Chinese')
    .replace('chatgpt', 'ChatGPT')
    .replace('binoculars', 'Binoculars')
    .replace('gemma', 'Gemma')
    .replace('2b', '2B')
    .replace('3b', '3B')
    )
  if '_' in detector_name:
    detector_name = detector_name.split('_')[0] + f" ({detector_name.split('_')[1]})"
  return detector_name

In [4]:
finetuned = pd.read_csv('results_finetuned.csv.gz')
finetuned = finetuned[finetuned.split == 'test'].reset_index(drop=True)

In [5]:
files = glob.glob("multidomain_test_ce.csv*.csv.gz")

In [6]:
#load existing detectors
results_df = pd.DataFrame()
for file in tqdm(files):
  with gzip.open(file, 'rt') as gzf: #determine the index of last column
    reader = csv.reader(gzf, dialect=csv.excel)
    last_column_index = len(next(reader)) - 1
  if "Monoculars" in file:
    df = pd.read_csv(file)
    results_df[f"binoculars"] = pd.Series([x.replace('[','').replace(']','') for x in df['binoculars']]).astype(np.float16)
    results_df[f"fastdetectgpt"] = pd.Series([x.replace('[','').replace(']','') for x in df['fastgptdetect']]).astype(np.float16)
    results_df[f"llmdeviation"] = 1-pd.Series([x.replace('[','').replace(']','') for x in df['llmd1']]).astype(np.float16)
  else:
    df = pd.read_csv(file, usecols=[last_column_index], dtype=np.float16) #load only the last column
    model_name = file.split('/')[-1].split('.csv_')[1].replace('_threshold', '').replace('.csv.gz', '').split('_')[-1]
    results_df[f"{model_name.replace('_','-')}"] = df[df.columns[-1]].astype(np.float16)
    if "unsup-simcse-roberta-base" == model_name: results_df[model_name] = 1-results_df[model_name]

100%|██████████| 4/4 [00:00<00:00,  6.00it/s]

In [7]:
df = pd.read_csv('multidomain_test_ce.csv.gz')
print(df.split.value_counts())
df.drop(columns=['generated', 'text', 'topic', 'split'], inplace=True)
df = pd.concat([df, results_df], axis=1)
df = pd.concat([df, finetuned.iloc[:,6:]], axis=1)
selected = results_df.columns.to_list() + finetuned.columns[6:].to_list()

split
test    55930
Name: count, dtype: int64

In [8]:
full_test = df.copy()
golden_test = df.groupby(['domain','label','language']).apply(lambda x: x.sample(100, random_state = 0)).reset_index(drop=True)
big_test = df.groupby(['domain','label','language']).apply(lambda x: x.sample(250, random_state = 0)).reset_index(drop=True)
big_test_generators = df.groupby(['domain','multi_label','language']).apply(lambda x: x.sample(200, random_state = 0)).reset_index(drop=True)

C:\Users\User\AppData\Local\Temp\ipykernel_16088\4238334442.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  golden_test = df.groupby(['domain','label','language']).apply(lambda x: x.sample(100, random_state = 0)).reset_index(drop=True)
C:\Users\User\AppData\Local\Temp\ipykernel_16088\4238334442.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  big_test = df.groupby(['domain','label','language']).apply(lambda x: x.sample(250, random_state = 0)).reset_index(drop=True)
C:\Users\User\AppData\Local\Temp\ipykernel_16088\4238334442.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  big_test_generators = df.groupby(['domain','multi_label','language']).apply(lambda x: x.sample(200, random_state = 0)).reset_index(drop=True)

In [13]:
pd.DataFrame(full_test.groupby(['domain', 'multi_label', 'language']).size()).unstack()

                                         0
language                                cs    de   hr   hu   pl   sk   sl
domain       multi_label
news         Llama-2-70b-chat-hf       278   283  281  280  283  263  279
             Mistral-7B-Instruct-v0.2  297   297  299  298  299  298  297
             aya-101                   294   298  298  300  298  298  299
             gpt-3.5-turbo-0125        296   298  298  300  298  300  298
             human                     296   296  298  300  300  299  299
             opt-iml-max-30b           298   287  293  297  294  286  295
             v5-Eagle-7B-HF            293   276  290  290  286  288  295
             vicuna-13b                276   287  291  285  278  285  292
social_media Mistral-7B-Instruct-v0.2  803  1224  779  813  920  259  393
             aya-101                   745  1190  708  733  834  252  377
             gemini                    801  1226  785  813  920  260  394
             gpt-3.5-turbo-0125        713  1181  738  693  858  254  386
             human                     710  1158  744  688  808  257  370
             opt-iml-max-30b           706  1091  693  608  799  228  358
             v5-Eagle-7B-HF            792  1198  769  812  922  256  391
             vicuna-13b                803  1229  777  797  910  260  389

In [14]:
pd.DataFrame(golden_test.groupby(['domain', 'multi_label', 'language']).size()).unstack()

                                         0
language                                cs   de   hr   hu   pl   sk   sl
domain       multi_label
news         Llama-2-70b-chat-hf         7    9   10   15   14   17   17
             Mistral-7B-Instruct-v0.2   17   14    6   17   13   16   16
             aya-101                    15   19   20   14   12   12   12
             gpt-3.5-turbo-0125         18   18   19   18   17   12   18
             human                     100  100  100  100  100  100  100
             opt-iml-max-30b            13   12   16   11   16   14    8
             v5-Eagle-7B-HF             18   17   17   16   14   16   15
             vicuna-13b                 12   11   12    9   14   13   14
social_media Mistral-7B-Instruct-v0.2   20   12   13   10   13   19   10
             aya-101                    13   19   15   16   23   12    9
             gemini                     12   11   12   17   16   13   15
             gpt-3.5-turbo-0125         16   23   15   13   11   20   16
             human                     100  100  100  100  100  100  100
             opt-iml-max-30b            14   10   18    9   12   10   18
             v5-Eagle-7B-HF             13   14   16   23    8   11   16
             vicuna-13b                 12   11   11   12   17   15   16

In [15]:
pd.DataFrame(big_test.groupby(['domain', 'multi_label', 'language']).size()).unstack()

                                         0
language                                cs   de   hr   hu   pl   sk   sl
domain       multi_label
news         Llama-2-70b-chat-hf        27   22   31   38   36   33   33
             Mistral-7B-Instruct-v0.2   30   38   31   47   29   32   38
             aya-101                    41   34   44   31   35   38   32
             gpt-3.5-turbo-0125         40   42   42   33   42   43   40
             human                     250  250  250  250  250  250  250
             opt-iml-max-30b            31   36   35   34   35   33   27
             v5-Eagle-7B-HF             47   40   40   35   34   36   37
             vicuna-13b                 34   38   27   32   39   35   43
social_media Mistral-7B-Instruct-v0.2   41   30   31   31   30   41   32
             aya-101                    36   36   39   38   36   34   31
             gemini                     39   37   29   46   42   36   38
             gpt-3.5-turbo-0125         34   49   31   28   32   40   47
             human                     250  250  250  250  250  250  250
             opt-iml-max-30b            30   29   34   28   22   31   34
             v5-Eagle-7B-HF             42   37   45   50   41   24   34
             vicuna-13b                 28   32   41   29   47   44   34

In [16]:
pd.DataFrame(big_test_generators.groupby(['domain', 'multi_label', 'language']).size()).unstack()

                                         0
language                                cs   de   hr   hu   pl   sk   sl
domain       multi_label
news         Llama-2-70b-chat-hf       200  200  200  200  200  200  200
             Mistral-7B-Instruct-v0.2  200  200  200  200  200  200  200
             aya-101                   200  200  200  200  200  200  200
             gpt-3.5-turbo-0125        200  200  200  200  200  200  200
             human                     200  200  200  200  200  200  200
             opt-iml-max-30b           200  200  200  200  200  200  200
             v5-Eagle-7B-HF            200  200  200  200  200  200  200
             vicuna-13b                200  200  200  200  200  200  200
social_media Mistral-7B-Instruct-v0.2  200  200  200  200  200  200  200
             aya-101                   200  200  200  200  200  200  200
             gemini                    200  200  200  200  200  200  200
             gpt-3.5-turbo-0125        200  200  200  200  200  200  200
             human                     200  200  200  200  200  200  200
             opt-iml-max-30b           200  200  200  200  200  200  200
             v5-Eagle-7B-HF            200  200  200  200  200  200  200
             vicuna-13b                200  200  200  200  200  200  200

In [13]:
#df = golden_test.copy()
#df = full_test.copy()
df = big_test.copy()
#df = big_test_generators.copy()

In [14]:
print(sorted(df.language.unique()))
df.language.value_counts()

['cs', 'de', 'hr', 'hu', 'pl', 'sk', 'sl']

language
cs    1000
de    1000
hr    1000
hu    1000
pl    1000
sk    1000
sl    1000
Name: count, dtype: int64

In [15]:
df.multi_label.value_counts()

multi_label
human                       3500
gpt-3.5-turbo-0125           543
v5-Eagle-7B-HF               542
aya-101                      505
vicuna-13b                   503
Mistral-7B-Instruct-v0.2     481
opt-iml-max-30b              439
gemini                       267
Llama-2-70b-chat-hf          220
Name: count, dtype: int64

In [16]:
results_all = pd.DataFrame()
for dataset in [to_auc_dict(df, True)]:
 for detector in tqdm(selected):
  temp = pd.DataFrame({'Dataset': "ALL_DATA", 'Detector': detector, 'Language': '{all}', 'AUC ROC': dataset[detector]['auc'], 'TPR @ 5% FPR': dataset[detector]['tpr_5%fpr'], 'Th @ 5% FPR': dataset[detector]['th_5%fpr'], 'Th @ max(TPR-FPR)': dataset[detector]['th_optim']}, index=[0])
  results_all = pd.concat([results_all, temp])
  for test_language,val in dataset[detector].items():
    if (test_language == 'auc') or ('_' in test_language): continue
    temp = pd.DataFrame({'Dataset': test_language, 'Detector': detector, 'Language': test_language, 'AUC ROC': dataset[detector][test_language]['auc'], 'TPR @ 5% FPR': val['tpr_5%fpr']}, index=[0])
    results_all = pd.concat([results_all, temp])
results_all = results_all[results_all['Detector'].isin(selected)]
#only best of each finetuned model version
temp = results_all.pivot_table(['AUC ROC', 'TPR @ 5% FPR'], 'Detector', "Dataset").reorder_levels(axis='columns', order=[1,0]).sort_index(axis='columns')#.sort_index(axis='index', ascending=False)
temp = temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False)
temp['temp'] = [x.split('_')[0] for x in temp.index]
temp = temp.drop_duplicates(subset=('temp','')).drop(columns='temp')
display(temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False).style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0))
print(temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False).style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).to_latex(convert_css=True))
#only worst of each finetuned model version
temp = results_all.pivot_table(['AUC ROC', 'TPR @ 5% FPR'], 'Detector', "Dataset").reorder_levels(axis='columns', order=[1,0]).sort_index(axis='columns')#.sort_index(axis='index', ascending=False)
temp = temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False)
temp['temp'] = [x.split('_')[0] for x in temp.index]
temp = temp.drop_duplicates(subset=('temp',''), keep='last').drop(columns='temp')
display(temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False).style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0))
print(temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False).style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).to_latex(convert_css=True))

Best FPR: andreas122001-bloomz-3b-mixed-detector sl 0.062
Best FPR: xlm-roberta-base_hr-cs de 0.092
Best FPR: xlm-roberta-base_hr-cs pl 0.06
Best FPR: xlm-roberta-base_hr-cs sk 0.094
Best FPR: xlm-roberta-base_hr-cs sl 0.204
Best FPR: xlm-roberta-base_de-hu-cs pl 0.052
Best FPR: xlm-roberta-base_de-hu-cs sk 0.06
Best FPR: xlm-roberta-base_de-hu-cs sl 0.08
Best FPR: xlm-roberta-base_de-hr-hu-cs sl 0.074
Best FPR: xlm-roberta-base_de-hr sl 0.154
Best FPR: xlm-roberta-base_de-hr-hu sk 0.052
Best FPR: xlm-roberta-base_de-hr-hu sl 0.128
Best FPR: xlm-roberta-base_pl de 0.064
Best FPR: xlm-roberta-base_de-pl-hr-hu sl 0.066
Best FPR: xlm-roberta-base_hr de 0.074
Best FPR: xlm-roberta-base_hr pl 0.06
Best FPR: xlm-roberta-base_hr sk 0.098
Best FPR: xlm-roberta-base_hr sl 0.38
Best FPR: xlm-roberta-base_hr-hu de 0.072
Best FPR: xlm-roberta-base_hr-hu pl 0.072
Best FPR: xlm-roberta-base_hr-hu sk 0.1
Best FPR: xlm-roberta-base_hr-hu sl 0.212
Best FPR: xlm-roberta-base_pl-cs de 0.052
Best FPR: xlm-roberta-base_pl-cs sl 0.052
Best FPR: xlm-roberta-base_pl-hr-hu-cs sl 0.062
Best FPR: xlm-roberta-base_pl-hr sl 0.058
Best FPR: mdeberta-v3-base_hr-cs pl 0.052
Best FPR: xlm-roberta-base_cs de 0.064
Best FPR: xlm-roberta-base_cs pl 0.054
Best FPR: xlm-roberta-base_cs sk 0.072
Best FPR: Llama-3.2-3B_hr-cs sl 0.182
Best FPR: Llama-3.2-3B_hr sl 0.268
Best FPR: Llama-3.2-3B_de-hr sl 0.186
Best FPR: Llama-3.2-3B_pl-hr sl 0.186
Best FPR: Llama-3.2-3B_de-pl-hr sl 0.102
Best FPR: Llama-3.2-3B_pl-hr-cs sl 0.092
Best FPR: Llama-3.2-3B_hr-hu-cs sl 0.16
Best FPR: Llama-3.2-3B_de-hr-hu-cs sl 0.128
Best FPR: Llama-3.2-3B_pl-hr-hu-cs sk 0.052
Best FPR: Llama-3.2-3B_pl-hr-hu-cs sl 0.154
Best FPR: Llama-3.2-3B_de-pl-hr-hu hu 0.062
Best FPR: Llama-3.2-3B_de-pl-hr-hu pl 0.056
Best FPR: Llama-3.2-3B_de-pl-hr-hu sk 0.058
Best FPR: Llama-3.2-3B_de-pl-hr-hu sl 0.15
Best FPR: Llama-3.2-3B_pl-hu de 0.06
Best FPR: Llama-3.2-3B_pl-hu pl 0.052
Best FPR: Llama-3.2-3B_pl-hu sl 0.082
Best FPR: Llama-3.2-3B_hr-hu sk 0.056
Best FPR: Llama-3.2-3B_hr-hu sl 0.168
Best FPR: Llama-3.2-3B_de-hr-hu sl 0.14
Best FPR: Llama-3.2-3B_pl-hr-hu de 0.064
Best FPR: Llama-3.2-3B_pl-hr-hu hr 0.062
Best FPR: Llama-3.2-3B_pl-hr-hu sk 0.082
Best FPR: Llama-3.2-3B_pl-hr-hu sl 0.224
Best FPR: gemma-2-2b_pl-cs de 0.086
Best FPR: gemma-2-2b_pl-hu-cs de 0.074
Best FPR: gemma-2-2b_pl de 0.19
Best FPR: gemma-2-2b_hr sl 0.188
Best FPR: gemma-2-2b_de-hr sl 0.14
Best FPR: gemma-2-2b_pl-hr de 0.102
Best FPR: gemma-2-2b_pl-hr sl 0.16
Best FPR: gemma-2-2b_de-pl-hr sl 0.122
Best FPR: gemma-2-2b_de-hr-cs sl 0.122
Best FPR: gemma-2-2b_pl-hr-cs de 0.06
Best FPR: gemma-2-2b_pl-hr-cs sl 0.122
Best FPR: gemma-2-2b_pl-hr-hu-cs de 0.058
Best FPR: gemma-2-2b_pl-hr-hu-cs sl 0.1
Best FPR: gemma-2-2b_cs pl 0.058
Best FPR: gemma-2-2b_de-hr-hu-cs sk 0.056
Best FPR: gemma-2-2b_de-hr-hu-cs sl 0.112
Best FPR: gemma-2-2b_de-hr-hu sl 0.108
Best FPR: gemma-2-2b_de-pl-hr-cs sl 0.11
Best FPR: gemma-2-2b_de-pl-hr-hu-cs sl 0.098
Best FPR: gemma-2-2b_de-pl-hr-hu sl 0.102
Best FPR: gemma-2-2b_hr-cs de 0.058
Best FPR: gemma-2-2b_hr-cs sl 0.162
Best FPR: gemma-2-2b_hr-hu-cs sl 0.106
Best FPR: gemma-2-2b_hr-hu sl 0.146
Best FPR: gemma-2-2b_pl-hr-hu de 0.058
Best FPR: gemma-2-2b_pl-hr-hu sl 0.14
Best FPR: gemma-2-2b_pl-hu de 0.072
Best FPR: Llama-3.2-3B_de-hr-cs sl 0.106
Best FPR: Llama-3.2-3B_de-pl-hr-hu-cs sl 0.092
Best FPR: xlm-roberta-base_de-hr-cs sl 0.082

100%|██████████| 130/130 [00:01<00:00, 95.48it/s]

\begin{tabular}{lrrrrrrrrrrrrrrrr}
Dataset & \multicolumn{2}{r}{ALL_DATA} & \multicolumn{2}{r}{cs} & \multicolumn{2}{r}{de} & \multicolumn{2}{r}{hr} & \multicolumn{2}{r}{hu} & \multicolumn{2}{r}{pl} & \multicolumn{2}{r}{sk} & \multicolumn{2}{r}{sl} \\
 & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR \\
Detector &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
Llama-3.2-3B_de-pl-hu & \bfseries 0.9758 & \bfseries 0.8869 & \bfseries 0.9886 & \bfseries 0.9440 & \bfseries 0.9739 & 0.8780 & \bfseries 0.9829 & \bfseries 0.9300 & \bfseries 0.9851 & \bfseries 0.9540 & \bfseries 0.9765 & \bfseries 0.8880 & \bfseries 0.9779 & 0.8880 & \bfseries 0.9638 & \bfseries 0.8240 \\
mdeberta-v3-base_de-pl-hr-cs & 0.9739 & 0.8611 & 0.9835 & 0.9360 & 0.9731 & \bfseries 0.8880 & 0.9789 & 0.9140 & 0.9821 & 0.9220 & 0.9727 & 0.8700 & 0.9693 & 0.8020 & 0.9624 & 0.7280 \\
gemma-2-2b_de-pl-cs & 0.9660 & 0.8603 & 0.9837 & \bfseries 0.9440 & 0.9697 & 0.8860 & 0.9546 & 0.8480 & 0.9750 & 0.9340 & 0.9620 & 0.8780 & 0.9765 & \bfseries 0.9100 & 0.9434 & 0.7220 \\
xlm-roberta-base_de-pl-hr-hu-cs & 0.9621 & 0.7974 & 0.9778 & 0.9080 & 0.9484 & 0.7260 & 0.9744 & 0.8800 & 0.9748 & 0.8720 & 0.9541 & 0.7600 & 0.9606 & 0.8260 & 0.9497 & 0.6900 \\
fastdetectgpt & 0.7904 & 0.4089 & 0.7943 & 0.3980 & 0.8074 & 0.5120 & 0.8228 & 0.4580 & 0.7587 & 0.4280 & 0.7830 & 0.4520 & 0.7829 & 0.3720 & 0.8133 & 0.4140 \\
binoculars & 0.7675 & 0.3871 & 0.7811 & 0.4740 & 0.7924 & 0.5040 & 0.8000 & 0.5100 & 0.7517 & 0.4240 & 0.7681 & 0.4200 & 0.7496 & 0.3520 & 0.7650 & 0.4160 \\
llmdeviation & 0.6887 & 0.1806 & 0.7543 & 0.3880 & 0.6666 & 0.2560 & 0.7258 & 0.4300 & 0.6855 & 0.2020 & 0.6991 & 0.3040 & 0.7141 & 0.2540 & 0.7337 & 0.4280 \\
andreas122001-bloomz-3b-mixed-detector & 0.6740 & 0.1540 & 0.6769 & 0.1840 & 0.6945 & 0.2140 & 0.6690 & 0.1500 & 0.6836 & 0.1920 & 0.6752 & 0.1600 & 0.7292 & 0.2380 & 0.5997 & 0.0000 \\
Hello-SimpleAI-chatgpt-detector-roberta-chinese & 0.6492 & 0.1511 & 0.6045 & 0.1540 & 0.7055 & 0.1920 & 0.6442 & 0.1920 & 0.7238 & 0.2320 & 0.6361 & 0.1420 & 0.6885 & 0.2180 & 0.6629 & 0.1720 \\
nealcly-detection-longformer & 0.5629 & 0.0734 & 0.5687 & 0.0740 & 0.4860 & 0.0440 & 0.6519 & 0.1540 & 0.6319 & 0.0680 & 0.5900 & 0.0680 & 0.4636 & 0.1220 & 0.5654 & 0.0820 \\
\end{tabular}

\begin{tabular}{lrrrrrrrrrrrrrrrr}
Dataset & \multicolumn{2}{r}{ALL_DATA} & \multicolumn{2}{r}{cs} & \multicolumn{2}{r}{de} & \multicolumn{2}{r}{hr} & \multicolumn{2}{r}{hu} & \multicolumn{2}{r}{pl} & \multicolumn{2}{r}{sk} & \multicolumn{2}{r}{sl} \\
 & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR \\
Detector &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
mdeberta-v3-base_hu-cs & \bfseries 0.9563 & 0.4186 & \bfseries 0.9759 & 0.9240 & 0.9428 & 0.4420 & 0.9620 & 0.8020 & 0.9799 & 0.9280 & 0.9437 & 0.5160 & 0.9594 & 0.3940 & \bfseries 0.9309 & 0.3780 \\
Llama-3.2-3B_hr & 0.9460 & 0.0000 & 0.9723 & \bfseries 0.9400 & \bfseries 0.9608 & \bfseries 0.8080 & \bfseries 0.9721 & \bfseries 0.9200 & 0.9750 & 0.9140 & \bfseries 0.9524 & \bfseries 0.7420 & \bfseries 0.9627 & \bfseries 0.8320 & 0.8490 & 0.0000 \\
xlm-roberta-base_hr & 0.9061 & 0.0000 & 0.9561 & 0.8140 & 0.8918 & 0.0000 & 0.9666 & 0.8160 & 0.9662 & 0.8660 & 0.9152 & 0.0000 & 0.9111 & 0.0000 & 0.7871 & 0.0000 \\
gemma-2-2b_hu & 0.8998 & \bfseries 0.5806 & 0.9674 & 0.8760 & 0.9277 & 0.7480 & 0.8876 & 0.6080 & \bfseries 0.9827 & \bfseries 0.9560 & 0.9109 & 0.7140 & 0.9338 & 0.7860 & 0.8946 & \bfseries 0.6800 \\
fastdetectgpt & 0.7904 & 0.4089 & 0.7943 & 0.3980 & 0.8074 & 0.5120 & 0.8228 & 0.4580 & 0.7587 & 0.4280 & 0.7830 & 0.4520 & 0.7829 & 0.3720 & 0.8133 & 0.4140 \\
binoculars & 0.7675 & 0.3871 & 0.7811 & 0.4740 & 0.7924 & 0.5040 & 0.8000 & 0.5100 & 0.7517 & 0.4240 & 0.7681 & 0.4200 & 0.7496 & 0.3520 & 0.7650 & 0.4160 \\
llmdeviation & 0.6887 & 0.1806 & 0.7543 & 0.3880 & 0.6666 & 0.2560 & 0.7258 & 0.4300 & 0.6855 & 0.2020 & 0.6991 & 0.3040 & 0.7141 & 0.2540 & 0.7337 & 0.4280 \\
andreas122001-bloomz-3b-mixed-detector & 0.6740 & 0.1540 & 0.6769 & 0.1840 & 0.6945 & 0.2140 & 0.6690 & 0.1500 & 0.6836 & 0.1920 & 0.6752 & 0.1600 & 0.7292 & 0.2380 & 0.5997 & 0.0000 \\
Hello-SimpleAI-chatgpt-detector-roberta-chinese & 0.6492 & 0.1511 & 0.6045 & 0.1540 & 0.7055 & 0.1920 & 0.6442 & 0.1920 & 0.7238 & 0.2320 & 0.6361 & 0.1420 & 0.6885 & 0.2180 & 0.6629 & 0.1720 \\
nealcly-detection-longformer & 0.5629 & 0.0734 & 0.5687 & 0.0740 & 0.4860 & 0.0440 & 0.6519 & 0.1540 & 0.6319 & 0.0680 & 0.5900 & 0.0680 & 0.4636 & 0.1220 & 0.5654 & 0.0820 \\
\end{tabular}

In [ ]:
#statistical significance of per-train-languages-combination results (mean across base models)
temp = results_all[results_all['Detector'].str.contains('_')].pivot_table('AUC ROC', 'Detector', "Dataset").sort_index(axis='columns')
temp = temp.sort_values(by='ALL_DATA', ascending=False)
temp['temp'] = ['-'.join(sorted(x.split('_')[1].split('-'))) for x in temp.index]
temp = temp[['temp', 'ALL_DATA']].copy()

#temp = temp.pivot(index=['Category', 'Detector'], columns='temp', values='ALL_DATA').reset_index()

res_df = pd.DataFrame()
significant = 0
not_significant = 0
for (src, trg) in itertools.combinations_with_replacement(temp.temp.unique(), 2):
   if src == trg: continue
   print(f"({trg}, {src})")
   res = pg.ttest(temp[temp["temp"] == trg]['ALL_DATA'], temp[temp["temp"] == src]['ALL_DATA'], paired=True)
   if res.loc['T-test', 'p-val'] < 0.05:
     significant += 1
     display(res)#.style.apply(lambda _: np.where(res['p-val'] >= 0.05, 'background-color: yellow', '')))
   else:
      not_significant += 1
print(f"significant: {significant}\n not significant: {not_significant}")

(de-pl, de-hu-pl)
(cs-de-hr-pl, de-hu-pl)
(cs-de-pl, de-hu-pl)
(cs-de-hr-hu-pl, de-hu-pl)
(pl, de-hu-pl)
(de-hr-hu-pl, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.352918,3,two-sided,0.043964,"[-0.01, -0.0]",0.604213,2.599,0.139393

(de-hu, de-hu-pl)
(cs-de, de-hu-pl)
(cs-de-hu-pl, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.457243,3,two-sided,0.021022,"[-0.01, -0.0]",0.530403,4.277,0.118945

(cs-hu-pl, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.926569,3,two-sided,0.016029,"[-0.01, -0.0]",0.587953,5.131,0.134668

(hr-pl, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.649592,3,two-sided,0.018761,"[-0.02, -0.0]",1.115673,4.617,0.342341

(cs-hr-hu, de-hu-pl)
(de, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.248238,3,two-sided,0.047553,"[-0.04, -0.0]",1.235199,2.464,0.400506

(cs-pl, de-hu-pl)
(hr-hu, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.236807,3,two-sided,0.047967,"[-0.04, -0.0]",1.268604,2.45,0.417091

(cs-hr-pl, de-hu-pl)
(cs, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.403746,3,two-sided,0.021714,"[-0.02, -0.0]",1.0492,4.185,0.311145

(de-hr, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.722541,3,two-sided,0.01059,"[-0.01, -0.0]",1.076965,6.767,0.324053

(de-hr-hu, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.703202,3,two-sided,0.010691,"[-0.01, -0.0]",0.93992,6.725,0.262346

(cs-de-hr-hu, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.389925,3,two-sided,0.042777,"[-0.01, -0.0]",0.665676,2.648,0.158353

(de-hr-pl, de-hu-pl)
(cs-de-hr, de-hu-pl)
(cs-de-hu, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-6.676204,3,two-sided,0.006853,"[-0.01, -0.0]",0.93619,9.042,0.260744

(hu-pl, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-9.568349,3,two-sided,0.002422,"[-0.01, -0.01]",0.947134,18.016,0.265458

(cs-hr-hu-pl, de-hu-pl)
(hr-hu-pl, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.895376,3,two-sided,0.009743,"[-0.02, -0.0]",1.27923,7.154,0.422387

(cs-hu, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-8.20538,3,two-sided,0.003788,"[-0.02, -0.01]",1.433386,13.398,0.499625

(cs-hr, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-6.386879,3,two-sided,0.007772,"[-0.03, -0.01]",1.535724,8.316,0.550409

(hu, de-hu-pl)
(hr, de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.922939,3,two-sided,0.016061,"[-0.06, -0.01]",1.949761,5.124,0.735781

(cs-de-hr-pl, de-pl)
(cs-de-pl, de-pl)
(cs-de-hr-hu-pl, de-pl)
(pl, de-pl)
(de-hr-hu-pl, de-pl)
(de-hu, de-pl)
(cs-de, de-pl)
(cs-de-hu-pl, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-7.255821,3,two-sided,0.005401,"[-0.01, -0.0]",0.540807,10.59,0.121671

(cs-hu-pl, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.756899,3,two-sided,0.03296,"[-0.01, -0.0]",0.59891,3.159,0.137838

(hr-pl, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.319276,3,two-sided,0.022866,"[-0.02, -0.0]",1.148147,4.042,0.357916

(cs-hr-hu, de-pl)
(de, de-pl)
(cs-pl, de-pl)
(hr-hu, de-pl)
(cs-hr-pl, de-pl)
(cs, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.532226,3,two-sided,0.038578,"[-0.02, -0.0]",1.064814,2.84,0.318381

(de-hr, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-7.414647,3,two-sided,0.005075,"[-0.01, -0.01]",1.120553,11.036,0.344669

(de-hr-hu, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-10.26449,3,two-sided,0.001972,"[-0.01, -0.01]",0.982955,20.643,0.281151

(cs-de-hr-hu, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.164916,3,two-sided,0.014079,"[-0.01, -0.0]",0.692752,5.596,0.167247

(de-hr-pl, de-pl)
(cs-de-hr, de-pl)
(cs-de-hu, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-9.700363,3,two-sided,0.002327,"[-0.01, -0.01]",0.974761,18.5,0.277526

(hu-pl, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-12.753649,3,two-sided,0.00104,"[-0.01, -0.01]",0.987553,31.515,0.283193

(cs-hr-hu-pl, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.498299,3,two-sided,0.039529,"[-0.01, -0.0]",0.972875,2.793,0.276696

(hr-hu-pl, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-8.842676,3,two-sided,0.003048,"[-0.01, -0.01]",1.35526,15.471,0.460453

(cs-hu, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-9.520156,3,two-sided,0.002458,"[-0.02, -0.01]",1.492232,17.841,0.528944

(cs-hr, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.616931,3,two-sided,0.011156,"[-0.03, -0.01]",1.570331,6.537,0.56732

(hu, de-pl)
(hr, de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.535507,3,two-sided,0.020062,"[-0.06, -0.01]",1.967819,4.414,0.74278

(cs-de-pl, cs-de-hr-pl)
(cs-de-hr-hu-pl, cs-de-hr-pl)
(pl, cs-de-hr-pl)
(de-hr-hu-pl, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.588203,3,two-sided,0.03707,"[-0.01, -0.0]",0.514141,2.918,0.114787

(de-hu, cs-de-hr-pl)
(cs-de, cs-de-hr-pl)
(cs-de-hu-pl, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.087984,3,two-sided,0.014673,"[-0.01, -0.0]",0.430261,5.443,0.09537

(cs-hu-pl, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.653794,3,two-sided,0.010954,"[-0.01, -0.0]",0.496598,6.617,0.110444

(hr-pl, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.39848,3,two-sided,0.021783,"[-0.02, -0.0]",1.063144,4.176,0.317605

(cs-hr-hu, cs-de-hr-pl)
(de, cs-de-hr-pl)
(cs-pl, cs-de-hr-pl)
(hr-hu, cs-de-hr-pl)
(cs-hr-pl, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.336497,3,two-sided,0.044503,"[-0.01, -0.0]",0.43939,2.578,0.097318

(cs, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.276162,3,two-sided,0.04656,"[-0.02, -0.0]",0.993947,2.5,0.286043

(de-hr, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.67872,3,two-sided,0.018446,"[-0.01, -0.0]",1.024454,4.669,0.299801

(de-hr-hu, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.467893,3,two-sided,0.012024,"[-0.01, -0.0]",0.877445,6.218,0.236123

(cs-de-hr-hu, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.296322,3,two-sided,0.04586,"[-0.01, -0.0]",0.575115,2.526,0.131025

(de-hr-pl, cs-de-hr-pl)
(cs-de-hr, cs-de-hr-pl)
(cs-de-hu, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.600756,3,two-sided,0.019304,"[-0.01, -0.0]",0.872733,4.529,0.234201

(hu-pl, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-6.948359,3,two-sided,0.006114,"[-0.01, -0.0]",0.884798,9.753,0.23914

(cs-hr-hu-pl, cs-de-hr-pl)
(hr-hu-pl, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-6.845632,3,two-sided,0.00638,"[-0.01, -0.0]",1.252705,9.481,0.409184

(cs-hu, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.845265,3,two-sided,0.009979,"[-0.02, -0.01]",1.405315,7.041,0.485568

(cs-hr, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.601369,3,two-sided,0.019297,"[-0.03, -0.01]",1.500946,4.53,0.533261

(hu, cs-de-hr-pl)
(hr, cs-de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.284797,3,two-sided,0.023359,"[-0.06, -0.01]",1.920249,3.985,0.724115

(cs-de-hr-hu-pl, cs-de-pl)
(pl, cs-de-pl)
(de-hr-hu-pl, cs-de-pl)
(de-hu, cs-de-pl)
(cs-de, cs-de-pl)
(cs-de-hu-pl, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.246821,3,two-sided,0.047604,"[-0.01, -0.0]",0.52039,2.463,0.11637

(cs-hu-pl, cs-de-pl)
(hr-pl, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.938318,3,two-sided,0.029169,"[-0.02, -0.0]",1.1714,3.431,0.369184

(cs-hr-hu, cs-de-pl)
(de, cs-de-pl)
(cs-pl, cs-de-pl)
(hr-hu, cs-de-pl)
(cs-hr-pl, cs-de-pl)
(cs, cs-de-pl)
(de-hr, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.792708,3,two-sided,0.010235,"[-0.01, -0.0]",1.162998,6.923,0.365102

(de-hr-hu, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-7.08697,3,two-sided,0.005778,"[-0.01, -0.0]",1.024979,10.126,0.30004

(cs-de-hr-hu, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.222042,3,two-sided,0.048509,"[-0.01, -0.0]",0.703474,2.431,0.170858

(de-hr-pl, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.955945,3,two-sided,0.028831,"[-0.01, -0.0]",0.751633,3.458,0.187691

(cs-de-hr, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.562924,3,two-sided,0.011461,"[-0.01, -0.0]",0.957245,6.42,0.269848

(cs-de-hu, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.720168,3,two-sided,0.033803,"[-0.01, -0.0]",1.007998,3.106,0.292348

(hu-pl, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.78522,3,two-sided,0.032328,"[-0.01, -0.0]",1.024326,3.201,0.299743

(cs-hr-hu-pl, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.749906,3,two-sided,0.017706,"[-0.01, -0.0]",1.045869,4.8,0.309609

(hr-hu-pl, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-20.234581,3,two-sided,0.000264,"[-0.01, -0.01]",1.463425,78.148,0.514623

(cs-hu, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.75052,3,two-sided,0.010447,"[-0.02, -0.01]",1.561878,6.829,0.563205

(cs-hr, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.847975,3,two-sided,0.030982,"[-0.03, -0.0]",1.599309,3.294,0.581344

(hu, cs-de-pl)
(hr, cs-de-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.821449,3,two-sided,0.031542,"[-0.06, -0.01]",1.976841,3.254,0.746236

(pl, cs-de-hr-hu-pl)
(de-hr-hu-pl, cs-de-hr-hu-pl)
(de-hu, cs-de-hr-hu-pl)
(cs-de, cs-de-hr-hu-pl)
(cs-de-hu-pl, cs-de-hr-hu-pl)
(cs-hu-pl, cs-de-hr-hu-pl)
(hr-pl, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.583916,3,two-sided,0.037183,"[-0.02, -0.0]",1.375227,2.912,0.470474

(cs-hr-hu, cs-de-hr-hu-pl)
(de, cs-de-hr-hu-pl)
(cs-pl, cs-de-hr-hu-pl)
(hr-hu, cs-de-hr-hu-pl)
(cs-hr-pl, cs-de-hr-hu-pl)
(cs, cs-de-hr-hu-pl)
(de-hr, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.658231,3,two-sided,0.018667,"[-0.02, -0.0]",1.4218,4.632,0.493827

(de-hr-hu, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.499143,3,two-sided,0.011835,"[-0.01, -0.0]",1.316803,6.284,0.44117

(cs-de-hr-hu, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.093053,3,two-sided,0.026368,"[-0.01, -0.0]",1.003724,3.672,0.290424

(de-hr-pl, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-7.892395,3,two-sided,0.004239,"[-0.01, -0.0]",1.137243,12.435,0.352664

(cs-de-hr, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-11.690534,3,two-sided,0.001345,"[-0.01, -0.0]",1.377162,26.588,0.471445

(cs-de-hu, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.845184,3,two-sided,0.031041,"[-0.02, -0.0]",1.276449,3.29,0.421

(hu-pl, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.012239,3,two-sided,0.027785,"[-0.01, -0.0]",1.299581,3.545,0.432551

(cs-hr-hu-pl, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-6.270615,3,two-sided,0.008187,"[-0.01, -0.0]",1.433417,8.033,0.499641

(hr-hu-pl, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-9.985232,3,two-sided,0.002138,"[-0.01, -0.01]",1.827748,19.567,0.685783

(cs-hu, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.070067,3,two-sided,0.014816,"[-0.02, -0.01]",1.821295,5.408,0.683014

(cs-hr, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.697815,3,two-sided,0.03433,"[-0.03, -0.0]",1.767587,3.073,0.659513

(hu, cs-de-hr-hu-pl)
(hr, cs-de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.709061,3,two-sided,0.034064,"[-0.06, -0.0]",2.077172,3.089,0.782815

(de-hr-hu-pl, pl)
(de-hu, pl)
(cs-de, pl)
(cs-de-hu-pl, pl)
(cs-hu-pl, pl)
(hr-pl, pl)
(cs-hr-hu, pl)
(de, pl)
(cs-pl, pl)
(hr-hu, pl)
(cs-hr-pl, pl)
(cs, pl)
(de-hr, pl)
(de-hr-hu, pl)
(cs-de-hr-hu, pl)
(de-hr-pl, pl)
(cs-de-hr, pl)
(cs-de-hu, pl)
(hu-pl, pl)
(cs-hr-hu-pl, pl)
(hr-hu-pl, pl)
(cs-hu, pl)
(cs-hr, pl)
(hu, pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.975229,3,two-sided,0.028467,"[-0.04, -0.0]",0.778898,3.488,0.197655

(hr, pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-6.048567,3,two-sided,0.009065,"[-0.03, -0.01]",0.962882,7.507,0.272309

(de-hu, de-hr-hu-pl)
(cs-de, de-hr-hu-pl)
(cs-de-hu-pl, de-hr-hu-pl)
(cs-hu-pl, de-hr-hu-pl)
(hr-pl, de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.913269,3,two-sided,0.016148,"[-0.01, -0.0]",0.58068,5.105,0.132595

(cs-hr-hu, de-hr-hu-pl)
(de, de-hr-hu-pl)
(cs-pl, de-hr-hu-pl)
(hr-hu, de-hr-hu-pl)
(cs-hr-pl, de-hr-hu-pl)
(cs, de-hr-hu-pl)
(de-hr, de-hr-hu-pl)
(de-hr-hu, de-hr-hu-pl)
(cs-de-hr-hu, de-hr-hu-pl)
(de-hr-pl, de-hr-hu-pl)
(cs-de-hr, de-hr-hu-pl)
(cs-de-hu, de-hr-hu-pl)
(hu-pl, de-hr-hu-pl)
(cs-hr-hu-pl, de-hr-hu-pl)
(hr-hu-pl, de-hr-hu-pl)
(cs-hu, de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.195092,3,two-sided,0.049518,"[-0.02, -0.0]",0.861021,2.398,0.229456

(cs-hr, de-hr-hu-pl)
(hu, de-hr-hu-pl)
(hr, de-hr-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.801928,3,two-sided,0.031963,"[-0.05, -0.0]",1.641873,3.225,0.601681

(cs-de, de-hu)
(cs-de-hu-pl, de-hu)
(cs-hu-pl, de-hu)
(hr-pl, de-hu)
(cs-hr-hu, de-hu)
(de, de-hu)
(cs-pl, de-hu)
(hr-hu, de-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.56576,3,two-sided,0.037665,"[-0.02, -0.0]",0.678599,2.886,0.162557

(cs-hr-pl, de-hu)
(cs, de-hu)
(de-hr, de-hu)
(de-hr-hu, de-hu)
(cs-de-hr-hu, de-hu)
(de-hr-pl, de-hu)
(cs-de-hr, de-hu)
(cs-de-hu, de-hu)
(hu-pl, de-hu)
(cs-hr-hu-pl, de-hu)
(hr-hu-pl, de-hu)
(cs-hu, de-hu)
(cs-hr, de-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-15.740712,3,two-sided,0.000557,"[-0.01, -0.01]",0.741524,47.622,0.184076

(hu, de-hu)
(hr, de-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.314112,3,two-sided,0.013014,"[-0.04, -0.01]",1.378193,5.898,0.471963

(cs-de-hu-pl, cs-de)
(cs-hu-pl, cs-de)
(hr-pl, cs-de)
(cs-hr-hu, cs-de)
(de, cs-de)
(cs-pl, cs-de)
(hr-hu, cs-de)
(cs-hr-pl, cs-de)
(cs, cs-de)
(de-hr, cs-de)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.932313,3,two-sided,0.029285,"[-0.02, -0.0]",1.335022,3.422,0.450301

(de-hr-hu, cs-de)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.291813,3,two-sided,0.023258,"[-0.01, -0.0]",1.220008,3.996,0.393001

(cs-de-hr-hu, cs-de)
(de-hr-pl, cs-de)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-11.859522,3,two-sided,0.001289,"[-0.01, -0.0]",1.014191,27.343,0.295144

(cs-de-hr, cs-de)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-19.081632,3,two-sided,0.000314,"[-0.01, -0.0]",1.268999,69.595,0.417288

(cs-de-hu, cs-de)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.244182,3,two-sided,0.047699,"[-0.01, -0.0]",1.182019,2.459,0.374359

(hu-pl, cs-de)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.255091,3,two-sided,0.047307,"[-0.01, -0.0]",1.204899,2.473,0.385563

(cs-hr-hu-pl, cs-de)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-6.540345,3,two-sided,0.007266,"[-0.01, -0.0]",1.331279,8.697,0.448424

(hr-hu-pl, cs-de)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-7.418855,3,two-sided,0.005067,"[-0.01, -0.01]",1.746627,11.048,0.650133

(cs-hu, cs-de)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.516305,3,two-sided,0.020292,"[-0.02, -0.0]",1.747421,4.38,0.65049

(cs-hr, cs-de)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.392978,3,two-sided,0.042681,"[-0.03, -0.0]",1.706424,2.652,0.631833

(hu, cs-de)
(hr, cs-de)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.507452,3,two-sided,0.03927,"[-0.06, -0.0]",2.035293,2.806,0.767966

(cs-hu-pl, cs-de-hu-pl)
(hr-pl, cs-de-hu-pl)
(cs-hr-hu, cs-de-hu-pl)
(de, cs-de-hu-pl)
(cs-pl, cs-de-hu-pl)
(hr-hu, cs-de-hu-pl)
(cs-hr-pl, cs-de-hu-pl)
(cs, cs-de-hu-pl)
(de-hr, cs-de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.33316,3,two-sided,0.022671,"[-0.01, -0.0]",0.621156,4.065,0.144447

(de-hr-hu, cs-de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.066598,3,two-sided,0.014844,"[-0.01, -0.0]",0.437752,5.401,0.096965

(cs-de-hr-hu, cs-de-hu-pl)
(de-hr-pl, cs-de-hu-pl)
(cs-de-hr, cs-de-hu-pl)
(cs-de-hu, cs-de-hu-pl)
(hu-pl, cs-de-hu-pl)
(cs-hr-hu-pl, cs-de-hu-pl)
(hr-hu-pl, cs-de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-7.206302,3,two-sided,0.005508,"[-0.01, -0.0]",0.794567,10.453,0.203518

(cs-hu, cs-de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-5.518228,3,two-sided,0.011721,"[-0.01, -0.0]",1.02467,6.325,0.2999

(cs-hr, cs-de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.844487,3,two-sided,0.031055,"[-0.03, -0.0]",1.209096,3.289,0.387626

(hu, cs-de-hu-pl)
(hr, cs-de-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.85523,3,two-sided,0.030832,"[-0.05, -0.01]",1.725442,3.305,0.640538

(hr-pl, cs-hu-pl)
(cs-hr-hu, cs-hu-pl)
(de, cs-hu-pl)
(cs-pl, cs-hu-pl)
(hr-hu, cs-hu-pl)
(cs-hr-pl, cs-hu-pl)
(cs, cs-hu-pl)
(de-hr, cs-hu-pl)
(de-hr-hu, cs-hu-pl)
(cs-de-hr-hu, cs-hu-pl)
(de-hr-pl, cs-hu-pl)
(cs-de-hr, cs-hu-pl)
(cs-de-hu, cs-hu-pl)
(hu-pl, cs-hu-pl)
(cs-hr-hu-pl, cs-hu-pl)
(hr-hu-pl, cs-hu-pl)
(cs-hu, cs-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.245581,3,two-sided,0.047649,"[-0.02, -0.0]",0.87692,2.461,0.235909

(cs-hr, cs-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.478802,3,two-sided,0.04009,"[-0.02, -0.0]",1.097124,2.767,0.333537

(hu, cs-hu-pl)
(hr, cs-hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.93144,3,two-sided,0.029302,"[-0.05, -0.01]",1.650365,3.42,0.605698

(cs-hr-hu, hr-pl)
(de, hr-pl)
(cs-pl, hr-pl)
(hr-hu, hr-pl)
(cs-hr-pl, hr-pl)
(cs, hr-pl)
(de-hr, hr-pl)
(de-hr-hu, hr-pl)
(cs-de-hr-hu, hr-pl)
(de-hr-pl, hr-pl)
(cs-de-hr, hr-pl)
(cs-de-hu, hr-pl)
(hu-pl, hr-pl)
(cs-hr-hu-pl, hr-pl)
(hr-hu-pl, hr-pl)
(cs-hu, hr-pl)
(cs-hr, hr-pl)
(hu, hr-pl)
(hr, hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.258211,3,two-sided,0.047195,"[-0.04, -0.0]",1.265528,2.477,0.415559

(de, cs-hr-hu)
(cs-pl, cs-hr-hu)
(hr-hu, cs-hr-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.8819,3,two-sided,0.030285,"[-0.02, -0.0]",0.464397,3.345,0.10286

(cs-hr-pl, cs-hr-hu)
(cs, cs-hr-hu)
(de-hr, cs-hr-hu)
(de-hr-hu, cs-hr-hu)
(cs-de-hr-hu, cs-hr-hu)
(de-hr-pl, cs-hr-hu)
(cs-de-hr, cs-hr-hu)
(cs-de-hu, cs-hr-hu)
(hu-pl, cs-hr-hu)
(cs-hr-hu-pl, cs-hr-hu)
(hr-hu-pl, cs-hr-hu)
(cs-hu, cs-hr-hu)
(cs-hr, cs-hr-hu)
(hu, cs-hr-hu)
(hr, cs-hr-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.123629,3,two-sided,0.025856,"[-0.04, -0.01]",1.153475,3.721,0.36049

(cs-pl, de)
(hr-hu, de)
(cs-hr-pl, de)
(cs, de)
(de-hr, de)
(de-hr-hu, de)
(cs-de-hr-hu, de)
(de-hr-pl, de)
(cs-de-hr, de)
(cs-de-hu, de)
(hu-pl, de)
(cs-hr-hu-pl, de)
(hr-hu-pl, de)
(cs-hu, de)
(cs-hr, de)
(hu, de)
(hr, de)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-19.371399,3,two-sided,0.0003,"[-0.02, -0.01]",0.598032,71.698,0.137582

(hr-hu, cs-pl)
(cs-hr-pl, cs-pl)
(cs, cs-pl)
(de-hr, cs-pl)
(de-hr-hu, cs-pl)
(cs-de-hr-hu, cs-pl)
(de-hr-pl, cs-pl)
(cs-de-hr, cs-pl)
(cs-de-hu, cs-pl)
(hu-pl, cs-pl)
(cs-hr-hu-pl, cs-pl)
(hr-hu-pl, cs-pl)
(cs-hu, cs-pl)
(cs-hr, cs-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.308937,3,two-sided,0.045428,"[-0.01, -0.0]",0.405125,2.542,0.090219

(hu, cs-pl)
(hr, cs-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-6.285769,3,two-sided,0.008132,"[-0.03, -0.01]",1.086812,8.069,0.328675

(cs-hr-pl, hr-hu)
(cs, hr-hu)
(de-hr, hr-hu)
(de-hr-hu, hr-hu)
(cs-de-hr-hu, hr-hu)
(de-hr-pl, hr-hu)
(cs-de-hr, hr-hu)
(cs-de-hu, hr-hu)
(hu-pl, hr-hu)
(cs-hr-hu-pl, hr-hu)
(hr-hu-pl, hr-hu)
(cs-hu, hr-hu)
(cs-hr, hr-hu)
(hu, hr-hu)
(hr, hr-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.455096,3,two-sided,0.040785,"[-0.03, -0.0]",0.682325,2.735,0.163783

(cs, cs-hr-pl)
(de-hr, cs-hr-pl)
(de-hr-hu, cs-hr-pl)
(cs-de-hr-hu, cs-hr-pl)
(de-hr-pl, cs-hr-pl)
(cs-de-hr, cs-hr-pl)
(cs-de-hu, cs-hr-pl)
(hu-pl, cs-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.594248,3,two-sided,0.036912,"[-0.01, -0.0]",0.510983,2.926,0.113994

(cs-hr-hu-pl, cs-hr-pl)
(hr-hu-pl, cs-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.339143,3,two-sided,0.044416,"[-0.01, -0.0]",0.882184,2.581,0.238065

(cs-hu, cs-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.429042,3,two-sided,0.041567,"[-0.02, -0.0]",1.098645,2.7,0.334256

(cs-hr, cs-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.296894,3,two-sided,0.04584,"[-0.03, -0.0]",1.260115,2.527,0.412867

(hu, cs-hr-pl)
(hr, cs-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.576154,3,two-sided,0.037388,"[-0.06, -0.0]",1.757543,2.901,0.655032

(de-hr, cs)
(de-hr-hu, cs)
(cs-de-hr-hu, cs)
(de-hr-pl, cs)
(cs-de-hr, cs)
(cs-de-hu, cs)
(hu-pl, cs)
(cs-hr-hu-pl, cs)
(hr-hu-pl, cs)
(cs-hu, cs)
(cs-hr, cs)
(hu, cs)
(hr, cs)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.777047,3,two-sided,0.017434,"[-0.03, -0.01]",1.093456,4.85,0.331805

(de-hr-hu, de-hr)
(cs-de-hr-hu, de-hr)
(de-hr-pl, de-hr)
(cs-de-hr, de-hr)
(cs-de-hu, de-hr)
(hu-pl, de-hr)
(cs-hr-hu-pl, de-hr)
(hr-hu-pl, de-hr)
(cs-hu, de-hr)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.668802,3,two-sided,0.018553,"[-0.01, -0.0]",0.416417,4.652,0.092495

(cs-hr, de-hr)
(hu, de-hr)
(hr, de-hr)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.279657,3,two-sided,0.046438,"[-0.05, -0.0]",1.40618,2.504,0.486001

(cs-de-hr-hu, de-hr-hu)
(de-hr-pl, de-hr-hu)
(cs-de-hr, de-hr-hu)
(cs-de-hu, de-hr-hu)
(hu-pl, de-hr-hu)
(cs-hr-hu-pl, de-hr-hu)
(hr-hu-pl, de-hr-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.703419,3,two-sided,0.018185,"[-0.0, -0.0]",0.346887,4.714,0.079474

(cs-hu, de-hr-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.412389,3,two-sided,0.0216,"[-0.01, -0.0]",0.657079,4.2,0.155598

(cs-hr, de-hr-hu)
(hu, de-hr-hu)
(hr, de-hr-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.329749,3,two-sided,0.044728,"[-0.05, -0.0]",1.538671,2.569,0.551855

(de-hr-pl, cs-de-hr-hu)
(cs-de-hr, cs-de-hr-hu)
(cs-de-hu, cs-de-hr-hu)
(hu-pl, cs-de-hr-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.347235,3,two-sided,0.044149,"[-0.01, -0.0]",0.401537,2.592,0.089509

(cs-hr-hu-pl, cs-de-hr-hu)
(hr-hu-pl, cs-de-hr-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.429112,3,two-sided,0.021382,"[-0.01, -0.0]",0.775615,4.229,0.196439

(cs-hu, cs-de-hr-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.211855,3,two-sided,0.024449,"[-0.01, -0.0]",1.01337,3.864,0.294773

(cs-hr, cs-de-hr-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.296305,3,two-sided,0.04586,"[-0.03, -0.0]",1.194395,2.526,0.38041

(hu, cs-de-hr-hu)
(hr, cs-de-hr-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.450714,3,two-sided,0.040915,"[-0.05, -0.0]",1.713895,2.729,0.635263

(cs-de-hr, de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.201006,3,two-sided,0.024616,"[-0.0, -0.0]",0.243078,3.846,0.064458

(cs-de-hu, de-hr-pl)
(hu-pl, de-hr-pl)
(cs-hr-hu-pl, de-hr-pl)
(hr-hu-pl, de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.329126,3,two-sided,0.022728,"[-0.01, -0.0]",0.9343,4.059,0.259934

(cs-hu, de-hr-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.228244,3,two-sided,0.04828,"[-0.02, -0.0]",1.13615,2.439,0.352139

(cs-hr, de-hr-pl)
(hu, de-hr-pl)
(hr, de-hr-pl)
(cs-de-hu, cs-de-hr)
(hu-pl, cs-de-hr)
(cs-hr-hu-pl, cs-de-hr)
(hr-hu-pl, cs-de-hr)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.466938,3,two-sided,0.040436,"[-0.01, -0.0]",0.743096,2.751,0.184635

(cs-hu, cs-de-hr)
(cs-hr, cs-de-hr)
(hu, cs-de-hr)
(hr, cs-de-hr)
(hu-pl, cs-de-hu)
(cs-hr-hu-pl, cs-de-hu)
(hr-hu-pl, cs-de-hu)
(cs-hu, cs-de-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-4.26714,3,two-sided,0.023617,"[-0.01, -0.0]",0.609031,3.955,0.140816

(cs-hr, cs-de-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.339986,3,two-sided,0.044388,"[-0.02, -0.0]",0.889819,2.582,0.24121

(hu, cs-de-hu)
(hr, cs-de-hu)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.432294,3,two-sided,0.041468,"[-0.05, -0.0]",1.511746,2.704,0.5386

(cs-hr-hu-pl, hu-pl)
(hr-hu-pl, hu-pl)
(cs-hu, hu-pl)
(cs-hr, hu-pl)
(hu, hu-pl)
(hr, hu-pl)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.424284,3,two-sided,0.041712,"[-0.05, -0.0]",1.513872,2.694,0.53965

(hr-hu-pl, cs-hr-hu-pl)
(cs-hu, cs-hr-hu-pl)
(cs-hr, cs-hr-hu-pl)
(hu, cs-hr-hu-pl)
(hr, cs-hr-hu-pl)
(cs-hu, hr-hu-pl)
(cs-hr, hr-hu-pl)
(hu, hr-hu-pl)
(hr, hr-hu-pl)
(cs-hr, cs-hu)
(hu, cs-hu)
(hr, cs-hu)
(hu, cs-hr)
(hr, cs-hr)

,T,dof,alternative,p-val,CI95%,cohen-d,BF10,power
T-test,-3.353521,3,two-sided,0.043944,"[-0.03, -0.0]",0.8252,2.6,0.215263

(hr, hu)
significant: 132
 not significant: 333

In [17]:
statistical = ['binoculars', 'fastdetectgpt', 'llmdeviation']
pretrained = ['andreas122001-bloomz-3b-mixed-detector', 'Hello-SimpleAI-chatgpt-detector-roberta-chinese', 'nealcly-detection-longformer']

In [32]:
df.corr(numeric_only=True).iloc[2][9:].describe()

count    124.000000
mean       0.059047
std        0.044424
min       -0.053709
25%        0.032399
50%        0.057537
75%        0.082611
max        0.197213
Name: length, dtype: float64

In [28]:
print_full(df.corr(numeric_only=True).iloc[2])

index                                                            -0.41
label                                                             0.10
length                                                            1.00
Hello-SimpleAI-chatgpt-detector-roberta-chinese                   0.17
andreas122001-bloomz-3b-mixed-detector                           -0.27
binoculars                                                        0.40
fastdetectgpt                                                     0.38
llmdeviation                                                      0.52
nealcly-detection-longformer                                      0.02
xlm-roberta-base_hr-cs                                            0.01
xlm-roberta-base_de-hu-cs                                         0.01
xlm-roberta-base_de-hr-hu-cs                                      0.03
xlm-roberta-base_de-hr                                            0.04
xlm-roberta-base_de-hr-hu                                        -0.00
xlm-roberta-base_hu                                              -0.05
xlm-roberta-base_de-hu                                            0.02
xlm-roberta-base_pl                                               0.08
xlm-roberta-base_de-pl-hr-cs                                      0.07
xlm-roberta-base_de-pl-hu                                         0.06
xlm-roberta-base_de-pl-hr-hu                                      0.08
xlm-roberta-base_de-pl-hr                                         0.10
xlm-roberta-base_de-pl-hu-cs                                      0.06
xlm-roberta-base_de-pl                                            0.06
xlm-roberta-base_de                                               0.20
xlm-roberta-base_hu-cs                                            0.01
xlm-roberta-base_hr                                               0.02
xlm-roberta-base_hr-hu                                            0.03
xlm-roberta-base_pl-cs                                            0.12
xlm-roberta-base_pl-hu-cs                                         0.02
xlm-roberta-base_pl-hr-hu-cs                                      0.01
xlm-roberta-base_pl-hr                                            0.05
xlm-roberta-base_pl-hr-hu                                         0.01
xlm-roberta-base_pl-hu                                            0.04
mdeberta-v3-base_hr-cs                                            0.04
mdeberta-v3-base_de-hu-cs                                         0.06
mdeberta-v3-base_de-hr-hu-cs                                      0.02
mdeberta-v3-base_de-hr                                            0.07
mdeberta-v3-base_de-hr-hu                                         0.00
mdeberta-v3-base_hu                                              -0.01
mdeberta-v3-base_de-hu                                            0.06
mdeberta-v3-base_pl                                               0.05
mdeberta-v3-base_de-pl-hr-cs                                      0.05
mdeberta-v3-base_de-pl-hu                                         0.07
mdeberta-v3-base_de-pl-hr-hu                                      0.07
mdeberta-v3-base_de-pl-hr                                         0.10
mdeberta-v3-base_de-pl-hu-cs                                      0.12
mdeberta-v3-base_de-pl                                            0.09
mdeberta-v3-base_de                                               0.12
mdeberta-v3-base_hu-cs                                            0.00
mdeberta-v3-base_hr                                              -0.00
xlm-roberta-base_cs                                               0.06
mdeberta-v3-base_hr-hu                                            0.04
mdeberta-v3-base_pl-cs                                            0.06
xlm-roberta-base_de-cs                                            0.05
mdeberta-v3-base_pl-hu-cs                                         0.06
mdeberta-v3-base_pl-hr-hu-cs                                      0.08
mdeberta-v3-base_pl-hr                                            0.00
mdeberta-v3-base_pl-hr-hu                                         0.01
mdeberta-v3-base_pl-hu                                            0.07
Llama-3.2-3B_hr-cs                                                0.04
mdeberta-v3-base_cs                                               0.02
Llama-3.2-3B_pl                                                   0.07
Llama-3.2-3B_hr                                                   0.05
Llama-3.2-3B_de-pl-hu                                             0.09
Llama-3.2-3B_hu                                                   0.04
Llama-3.2-3B_de                                                   0.11
Llama-3.2-3B_de-hr                                                0.03
Llama-3.2-3B_pl-hr                                                0.04
Llama-3.2-3B_de-pl-hr                                             0.06
Llama-3.2-3B_pl-hr-cs                                             0.00
Llama-3.2-3B_de-pl-hr-cs                                          0.08
Llama-3.2-3B_hr-hu-cs                                             0.04
Llama-3.2-3B_de-hr-hu-cs                                          0.04
Llama-3.2-3B_pl-hr-hu-cs                                          0.03
Llama-3.2-3B_de-pl-hr-hu                                          0.07
Llama-3.2-3B_de-hu                                                0.05
Llama-3.2-3B_pl-hu                                                0.04
Llama-3.2-3B_de-pl                                                0.05
Llama-3.2-3B_hr-hu                                               -0.04
Llama-3.2-3B_de-hr-hu                                            -0.05
Llama-3.2-3B_pl-hr-hu                                             0.01
Llama-3.2-3B_de-pl-hu-cs                                          0.08
gemma-2-2b_pl-cs                                                  0.12
gemma-2-2b_de                                                     0.18
gemma-2-2b_pl-hu-cs                                               0.10
gemma-2-2b_de-hu-cs                                               0.11
gemma-2-2b_de-pl-hu                                               0.14
gemma-2-2b_de-pl-cs                                               0.11
gemma-2-2b_pl                                                     0.14
Llama-3.2-3B_cs                                                   0.08
gemma-2-2b_de-pl                                                  0.13
gemma-2-2b_hr                                                     0.13
gemma-2-2b_de-hr                                                  0.08
gemma-2-2b_pl-hr                                                  0.08
gemma-2-2b_de-pl-hr                                               0.09
gemma-2-2b_de-hr-cs                                               0.06
gemma-2-2b_pl-hr-cs                                               0.06
gemma-2-2b_pl-hr-hu-cs                                            0.05
xlm-roberta-base_hr-hu-cs                                         0.02
gemma-2-2b_cs                                                     0.11
gemma-2-2b_de-cs                                                  0.12
gemma-2-2b_de-hr-hu-cs                                            0.05
gemma-2-2b_de-hr-hu                                               0.07
gemma-2-2b_de-hu                                                  0.19
gemma-2-2b_de-pl-hr-cs                                            0.02
gemma-2-2b_de-pl-hr-hu-cs                                         0.06
gemma-2-2b_de-pl-hr-hu                                            0.06
gemma-2-2b_de-pl-hu-cs                                            0.11
gemma-2-2b_hr-cs                                                  0.07
gemma-2-2b_hr-hu-cs                                               0.06
gemma-2-2b_hr-hu                                                  0.06
gemma-2-2b_hu-cs                                                  0.08
gemma-2-2b_hu                                                     0.14
gemma-2-2b_pl-hr-hu                                               0.05
gemma-2-2b_pl-hu                                                  0.10
Llama-3.2-3B_de-cs                                                0.10
Llama-3.2-3B_de-hr-cs                                             0.04
Llama-3.2-3B_de-hu-cs                                             0.08
Llama-3.2-3B_de-pl-cs                                             0.04
Llama-3.2-3B_de-pl-hr-hu-cs                                       0.04
Llama-3.2-3B_hu-cs                                                0.04
Llama-3.2-3B_pl-cs                                                0.02
Llama-3.2-3B_pl-hu-cs                                             0.07
mdeberta-v3-base_de-cs                                            0.11
mdeberta-v3-base_de-hr-cs                                         0.04
mdeberta-v3-base_de-pl-cs                                         0.11
mdeberta-v3-base_de-pl-hr-hu-cs                                   0.04
mdeberta-v3-base_hr-hu-cs                                         0.01
mdeberta-v3-base_pl-hr-cs                                         0.04
xlm-roberta-base_de-hr-cs                                         0.04
xlm-roberta-base_de-pl-cs                                         0.10
xlm-roberta-base_de-pl-hr-hu-cs                                   0.01
xlm-roberta-base_pl-hr-cs                                         0.01
Name: length, dtype: float64

In [18]:
#AUC ROC of only best of each finetuned model version
temp = results_all.pivot_table('AUC ROC', 'Detector', "Dataset").sort_index(axis='columns')
temp = temp.sort_values(by='ALL_DATA', ascending=False)
temp['temp'] = [x.split('_')[0] for x in temp.index]
temp['Category'] = ['S' if x in statistical else 'P' if x in pretrained else 'F' for x in temp['temp']]
temp = temp.drop_duplicates(subset='temp').drop(columns='temp')
temp = temp.reset_index()
temp['Detector'] = temp['Detector'].apply(rename_detector)
#temp = temp.set_index('Detector')
temp = temp[[temp.columns[-1]] + list(temp.columns[:-1])]
display(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', subset=[x for x in temp.columns if x not in ['Category', 'Detector']], axis=0).apply(highlight_categories, axis=1)) #.hide('Category', axis=1)
print(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', subset=[x for x in temp.columns if x not in ['Category', 'Detector']],axis=0).applymap_index(lambda v: "font-weight: bold;", axis=0).applymap_index(lambda v: "font-weight: bold;", axis=1).hide().background_gradient(vmin=0.5, vmax=1.5, text_color_threshold=0, axis=None).to_latex(convert_css=True))

\begin{tabular}{llrrrrrrrr}
\bfseries Category & \bfseries Detector & \bfseries ALL_DATA & \bfseries cs & \bfseries de & \bfseries hr & \bfseries hu & \bfseries pl & \bfseries sk & sl \\
F & Llama-3.2-3B (de-pl-hu) & \bfseries {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9758 & \bfseries {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9886 & \bfseries {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9739 & \bfseries {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9829 & \bfseries {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9851 & \bfseries {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9765 & \bfseries {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9779 & \bfseries {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9638 \\
F & mDeBERTa-v3-base (de-pl-hr-cs) & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9739 & {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9835 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9731 & {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9789 & {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9821 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9727 & {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9693 & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9624 \\
F & Gemma-2-2B (de-pl-cs) & {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9660 & {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9837 & {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9697 & {\cellcolor[HTML]{86B0D3}} \color[HTML]{000000} 0.9546 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9750 & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9620 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9765 & {\cellcolor[HTML]{8BB2D4}} \color[HTML]{000000} 0.9434 \\
F & XLM-RoBERTa-base (de-pl-hr-hu-cs) & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9621 & {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9778 & {\cellcolor[HTML]{89B1D4}} \color[HTML]{000000} 0.9484 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9744 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9748 & {\cellcolor[HTML]{86B0D3}} \color[HTML]{000000} 0.9541 & {\cellcolor[HTML]{84B0D3}} \color[HTML]{000000} 0.9606 & {\cellcolor[HTML]{88B1D4}} \color[HTML]{000000} 0.9497 \\
S & Fast-DetectGPT & {\cellcolor[HTML]{C2CBE2}} \color[HTML]{000000} 0.7904 & {\cellcolor[HTML]{C1CAE2}} \color[HTML]{000000} 0.7943 & {\cellcolor[HTML]{BDC8E1}} \color[HTML]{000000} 0.8074 & {\cellcolor[HTML]{B8C6E0}} \color[HTML]{000000} 0.8228 & {\cellcolor[HTML]{CDD0E5}} \color[HTML]{000000} 0.7587 & {\cellcolor[HTML]{C5CCE3}} \color[HTML]{000000} 0.7830 & {\cellcolor[HTML]{C5CCE3}} \color[HTML]{000000} 0.7829 & {\cellcolor[HTML]{BBC7E0}} \color[HTML]{000000} 0.8133 \\
S & Binoculars & {\cellcolor[HTML]{CACEE5}} \color[HTML]{000000} 0.7675 & {\cellcolor[HTML]{C6CCE3}} \color[HTML]{000000} 0.7811 & {\cellcolor[HTML]{C2CBE2}} \color[HTML]{000000} 0.7924 & {\cellcolor[HTML]{C0C9E2}} \color[HTML]{000000} 0.8000 & {\cellcolor[HTML]{D0D1E6}} \color[HTML]{000000} 0.7517 & {\cellcolor[HTML]{CACEE5}} \color[HTML]{000000} 0.7681 & {\cellcolor[HTML]{D1D2E6}} \color[HTML]{000000} 0.7496 & {\cellcolor[HTML]{CCCFE5}} \color[HTML]{000000} 0.7650 \\
S & LLM-Deviation & {\cellcolor[HTML]{DEDCEC}} \color[HTML]{000000} 0.6887 & {\cellcolor[HTML]{CED0E6}} \color[HTML]{000000} 0.7543 & {\cellcolor[HTML]{E3E0EE}} \color[HTML]{000000} 0.6666 & {\cellcolor[HTML]{D6D6E9}} \color[HTML]{000000} 0.7258 & {\cellcolor[HTML]{DFDDEC}} \color[HTML]{000000} 0.6855 & {\cellcolor[HTML]{DCDAEB}} \color[HTML]{000000} 0.6991 & {\cellcolor[HTML]{D9D8EA}} \color[HTML]{000000} 0.7141 & {\cellcolor[HTML]{D4D4E8}} \color[HTML]{000000} 0.7337 \\
P & BLOOMZ-3B-mixed-detector & {\cellcolor[HTML]{E1DFED}} \color[HTML]{000000} 0.6740 & {\cellcolor[HTML]{E0DEED}} \color[HTML]{000000} 0.6769 & {\cellcolor[HTML]{DDDBEC}} \color[HTML]{000000} 0.6945 & {\cellcolor[HTML]{E2DFEE}} \color[HTML]{000000} 0.6690 & {\cellcolor[HTML]{E0DDED}} \color[HTML]{000000} 0.6836 & {\cellcolor[HTML]{E1DFED}} \color[HTML]{000000} 0.6752 & {\cellcolor[HTML]{D5D5E8}} \color[HTML]{000000} 0.7292 & {\cellcolor[HTML]{F0EAF4}} \color[HTML]{000000} 0.5997 \\
P & ChatGPT-detector-RoBERTa-Chinese & {\cellcolor[HTML]{E7E3F0}} \color[HTML]{000000} 0.6492 & {\cellcolor[HTML]{F0EAF4}} \color[HTML]{000000} 0.6045 & {\cellcolor[HTML]{DAD9EA}} \color[HTML]{000000} 0.7055 & {\cellcolor[HTML]{E8E4F0}} \color[HTML]{000000} 0.6442 & {\cellcolor[HTML]{D6D6E9}} \color[HTML]{000000} 0.7238 & {\cellcolor[HTML]{EAE6F1}} \color[HTML]{000000} 0.6361 & {\cellcolor[HTML]{DEDCEC}} \color[HTML]{000000} 0.6885 & {\cellcolor[HTML]{E4E1EF}} \color[HTML]{000000} 0.6629 \\
P & Detection-Longformer & {\cellcolor[HTML]{F5EFF6}} \color[HTML]{000000} 0.5629 & {\cellcolor[HTML]{F5EEF6}} \color[HTML]{000000} 0.5687 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4860 & {\cellcolor[HTML]{E7E3F0}} \color[HTML]{000000} 0.6519 & {\cellcolor[HTML]{EBE6F2}} \color[HTML]{000000} 0.6319 & {\cellcolor[HTML]{F1EBF5}} \color[HTML]{000000} 0.5900 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4636 & {\cellcolor[HTML]{F5EFF6}} \color[HTML]{000000} 0.5654 \\
\end{tabular}

C:\Users\User\AppData\Local\Temp\ipykernel_16088\2770399120.py:12: FutureWarning: Styler.applymap_index has been deprecated. Use Styler.map_index instead.
  print(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', subset=[x for x in temp.columns if x not in ['Category', 'Detector']],axis=0).applymap_index(lambda v: "font-weight: bold;", axis=0).applymap_index(lambda v: "font-weight: bold;", axis=1).hide().background_gradient(vmin=0.5, vmax=1.5, text_color_threshold=0, axis=None).to_latex(convert_css=True))

In [ ]:
#TPR @ 5% FPR of only best of each finetuned model version
temp = results_all.pivot_table('TPR @ 5% FPR', 'Detector', "Dataset").sort_index(axis='columns')
temp = temp.sort_values(by='ALL_DATA', ascending=False)
temp['temp'] = [x.split('_')[0] for x in temp.index]
temp['Category'] = ['S' if x in statistical else 'P' if x in pretrained else 'F' for x in temp['temp']]
temp = temp.drop_duplicates(subset='temp').drop(columns='temp')
temp = temp.reset_index()
temp['Detector'] = temp['Detector'].apply(rename_detector)
#temp = temp.set_index('Detector')
temp = temp[[temp.columns[-1]] + list(temp.columns[:-1])]
display(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', subset=[x for x in temp.columns if x not in ['Category', 'Detector']], axis=0).apply(highlight_categories, axis=1)) #.hide('Category', axis=1)
print(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', subset=[x for x in temp.columns if x not in ['Category', 'Detector']],axis=0).applymap_index(lambda v: "font-weight: bold;", axis=0).applymap_index(lambda v: "font-weight: bold;", axis=1).hide().background_gradient(vmin=0.5, vmax=1.5, text_color_threshold=0, axis=None).to_latex(convert_css=True))

In [24]:
#mean AUC ROC of language combinations of finetuned detectors
temp = results_all[results_all['Detector'].str.contains('_')].pivot_table('AUC ROC', 'Detector', "Dataset").sort_index(axis='columns')
temp = temp.sort_values(by='ALL_DATA', ascending=False)
temp['temp'] = ['-'.join(sorted(x.split('_')[1].split('-'))) for x in temp.index]
temp = temp.groupby('temp').agg(['mean', 'std']).sort_values(by=('ALL_DATA', 'mean'), ascending=False)
display(temp.style.format(precision=3).highlight_max(props='font-weight: bold;', axis=0)) #.background_gradient(vmin=0.5, vmax=1.5, text_color_threshold=0, axis=None)
print(temp.style.format(precision=3).highlight_max(props='font-weight: bold;', axis=0).to_latex(convert_css=True))

\begin{tabular}{lrrrrrrrrrrrrrrrr}
Dataset & \multicolumn{2}{r}{ALL_DATA} & \multicolumn{2}{r}{cs} & \multicolumn{2}{r}{de} & \multicolumn{2}{r}{hr} & \multicolumn{2}{r}{hu} & \multicolumn{2}{r}{pl} & \multicolumn{2}{r}{sk} & \multicolumn{2}{r}{sl} \\
 & mean & std & mean & std & mean & std & mean & std & mean & std & mean & std & mean & std & mean & std \\
temp &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
cs-de-hr-hu-pl & \bfseries 0.967 & 0.005 & 0.982 & 0.003 & 0.963 & 0.010 & 0.975 & 0.002 & 0.979 & 0.004 & 0.962 & 0.007 & 0.969 & 0.005 & 0.941 & 0.016 \\
de-hu-pl & 0.966 & 0.009 & \bfseries 0.982 & 0.007 & 0.967 & 0.011 & 0.965 & 0.012 & 0.980 & 0.005 & 0.966 & 0.010 & 0.969 & 0.011 & \bfseries 0.953 & 0.014 \\
de-pl & 0.966 & 0.008 & 0.981 & 0.006 & 0.969 & 0.009 & 0.965 & 0.012 & 0.974 & 0.011 & 0.967 & 0.006 & 0.967 & 0.011 & 0.951 & 0.010 \\
cs-de & 0.966 & 0.004 & 0.980 & 0.002 & \bfseries 0.972 & 0.007 & 0.963 & 0.012 & 0.973 & 0.008 & 0.951 & 0.007 & \bfseries 0.973 & 0.006 & 0.951 & 0.004 \\
cs-de-pl & 0.966 & 0.006 & 0.981 & 0.005 & 0.966 & 0.009 & 0.961 & 0.014 & 0.975 & 0.009 & 0.962 & 0.007 & 0.971 & 0.008 & 0.948 & 0.009 \\
cs-de-hr-pl & 0.965 & 0.008 & 0.981 & 0.004 & 0.965 & 0.010 & 0.974 & 0.005 & 0.973 & 0.007 & 0.962 & 0.008 & 0.966 & 0.010 & 0.945 & 0.017 \\
cs-hr-pl & 0.962 & 0.007 & 0.982 & 0.004 & 0.948 & 0.016 & 0.975 & 0.003 & 0.977 & 0.004 & 0.966 & 0.005 & 0.965 & 0.011 & 0.935 & 0.015 \\
cs-de-hu-pl & 0.962 & 0.008 & 0.980 & 0.008 & 0.964 & 0.011 & 0.957 & 0.021 & 0.973 & 0.005 & 0.959 & 0.009 & 0.966 & 0.013 & 0.945 & 0.014 \\
de-hr-pl & 0.962 & 0.004 & 0.980 & 0.005 & 0.963 & 0.010 & 0.973 & 0.008 & 0.974 & 0.006 & 0.959 & 0.009 & 0.972 & 0.004 & 0.932 & 0.012 \\
cs-de-hr-hu & 0.961 & 0.006 & 0.978 & 0.003 & 0.964 & 0.012 & 0.975 & 0.005 & 0.978 & 0.003 & 0.950 & 0.008 & 0.961 & 0.007 & 0.929 & 0.016 \\
cs-hu-pl & 0.961 & 0.009 & 0.981 & 0.006 & 0.946 & 0.013 & 0.968 & 0.009 & 0.981 & 0.004 & 0.964 & 0.008 & 0.963 & 0.016 & 0.941 & 0.012 \\
de-hr-hu-pl & 0.961 & 0.009 & 0.977 & 0.005 & 0.962 & 0.014 & 0.971 & 0.005 & 0.974 & 0.009 & 0.959 & 0.009 & 0.965 & 0.007 & 0.929 & 0.023 \\
cs-de-hr & 0.961 & 0.004 & 0.980 & 0.005 & 0.965 & 0.008 & 0.972 & 0.004 & 0.976 & 0.003 & 0.948 & 0.011 & 0.967 & 0.008 & 0.923 & 0.006 \\
cs-hr-hu-pl & 0.960 & 0.005 & 0.981 & 0.004 & 0.944 & 0.018 & 0.971 & 0.003 & 0.980 & 0.003 & 0.961 & 0.007 & 0.957 & 0.006 & 0.927 & 0.016 \\
de-hr-hu & 0.959 & 0.007 & 0.975 & 0.008 & 0.964 & 0.011 & 0.973 & 0.005 & 0.978 & 0.002 & 0.951 & 0.005 & 0.957 & 0.009 & 0.922 & 0.018 \\
de-hu & 0.959 & 0.014 & 0.979 & 0.004 & 0.969 & 0.008 & 0.953 & 0.025 & 0.981 & 0.006 & 0.949 & 0.011 & 0.959 & 0.013 & 0.947 & 0.014 \\
cs-de-hu & 0.959 & 0.008 & 0.975 & 0.008 & 0.968 & 0.010 & 0.958 & 0.005 & 0.976 & 0.005 & 0.944 & 0.008 & 0.960 & 0.012 & 0.938 & 0.016 \\
hu-pl & 0.958 & 0.008 & 0.980 & 0.003 & 0.943 & 0.009 & 0.963 & 0.010 & \bfseries 0.982 & 0.005 & 0.963 & 0.003 & 0.959 & 0.012 & 0.940 & 0.014 \\
de-hr & 0.957 & 0.009 & 0.977 & 0.007 & 0.967 & 0.008 & \bfseries 0.977 & 0.005 & 0.973 & 0.004 & 0.950 & 0.008 & 0.965 & 0.009 & 0.910 & 0.025 \\
hr-hu-pl & 0.956 & 0.007 & 0.977 & 0.005 & 0.947 & 0.012 & 0.969 & 0.006 & 0.979 & 0.005 & 0.964 & 0.006 & 0.952 & 0.009 & 0.912 & 0.028 \\
cs-hr-hu & 0.956 & 0.016 & 0.977 & 0.008 & 0.942 & 0.031 & 0.970 & 0.008 & 0.978 & 0.008 & 0.946 & 0.024 & 0.955 & 0.017 & 0.924 & 0.029 \\
hr-pl & 0.955 & 0.011 & 0.978 & 0.005 & 0.941 & 0.022 & 0.976 & 0.004 & 0.974 & 0.006 & 0.966 & 0.006 & 0.957 & 0.012 & 0.919 & 0.034 \\
cs-pl & 0.955 & 0.017 & 0.977 & 0.012 & 0.941 & 0.024 & 0.961 & 0.014 & 0.973 & 0.013 & 0.960 & 0.017 & 0.960 & 0.022 & 0.935 & 0.027 \\
pl & 0.954 & 0.021 & 0.977 & \bfseries 0.015 & 0.925 & \bfseries 0.051 & 0.965 & 0.014 & 0.970 & 0.016 & \bfseries 0.968 & 0.003 & 0.958 & \bfseries 0.028 & 0.945 & 0.017 \\
cs & 0.954 & 0.015 & 0.976 & 0.002 & 0.941 & 0.022 & 0.958 & 0.018 & 0.971 & 0.010 & 0.946 & 0.015 & 0.960 & 0.016 & 0.941 & 0.015 \\
cs-hu & 0.953 & 0.010 & 0.976 & 0.004 & 0.937 & 0.032 & 0.961 & 0.012 & 0.978 & 0.005 & 0.942 & 0.007 & 0.957 & 0.009 & 0.922 & 0.014 \\
cs-hr & 0.948 & 0.014 & 0.975 & 0.005 & 0.937 & 0.034 & 0.967 & 0.004 & 0.974 & 0.008 & 0.944 & 0.014 & 0.954 & 0.020 & 0.902 & 0.032 \\
hr-hu & 0.947 & 0.020 & 0.972 & 0.010 & 0.937 & 0.030 & 0.970 & 0.007 & 0.981 & 0.005 & 0.941 & 0.017 & 0.945 & 0.026 & 0.905 & 0.042 \\
de & 0.946 & 0.022 & 0.968 & 0.011 & 0.970 & 0.007 & 0.933 & 0.033 & 0.961 & 0.019 & 0.932 & 0.020 & 0.959 & 0.014 & 0.934 & 0.024 \\
hu & 0.934 & \bfseries 0.030 & 0.968 & 0.013 & 0.927 & 0.038 & 0.941 & \bfseries 0.037 & 0.980 & 0.006 & 0.929 & \bfseries 0.028 & 0.934 & 0.016 & 0.910 & 0.027 \\
hr & 0.933 & 0.023 & 0.971 & 0.010 & 0.923 & 0.037 & 0.971 & 0.007 & 0.965 & \bfseries 0.020 & 0.936 & 0.017 & 0.942 & 0.023 & 0.859 & \bfseries 0.058 \\
\end{tabular}

In [20]:
#mean TPR @ 5% FPR of language combinations of finetuned detectors
temp = results_all[results_all['Detector'].str.contains('_')].pivot_table('TPR @ 5% FPR', 'Detector', "Dataset").sort_index(axis='columns')
temp = temp.sort_values(by='ALL_DATA', ascending=False)
temp['temp'] = ['-'.join(sorted(x.split('_')[1].split('-'))) for x in temp.index]
temp = temp.groupby('temp').agg(['mean', 'std']).sort_values(by=('ALL_DATA', 'mean'), ascending=False)
display(temp.style.format(precision=3).highlight_max(props='font-weight: bold;', axis=0)) #.background_gradient(vmin=0.5, vmax=1.5, text_color_threshold=0, axis=None)
print(temp.style.format(precision=3).highlight_max(props='font-weight: bold;', axis=0).to_latex(convert_css=True))

\begin{tabular}{lrrrrrrrrrrrrrrrr}
Dataset & \multicolumn{2}{r}{ALL_DATA} & \multicolumn{2}{r}{cs} & \multicolumn{2}{r}{de} & \multicolumn{2}{r}{hr} & \multicolumn{2}{r}{hu} & \multicolumn{2}{r}{pl} & \multicolumn{2}{r}{sk} & \multicolumn{2}{r}{sl} \\
 & mean & std & mean & std & mean & std & mean & std & mean & std & mean & std & mean & std & mean & std \\
temp &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
cs-de-hr-hu-pl & \bfseries 0.849 & 0.036 & 0.936 & 0.019 & 0.844 & 0.080 & 0.893 & 0.020 & 0.922 & 0.038 & 0.825 & 0.054 & 0.863 & 0.041 & 0.275 & 0.337 \\
de-pl & 0.844 & 0.033 & 0.916 & 0.023 & 0.863 & 0.045 & 0.850 & 0.065 & 0.901 & 0.050 & 0.849 & 0.062 & 0.845 & 0.056 & 0.731 & 0.033 \\
cs-de & 0.840 & 0.037 & 0.937 & 0.019 & \bfseries 0.879 & 0.039 & 0.855 & 0.051 & 0.893 & 0.047 & 0.762 & 0.086 & 0.855 & 0.045 & \bfseries 0.750 & 0.067 \\
cs-de-pl & 0.837 & 0.037 & 0.932 & 0.021 & 0.843 & 0.056 & 0.820 & 0.086 & 0.909 & 0.032 & 0.837 & 0.057 & 0.858 & 0.052 & 0.626 & 0.258 \\
de-hu-pl & 0.833 & 0.046 & 0.920 & 0.039 & 0.840 & 0.066 & 0.846 & 0.059 & 0.929 & 0.044 & 0.829 & 0.074 & 0.849 & 0.039 & 0.746 & 0.074 \\
cs-de-hr-pl & 0.832 & 0.033 & 0.928 & 0.018 & 0.850 & 0.043 & 0.886 & 0.027 & 0.865 & 0.039 & 0.817 & 0.051 & 0.821 & 0.057 & 0.528 & 0.356 \\
de-hr-pl & 0.822 & 0.045 & 0.928 & 0.028 & 0.838 & 0.047 & 0.889 & 0.049 & 0.897 & 0.031 & 0.804 & 0.095 & \bfseries 0.886 & 0.029 & 0.351 & 0.405 \\
cs-hu-pl & 0.813 & 0.061 & \bfseries 0.941 & 0.033 & 0.572 & 0.387 & 0.868 & 0.038 & \bfseries 0.951 & 0.020 & 0.845 & 0.061 & 0.820 & 0.101 & 0.650 & 0.100 \\
de-hu & 0.810 & 0.046 & 0.922 & 0.017 & 0.868 & 0.040 & 0.815 & 0.071 & 0.942 & 0.021 & 0.736 & 0.053 & 0.832 & 0.022 & 0.699 & 0.032 \\
cs-de-hr & 0.802 & 0.060 & 0.933 & 0.030 & 0.851 & 0.037 & 0.877 & 0.033 & 0.899 & 0.021 & 0.575 & 0.383 & 0.824 & 0.061 & 0.002 & 0.003 \\
cs-hr-pl & 0.801 & 0.045 & 0.934 & 0.031 & 0.521 & 0.369 & 0.890 & 0.014 & 0.906 & 0.035 & 0.837 & 0.054 & 0.821 & 0.061 & 0.336 & 0.394 \\
cs-de-hu-pl & 0.797 & 0.067 & 0.915 & 0.046 & 0.841 & 0.077 & 0.674 & 0.367 & 0.905 & 0.046 & 0.812 & 0.059 & 0.826 & 0.081 & 0.569 & 0.304 \\
hu-pl & 0.793 & 0.047 & 0.926 & 0.038 & 0.308 & 0.360 & 0.822 & 0.061 & 0.950 & 0.020 & 0.599 & 0.403 & 0.785 & 0.072 & 0.466 & 0.313 \\
cs-de-hu & 0.783 & 0.061 & 0.897 & 0.094 & 0.852 & 0.073 & 0.770 & 0.109 & 0.923 & 0.038 & 0.477 & 0.380 & 0.596 & 0.402 & 0.397 & 0.330 \\
cs-hr-hu & 0.782 & 0.104 & 0.916 & 0.068 & 0.742 & 0.162 & 0.867 & 0.046 & 0.926 & 0.070 & 0.689 & 0.149 & 0.785 & 0.098 & 0.263 & 0.307 \\
cs & 0.779 & 0.054 & 0.928 & 0.011 & 0.595 & 0.397 & 0.810 & 0.077 & 0.877 & 0.075 & 0.403 & \bfseries 0.466 & 0.631 & 0.422 & 0.679 & 0.056 \\
de & 0.776 & 0.074 & 0.879 & 0.044 & 0.875 & 0.034 & 0.767 & 0.102 & 0.816 & 0.129 & 0.719 & 0.058 & 0.825 & 0.064 & 0.709 & 0.063 \\
pl & 0.772 & 0.119 & 0.907 & 0.084 & 0.427 & \bfseries 0.493 & 0.849 & 0.062 & 0.895 & 0.068 & \bfseries 0.858 & 0.038 & 0.820 & 0.127 & 0.710 & 0.083 \\
cs-de-hr-hu & 0.769 & 0.097 & 0.927 & 0.030 & 0.860 & 0.060 & \bfseries 0.903 & 0.025 & 0.935 & 0.031 & 0.751 & 0.082 & 0.570 & 0.405 & 0.171 & 0.341 \\
cs-pl & 0.740 & 0.133 & 0.900 & \bfseries 0.107 & 0.380 & 0.443 & 0.799 & 0.088 & 0.876 & 0.073 & 0.810 & 0.118 & 0.799 & 0.116 & 0.512 & 0.341 \\
cs-hu & 0.686 & 0.194 & 0.913 & 0.042 & 0.644 & 0.225 & 0.828 & 0.038 & 0.932 & 0.030 & 0.662 & 0.139 & 0.673 & 0.206 & 0.514 & 0.120 \\
hu & 0.664 & 0.113 & 0.855 & 0.082 & 0.649 & 0.165 & 0.745 & 0.120 & 0.933 & 0.046 & 0.654 & 0.189 & 0.690 & 0.090 & 0.582 & 0.143 \\
de-hr-hu-pl & 0.628 & 0.422 & 0.927 & 0.029 & 0.851 & 0.065 & 0.891 & 0.016 & 0.689 & \bfseries 0.460 & 0.618 & 0.420 & 0.627 & 0.419 & 0.189 & 0.378 \\
hr-hu & 0.599 & 0.401 & 0.906 & 0.057 & 0.575 & 0.384 & 0.865 & 0.039 & 0.934 & 0.021 & 0.476 & 0.356 & 0.411 & \bfseries 0.475 & 0.206 & \bfseries 0.412 \\
cs-hr-hu-pl & 0.596 & 0.400 & 0.937 & 0.024 & 0.535 & 0.374 & 0.877 & 0.023 & 0.946 & 0.030 & 0.817 & 0.057 & 0.573 & 0.385 & 0.171 & 0.341 \\
hr-hu-pl & 0.594 & 0.398 & 0.931 & 0.039 & 0.349 & 0.410 & 0.643 & \bfseries 0.430 & 0.944 & 0.022 & 0.825 & 0.075 & 0.567 & 0.392 & 0.172 & 0.339 \\
de-hr & 0.594 & 0.400 & 0.918 & 0.028 & 0.875 & 0.042 & 0.902 & 0.007 & 0.900 & 0.040 & 0.628 & 0.264 & 0.840 & 0.035 & 0.072 & 0.145 \\
de-hr-hu & 0.555 & 0.383 & 0.899 & 0.059 & 0.822 & 0.087 & 0.877 & 0.029 & 0.936 & 0.015 & 0.731 & 0.075 & 0.567 & 0.406 & 0.162 & 0.324 \\
hr-pl & 0.391 & \bfseries 0.454 & 0.931 & 0.033 & 0.550 & 0.377 & 0.901 & 0.019 & 0.910 & 0.029 & 0.834 & 0.077 & 0.782 & 0.116 & 0.192 & 0.383 \\
hr & 0.345 & 0.403 & 0.893 & 0.055 & 0.535 & 0.366 & 0.877 & 0.044 & 0.843 & 0.100 & 0.438 & 0.347 & 0.446 & 0.442 & 0.068 & 0.135 \\
cs-hr & 0.168 & 0.335 & 0.914 & 0.039 & 0.372 & 0.442 & 0.854 & 0.040 & 0.885 & 0.050 & 0.399 & 0.462 & 0.589 & 0.404 & 0.186 & 0.372 \\
\end{tabular}

In [103]:
#mean AUC ROC of finetuned base models
temp = results_all[results_all['Detector'].str.contains('_')].pivot_table('AUC ROC', 'Detector', "Dataset").sort_index(axis='columns')
temp = temp.sort_values(by='ALL_DATA', ascending=False)
temp['temp'] = [x.split('_')[0] for x in temp.index]
temp = temp.groupby('temp').mean().sort_values(by='ALL_DATA', ascending=False)
display(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0))
print(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).to_latex(convert_css=True))

\begin{tabular}{lrrrrrrrr}
Dataset & ALL_DATA & cs & de & hr & hu & pl & sk & sl \\
temp &  &  &  &  &  &  &  &  \\
mdeberta-v3-base & \bfseries 0.9661 & \bfseries 0.9821 & 0.9609 & 0.9707 & \bfseries 0.9812 & 0.9574 & 0.9639 & \bfseries 0.9487 \\
Llama-3.2-3B & 0.9625 & 0.9805 & \bfseries 0.9611 & \bfseries 0.9727 & 0.9800 & \bfseries 0.9627 & \bfseries 0.9671 & 0.9224 \\
gemma-2-2b & 0.9486 & 0.9801 & 0.9445 & 0.9551 & 0.9718 & 0.9538 & 0.9652 & 0.9114 \\
xlm-roberta-base & 0.9457 & 0.9707 & 0.9214 & 0.9634 & 0.9712 & 0.9422 & 0.9434 & 0.9161 \\
\end{tabular}

In [21]:
#mean TPR @ 5% FPR of finetuned base models
temp = results_all[results_all['Detector'].str.contains('_')].pivot_table('TPR @ 5% FPR', 'Detector', "Dataset").sort_index(axis='columns')
temp = temp.sort_values(by='ALL_DATA', ascending=False)
temp['temp'] = [x.split('_')[0] for x in temp.index]
temp = temp.groupby('temp').mean().sort_values(by='ALL_DATA', ascending=False)
display(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0))
print(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).to_latex(convert_css=True))

\begin{tabular}{lrrrrrrrr}
Dataset & ALL_DATA & cs & de & hr & hu & pl & sk & sl \\
temp &  &  &  &  &  &  &  &  \\
mdeberta-v3-base & \bfseries 0.7816 & 0.9286 & 0.7879 & 0.8163 & \bfseries 0.9276 & 0.6664 & 0.7392 & \bfseries 0.5750 \\
gemma-2-2b & 0.7432 & 0.9381 & 0.6021 & 0.8427 & 0.9148 & \bfseries 0.8033 & \bfseries 0.8279 & 0.3256 \\
xlm-roberta-base & 0.6635 & 0.8605 & 0.5652 & 0.8230 & 0.8585 & 0.5843 & 0.6014 & 0.3865 \\
Llama-3.2-3B & 0.6366 & \bfseries 0.9442 & \bfseries 0.8065 & \bfseries 0.8740 & 0.9079 & 0.7737 & 0.7571 & 0.3492 \\
\end{tabular}

In [71]:
#generators
results_all = pd.DataFrame()
for dataset in [to_auc_dict_generator(df, True)]:
 for detector in tqdm(selected):
  temp = pd.DataFrame({'Dataset': "ALL_DATA", 'Detector': detector, 'Generator': '{all}', 'AUC ROC': dataset[detector]['auc'], 'TPR @ 5% FPR': dataset[detector]['tpr_5%fpr'], 'Th @ 5% FPR': dataset[detector]['th_5%fpr'], 'Th @ max(TPR-FPR)': dataset[detector]['th_optim']}, index=[0])
  results_all = pd.concat([results_all, temp])
  for generator,val in dataset[detector].items():
    if (generator == 'auc') or ('_' in generator): continue
    temp = pd.DataFrame({'Dataset': generator, 'Detector': detector, 'Generator': generator, 'AUC ROC': dataset[detector][generator]['auc'], 'TPR @ 5% FPR': val['tpr_5%fpr']}, index=[0])
    results_all = pd.concat([results_all, temp])
results_all = results_all[results_all['Detector'].isin(selected)]
#only best of each finetuned model version
temp = results_all.pivot_table(['AUC ROC', 'TPR @ 5% FPR'], 'Detector', "Dataset").reorder_levels(axis='columns', order=[1,0]).sort_index(axis='columns')#.sort_index(axis='index', ascending=False)
temp = temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False)
temp['temp'] = [x.split('_')[0] for x in temp.index]
temp = temp.drop_duplicates(subset=('temp','')).drop(columns='temp')
display(temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False).style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0))
print(temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False).style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).to_latex(convert_css=True))
#only worst of each finetuned model version
temp = results_all.pivot_table(['AUC ROC', 'TPR @ 5% FPR'], 'Detector', "Dataset").reorder_levels(axis='columns', order=[1,0]).sort_index(axis='columns')#.sort_index(axis='index', ascending=False)
temp = temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False)
temp['temp'] = [x.split('_')[0] for x in temp.index]
temp = temp.drop_duplicates(subset=('temp',''), keep='last').drop(columns='temp')
display(temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False).style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0))
print(temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False).style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).to_latex(convert_css=True))

Best FPR: xlm-roberta-base_hr-cs Llama-2-70b-chat-hf 0.07857142857142857
Best FPR: xlm-roberta-base_hr-cs Mistral-7B-Instruct-v0.2 0.07857142857142857
Best FPR: xlm-roberta-base_hr-cs aya-101 0.07857142857142857
Best FPR: xlm-roberta-base_hr-cs gpt-3.5-turbo-0125 0.07857142857142857
Best FPR: xlm-roberta-base_hr-cs opt-iml-max-30b 0.07857142857142857
Best FPR: xlm-roberta-base_hr-cs v5-Eagle-7B-HF 0.07857142857142857
Best FPR: xlm-roberta-base_hr-cs vicuna-13b 0.07857142857142857
Best FPR: xlm-roberta-base_hr-cs gemini 0.07857142857142857
Best FPR: xlm-roberta-base_hr Llama-2-70b-chat-hf 0.09785714285714285
Best FPR: xlm-roberta-base_hr Mistral-7B-Instruct-v0.2 0.09785714285714285
Best FPR: xlm-roberta-base_hr aya-101 0.09785714285714285
Best FPR: xlm-roberta-base_hr gpt-3.5-turbo-0125 0.09785714285714285
Best FPR: xlm-roberta-base_hr opt-iml-max-30b 0.09785714285714285
Best FPR: xlm-roberta-base_hr v5-Eagle-7B-HF 0.09785714285714285
Best FPR: xlm-roberta-base_hr vicuna-13b 0.09785714285714285
Best FPR: xlm-roberta-base_hr gemini 0.09785714285714285
Best FPR: xlm-roberta-base_hr-hu Llama-2-70b-chat-hf 0.07642857142857143
Best FPR: xlm-roberta-base_hr-hu Mistral-7B-Instruct-v0.2 0.07642857142857143
Best FPR: xlm-roberta-base_hr-hu aya-101 0.07642857142857143
Best FPR: xlm-roberta-base_hr-hu gpt-3.5-turbo-0125 0.07642857142857143
Best FPR: xlm-roberta-base_hr-hu opt-iml-max-30b 0.07642857142857143
Best FPR: xlm-roberta-base_hr-hu v5-Eagle-7B-HF 0.07642857142857143
Best FPR: xlm-roberta-base_hr-hu vicuna-13b 0.07642857142857143
Best FPR: xlm-roberta-base_hr-hu gemini 0.07642857142857143
Best FPR: Llama-3.2-3B_hr-cs Llama-2-70b-chat-hf 0.05142857142857143
Best FPR: Llama-3.2-3B_hr-cs Mistral-7B-Instruct-v0.2 0.05142857142857143
Best FPR: Llama-3.2-3B_hr-cs aya-101 0.05142857142857143
Best FPR: Llama-3.2-3B_hr-cs gpt-3.5-turbo-0125 0.05142857142857143
Best FPR: Llama-3.2-3B_hr-cs opt-iml-max-30b 0.05142857142857143
Best FPR: Llama-3.2-3B_hr-cs v5-Eagle-7B-HF 0.05142857142857143
Best FPR: Llama-3.2-3B_hr-cs vicuna-13b 0.05142857142857143
Best FPR: Llama-3.2-3B_hr-cs gemini 0.05142857142857143
Best FPR: Llama-3.2-3B_hr Llama-2-70b-chat-hf 0.06357142857142857
Best FPR: Llama-3.2-3B_hr Mistral-7B-Instruct-v0.2 0.06357142857142857
Best FPR: Llama-3.2-3B_hr aya-101 0.06357142857142857
Best FPR: Llama-3.2-3B_hr gpt-3.5-turbo-0125 0.06357142857142857
Best FPR: Llama-3.2-3B_hr opt-iml-max-30b 0.06357142857142857
Best FPR: Llama-3.2-3B_hr v5-Eagle-7B-HF 0.06357142857142857
Best FPR: Llama-3.2-3B_hr vicuna-13b 0.06357142857142857
Best FPR: Llama-3.2-3B_hr gemini 0.06357142857142857
Best FPR: Llama-3.2-3B_de-hr Llama-2-70b-chat-hf 0.0575
Best FPR: Llama-3.2-3B_de-hr Mistral-7B-Instruct-v0.2 0.0575
Best FPR: Llama-3.2-3B_de-hr aya-101 0.0575
Best FPR: Llama-3.2-3B_de-hr gpt-3.5-turbo-0125 0.0575
Best FPR: Llama-3.2-3B_de-hr opt-iml-max-30b 0.0575
Best FPR: Llama-3.2-3B_de-hr v5-Eagle-7B-HF 0.0575
Best FPR: Llama-3.2-3B_de-hr vicuna-13b 0.0575
Best FPR: Llama-3.2-3B_de-hr gemini 0.0575
Best FPR: Llama-3.2-3B_pl-hr Llama-2-70b-chat-hf 0.05857142857142857
Best FPR: Llama-3.2-3B_pl-hr Mistral-7B-Instruct-v0.2 0.05857142857142857
Best FPR: Llama-3.2-3B_pl-hr aya-101 0.05857142857142857
Best FPR: Llama-3.2-3B_pl-hr gpt-3.5-turbo-0125 0.05857142857142857
Best FPR: Llama-3.2-3B_pl-hr opt-iml-max-30b 0.05857142857142857
Best FPR: Llama-3.2-3B_pl-hr v5-Eagle-7B-HF 0.05857142857142857
Best FPR: Llama-3.2-3B_pl-hr vicuna-13b 0.05857142857142857
Best FPR: Llama-3.2-3B_pl-hr gemini 0.05857142857142857
Best FPR: Llama-3.2-3B_hr-hu-cs Llama-2-70b-chat-hf 0.05178571428571429
Best FPR: Llama-3.2-3B_hr-hu-cs Mistral-7B-Instruct-v0.2 0.05178571428571429
Best FPR: Llama-3.2-3B_hr-hu-cs aya-101 0.05178571428571429
Best FPR: Llama-3.2-3B_hr-hu-cs gpt-3.5-turbo-0125 0.05178571428571429
Best FPR: Llama-3.2-3B_hr-hu-cs opt-iml-max-30b 0.05178571428571429
Best FPR: Llama-3.2-3B_hr-hu-cs v5-Eagle-7B-HF 0.05178571428571429
Best FPR: Llama-3.2-3B_hr-hu-cs vicuna-13b 0.05178571428571429
Best FPR: Llama-3.2-3B_hr-hu-cs gemini 0.05178571428571429
Best FPR: Llama-3.2-3B_pl-hr-hu-cs Llama-2-70b-chat-hf 0.05357142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu-cs Mistral-7B-Instruct-v0.2 0.05357142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu-cs aya-101 0.05357142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu-cs gpt-3.5-turbo-0125 0.05357142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu-cs opt-iml-max-30b 0.05357142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu-cs v5-Eagle-7B-HF 0.05357142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu-cs vicuna-13b 0.05357142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu-cs gemini 0.05357142857142857
Best FPR: Llama-3.2-3B_de-pl-hr-hu Llama-2-70b-chat-hf 0.0625
Best FPR: Llama-3.2-3B_de-pl-hr-hu Mistral-7B-Instruct-v0.2 0.0625
Best FPR: Llama-3.2-3B_de-pl-hr-hu aya-101 0.0625
Best FPR: Llama-3.2-3B_de-pl-hr-hu gpt-3.5-turbo-0125 0.0625
Best FPR: Llama-3.2-3B_de-pl-hr-hu opt-iml-max-30b 0.0625
Best FPR: Llama-3.2-3B_de-pl-hr-hu v5-Eagle-7B-HF 0.0625
Best FPR: Llama-3.2-3B_de-pl-hr-hu vicuna-13b 0.0625
Best FPR: Llama-3.2-3B_de-pl-hr-hu gemini 0.0625
Best FPR: Llama-3.2-3B_de-hr-hu Llama-2-70b-chat-hf 0.0525
Best FPR: Llama-3.2-3B_de-hr-hu Mistral-7B-Instruct-v0.2 0.0525
Best FPR: Llama-3.2-3B_de-hr-hu aya-101 0.0525
Best FPR: Llama-3.2-3B_de-hr-hu gpt-3.5-turbo-0125 0.0525
Best FPR: Llama-3.2-3B_de-hr-hu opt-iml-max-30b 0.0525
Best FPR: Llama-3.2-3B_de-hr-hu v5-Eagle-7B-HF 0.0525
Best FPR: Llama-3.2-3B_de-hr-hu vicuna-13b 0.0525
Best FPR: Llama-3.2-3B_de-hr-hu gemini 0.0525
Best FPR: Llama-3.2-3B_pl-hr-hu Llama-2-70b-chat-hf 0.08107142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu Mistral-7B-Instruct-v0.2 0.08107142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu aya-101 0.08107142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu gpt-3.5-turbo-0125 0.08107142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu opt-iml-max-30b 0.08107142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu v5-Eagle-7B-HF 0.08107142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu vicuna-13b 0.08107142857142857
Best FPR: Llama-3.2-3B_pl-hr-hu gemini 0.08107142857142857
Best FPR: gemma-2-2b_pl-hr Llama-2-70b-chat-hf 0.055357142857142855
Best FPR: gemma-2-2b_pl-hr Mistral-7B-Instruct-v0.2 0.055357142857142855
Best FPR: gemma-2-2b_pl-hr aya-101 0.055357142857142855
Best FPR: gemma-2-2b_pl-hr gpt-3.5-turbo-0125 0.055357142857142855
Best FPR: gemma-2-2b_pl-hr opt-iml-max-30b 0.055357142857142855
Best FPR: gemma-2-2b_pl-hr v5-Eagle-7B-HF 0.055357142857142855
Best FPR: gemma-2-2b_pl-hr vicuna-13b 0.055357142857142855
Best FPR: gemma-2-2b_pl-hr gemini 0.055357142857142855
Best FPR: gemma-2-2b_hr-cs Llama-2-70b-chat-hf 0.052142857142857144
Best FPR: gemma-2-2b_hr-cs Mistral-7B-Instruct-v0.2 0.052142857142857144
Best FPR: gemma-2-2b_hr-cs aya-101 0.052142857142857144
Best FPR: gemma-2-2b_hr-cs gpt-3.5-turbo-0125 0.052142857142857144
Best FPR: gemma-2-2b_hr-cs opt-iml-max-30b 0.052142857142857144
Best FPR: gemma-2-2b_hr-cs v5-Eagle-7B-HF 0.052142857142857144
Best FPR: gemma-2-2b_hr-cs vicuna-13b 0.052142857142857144
Best FPR: gemma-2-2b_hr-cs gemini 0.052142857142857144

100%|██████████| 130/130 [00:01<00:00, 104.87it/s]

\begin{tabular}{lrrrrrrrrrrrrrrrrrr}
Dataset & \multicolumn{2}{r}{ALL_DATA} & \multicolumn{2}{r}{Llama-2-70b-chat-hf} & \multicolumn{2}{r}{Mistral-7B-Instruct-v0.2} & \multicolumn{2}{r}{aya-101} & \multicolumn{2}{r}{gemini} & \multicolumn{2}{r}{gpt-3.5-turbo-0125} & \multicolumn{2}{r}{opt-iml-max-30b} & \multicolumn{2}{r}{v5-Eagle-7B-HF} & \multicolumn{2}{r}{vicuna-13b} \\
 & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR \\
Detector &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
Llama-3.2-3B_de-pl-hu & \bfseries 0.9749 & \bfseries 0.8871 & 0.9904 & 0.9714 & 0.9688 & \bfseries 0.8371 & 0.9655 & \bfseries 0.8421 & \bfseries 0.9754 & \bfseries 0.8814 & \bfseries 0.9828 & \bfseries 0.9204 & \bfseries 0.9632 & \bfseries 0.8446 & 0.9822 & 0.9254 & 0.9789 & \bfseries 0.9136 \\
mdeberta-v3-base_de-pl-hr-hu-cs & 0.9734 & 0.8403 & \bfseries 0.9935 & \bfseries 0.9750 & \bfseries 0.9704 & 0.8039 & \bfseries 0.9662 & 0.7950 & 0.9706 & 0.8500 & 0.9797 & 0.8707 & 0.9505 & 0.6732 & \bfseries 0.9848 & \bfseries 0.9389 & \bfseries 0.9801 & 0.8879 \\
gemma-2-2b_de-pl-cs & 0.9627 & 0.8471 & 0.9777 & 0.9407 & 0.9555 & 0.8014 & 0.9612 & 0.8375 & 0.9585 & 0.8021 & 0.9717 & 0.8850 & 0.9452 & 0.7843 & 0.9722 & 0.8829 & 0.9653 & 0.8671 \\
xlm-roberta-base_de-pl-hr-hu-cs & 0.9613 & 0.7874 & 0.9821 & 0.9050 & 0.9430 & 0.6721 & 0.9526 & 0.7364 & 0.9626 & 0.7936 & 0.9745 & 0.8525 & 0.9403 & 0.6882 & 0.9732 & 0.8643 & 0.9732 & 0.8489 \\
fastdetectgpt & 0.7830 & 0.4074 & 0.9667 & 0.8371 & 0.6305 & 0.1675 & 0.8292 & 0.4686 & 0.7920 & 0.3793 & 0.7986 & 0.4004 & 0.6377 & 0.2164 & 0.8729 & 0.5211 & 0.8325 & 0.4700 \\
binoculars & 0.7603 & 0.3871 & 0.9555 & 0.7557 & 0.6211 & 0.1243 & 0.7955 & 0.4461 & 0.7889 & 0.3450 & 0.7756 & 0.3996 & 0.5985 & 0.2379 & 0.8518 & 0.4961 & 0.8075 & 0.4554 \\
llmdeviation & 0.6843 & 0.1839 & 0.8873 & 0.4671 & 0.6233 & 0.0571 & 0.6807 & 0.2168 & 0.6584 & 0.1221 & 0.6861 & 0.2314 & 0.5610 & 0.0875 & 0.7570 & 0.2211 & 0.7088 & 0.1789 \\
andreas122001-bloomz-3b-mixed-detector & 0.6730 & 0.1483 & 0.5410 & 0.0443 & 0.6302 & 0.0929 & 0.6655 & 0.2111 & 0.6271 & 0.1593 & 0.7694 & 0.1904 & 0.6697 & 0.1561 & 0.7000 & 0.1282 & 0.6923 & 0.1575 \\
Hello-SimpleAI-chatgpt-detector-roberta-chinese & 0.6423 & 0.1544 & 0.7949 & 0.2857 & 0.6784 & 0.2104 & 0.6090 & 0.1068 & 0.6906 & 0.1679 & 0.5882 & 0.1071 & 0.5667 & 0.0904 & 0.6403 & 0.1461 & 0.6711 & 0.1936 \\
nealcly-detection-longformer & 0.5615 & 0.0687 & 0.6601 & 0.1364 & 0.6045 & 0.0607 & 0.5209 & 0.0407 & 0.5045 & 0.0593 & 0.4613 & 0.0461 & 0.5453 & 0.1146 & 0.6283 & 0.0654 & 0.5879 & 0.0554 \\
\end{tabular}

\begin{tabular}{lrrrrrrrrrrrrrrrrrr}
Dataset & \multicolumn{2}{r}{ALL_DATA} & \multicolumn{2}{r}{Llama-2-70b-chat-hf} & \multicolumn{2}{r}{Mistral-7B-Instruct-v0.2} & \multicolumn{2}{r}{aya-101} & \multicolumn{2}{r}{gemini} & \multicolumn{2}{r}{gpt-3.5-turbo-0125} & \multicolumn{2}{r}{opt-iml-max-30b} & \multicolumn{2}{r}{v5-Eagle-7B-HF} & \multicolumn{2}{r}{vicuna-13b} \\
 & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR \\
Detector &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
mdeberta-v3-base_hr & \bfseries 0.9566 & \bfseries 0.7557 & \bfseries 0.9833 & \bfseries 0.9529 & \bfseries 0.9591 & \bfseries 0.7518 & \bfseries 0.9450 & \bfseries 0.6689 & \bfseries 0.9547 & \bfseries 0.7750 & \bfseries 0.9620 & \bfseries 0.7654 & \bfseries 0.9242 & 0.5429 & \bfseries 0.9728 & \bfseries 0.8943 & \bfseries 0.9642 & \bfseries 0.8029 \\
Llama-3.2-3B_hr & 0.9442 & 0.0000 & 0.9628 & 0.0000 & 0.9417 & 0.0000 & 0.9364 & 0.0000 & 0.9465 & 0.0000 & 0.9513 & 0.0000 & 0.9219 & 0.0000 & 0.9515 & 0.0000 & 0.9524 & 0.0000 \\
xlm-roberta-base_hr & 0.9069 & 0.0000 & 0.9402 & 0.0000 & 0.9000 & 0.0000 & 0.8631 & 0.0000 & 0.9196 & 0.0000 & 0.9227 & 0.0000 & 0.8808 & 0.0000 & 0.9216 & 0.0000 & 0.9305 & 0.0000 \\
gemma-2-2b_hu & 0.8954 & 0.5777 & 0.9297 & 0.6579 & 0.8505 & 0.4600 & 0.9107 & 0.6336 & 0.8511 & 0.4307 & 0.9235 & 0.6357 & 0.9003 & \bfseries 0.6007 & 0.8969 & 0.5775 & 0.8954 & 0.5918 \\
fastdetectgpt & 0.7830 & 0.4074 & 0.9667 & 0.8371 & 0.6305 & 0.1675 & 0.8292 & 0.4686 & 0.7920 & 0.3793 & 0.7986 & 0.4004 & 0.6377 & 0.2164 & 0.8729 & 0.5211 & 0.8325 & 0.4700 \\
binoculars & 0.7603 & 0.3871 & 0.9555 & 0.7557 & 0.6211 & 0.1243 & 0.7955 & 0.4461 & 0.7889 & 0.3450 & 0.7756 & 0.3996 & 0.5985 & 0.2379 & 0.8518 & 0.4961 & 0.8075 & 0.4554 \\
llmdeviation & 0.6843 & 0.1839 & 0.8873 & 0.4671 & 0.6233 & 0.0571 & 0.6807 & 0.2168 & 0.6584 & 0.1221 & 0.6861 & 0.2314 & 0.5610 & 0.0875 & 0.7570 & 0.2211 & 0.7088 & 0.1789 \\
andreas122001-bloomz-3b-mixed-detector & 0.6730 & 0.1483 & 0.5410 & 0.0443 & 0.6302 & 0.0929 & 0.6655 & 0.2111 & 0.6271 & 0.1593 & 0.7694 & 0.1904 & 0.6697 & 0.1561 & 0.7000 & 0.1282 & 0.6923 & 0.1575 \\
Hello-SimpleAI-chatgpt-detector-roberta-chinese & 0.6423 & 0.1544 & 0.7949 & 0.2857 & 0.6784 & 0.2104 & 0.6090 & 0.1068 & 0.6906 & 0.1679 & 0.5882 & 0.1071 & 0.5667 & 0.0904 & 0.6403 & 0.1461 & 0.6711 & 0.1936 \\
nealcly-detection-longformer & 0.5615 & 0.0687 & 0.6601 & 0.1364 & 0.6045 & 0.0607 & 0.5209 & 0.0407 & 0.5045 & 0.0593 & 0.4613 & 0.0461 & 0.5453 & 0.1146 & 0.6283 & 0.0654 & 0.5879 & 0.0554 \\
\end{tabular}

In [ ]:
temp['Category'] = ['S' if x in statistical else 'P' if x in pretrained else 'F' for x in temp['temp']]
temp = temp.drop_duplicates(subset='temp').drop(columns='temp')
temp = temp.reset_index()
temp['Detector'] = temp['Detector'].apply(rename_detector)
#temp = temp.set_index('Detector')
temp = temp[[temp.columns[-1]] + list(temp.columns[:-1])]
display(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', subset=[x for x in temp.columns if x not in ['Category', 'Detector']], axis=0).apply(highlight_categories, axis=1)) #.hide('Category', axis=1)

In [73]:
#AUC ROC of only best of each finetuned model version
temp = results_all.pivot_table('AUC ROC', 'Detector', "Dataset").sort_index(axis='columns')
temp = temp.sort_values(by='ALL_DATA', ascending=False)
temp['temp'] = [x.split('_')[0] for x in temp.index]
temp['Category'] = ['S' if x in statistical else 'P' if x in pretrained else 'F' for x in temp['temp']]
temp = temp.drop_duplicates(subset='temp').drop(columns='temp')
temp = temp.reset_index()
temp['Detector'] = temp['Detector'].apply(rename_detector)
temp = temp[[temp.columns[-1]] + list(temp.columns[:-1])]
display(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', subset=[x for x in temp.columns if x not in ['Category', 'Detector']], axis=0).hide().background_gradient(vmin=0.5, vmax=1.5, text_color_threshold=0, axis=None))
print(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', subset=[x for x in temp.columns if x not in ['Category', 'Detector']], axis=0).applymap_index(lambda v: "font-weight: bold;", axis=0).applymap_index(lambda v: "font-weight: bold;", axis=1).hide().background_gradient(vmin=0.5, vmax=1.5, text_color_threshold=0, axis=None).to_latex(convert_css=True))

\begin{tabular}{llrrrrrrrrr}
\bfseries Category & \bfseries Detector & \bfseries ALL_DATA & \bfseries Llama-2-70b-chat-hf & \bfseries Mistral-7B-Instruct-v0.2 & \bfseries aya-101 & \bfseries gemini & \bfseries gpt-3.5-turbo-0125 & \bfseries opt-iml-max-30b & \bfseries v5-Eagle-7B-HF & vicuna-13b \\
F & Llama-3.2-3B (de-pl-hu) & \bfseries {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9749 & {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9904 & {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9688 & {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9655 & \bfseries {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9754 & \bfseries {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9828 & \bfseries {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9632 & {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9822 & {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9789 \\
F & mDeBERTa-v3-base (de-pl-hr-hu-cs) & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9734 & \bfseries {\cellcolor[HTML]{76AAD0}} \color[HTML]{000000} 0.9935 & \bfseries {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9704 & \bfseries {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9662 & {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9706 & {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9797 & {\cellcolor[HTML]{88B1D4}} \color[HTML]{000000} 0.9505 & \bfseries {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9848 & \bfseries {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9801 \\
F & Gemma-2-2B (de-pl-cs) & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9627 & {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9777 & {\cellcolor[HTML]{86B0D3}} \color[HTML]{000000} 0.9555 & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9612 & {\cellcolor[HTML]{84B0D3}} \color[HTML]{000000} 0.9585 & {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9717 & {\cellcolor[HTML]{8BB2D4}} \color[HTML]{000000} 0.9452 & {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9722 & {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9653 \\
F & XLM-RoBERTa-base (de-pl-hr-hu-cs) & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9613 & {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9821 & {\cellcolor[HTML]{8BB2D4}} \color[HTML]{000000} 0.9430 & {\cellcolor[HTML]{88B1D4}} \color[HTML]{000000} 0.9526 & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9626 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9745 & {\cellcolor[HTML]{8CB3D5}} \color[HTML]{000000} 0.9403 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9732 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9732 \\
S & Fast-DetectGPT & {\cellcolor[HTML]{C5CCE3}} \color[HTML]{000000} 0.7830 & {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9667 & {\cellcolor[HTML]{EBE6F2}} \color[HTML]{000000} 0.6305 & {\cellcolor[HTML]{B5C4DF}} \color[HTML]{000000} 0.8292 & {\cellcolor[HTML]{C2CBE2}} \color[HTML]{000000} 0.7920 & {\cellcolor[HTML]{C0C9E2}} \color[HTML]{000000} 0.7986 & {\cellcolor[HTML]{E9E5F1}} \color[HTML]{000000} 0.6377 & {\cellcolor[HTML]{A7BDDB}} \color[HTML]{000000} 0.8729 & {\cellcolor[HTML]{B4C4DF}} \color[HTML]{000000} 0.8325 \\
S & Binoculars & {\cellcolor[HTML]{CDD0E5}} \color[HTML]{000000} 0.7603 & {\cellcolor[HTML]{86B0D3}} \color[HTML]{000000} 0.9555 & {\cellcolor[HTML]{EDE7F2}} \color[HTML]{000000} 0.6211 & {\cellcolor[HTML]{C1CAE2}} \color[HTML]{000000} 0.7955 & {\cellcolor[HTML]{C4CBE3}} \color[HTML]{000000} 0.7889 & {\cellcolor[HTML]{C8CDE4}} \color[HTML]{000000} 0.7756 & {\cellcolor[HTML]{F0EAF4}} \color[HTML]{000000} 0.5985 & {\cellcolor[HTML]{ADC1DD}} \color[HTML]{000000} 0.8518 & {\cellcolor[HTML]{BDC8E1}} \color[HTML]{000000} 0.8075 \\
S & LLM-Deviation & {\cellcolor[HTML]{DFDDEC}} \color[HTML]{000000} 0.6843 & {\cellcolor[HTML]{A1BBDA}} \color[HTML]{000000} 0.8873 & {\cellcolor[HTML]{EDE7F2}} \color[HTML]{000000} 0.6233 & {\cellcolor[HTML]{E0DDED}} \color[HTML]{000000} 0.6807 & {\cellcolor[HTML]{E5E1EF}} \color[HTML]{000000} 0.6584 & {\cellcolor[HTML]{DFDDEC}} \color[HTML]{000000} 0.6861 & {\cellcolor[HTML]{F6EFF7}} \color[HTML]{000000} 0.5610 & {\cellcolor[HTML]{CED0E6}} \color[HTML]{000000} 0.7570 & {\cellcolor[HTML]{D9D8EA}} \color[HTML]{000000} 0.7088 \\
P & BLOOMZ-3B-mixed-detector & {\cellcolor[HTML]{E1DFED}} \color[HTML]{000000} 0.6730 & {\cellcolor[HTML]{F9F2F8}} \color[HTML]{000000} 0.5410 & {\cellcolor[HTML]{EBE6F2}} \color[HTML]{000000} 0.6302 & {\cellcolor[HTML]{E3E0EE}} \color[HTML]{000000} 0.6655 & {\cellcolor[HTML]{ECE7F2}} \color[HTML]{000000} 0.6271 & {\cellcolor[HTML]{CACEE5}} \color[HTML]{000000} 0.7694 & {\cellcolor[HTML]{E2DFEE}} \color[HTML]{000000} 0.6697 & {\cellcolor[HTML]{DBDAEB}} \color[HTML]{000000} 0.7000 & {\cellcolor[HTML]{DDDBEC}} \color[HTML]{000000} 0.6923 \\
P & ChatGPT-detector-RoBERTa-Chinese & {\cellcolor[HTML]{E8E4F0}} \color[HTML]{000000} 0.6423 & {\cellcolor[HTML]{C1CAE2}} \color[HTML]{000000} 0.7949 & {\cellcolor[HTML]{E0DEED}} \color[HTML]{000000} 0.6784 & {\cellcolor[HTML]{EFE9F3}} \color[HTML]{000000} 0.6090 & {\cellcolor[HTML]{DEDCEC}} \color[HTML]{000000} 0.6906 & {\cellcolor[HTML]{F2ECF5}} \color[HTML]{000000} 0.5882 & {\cellcolor[HTML]{F5EEF6}} \color[HTML]{000000} 0.5667 & {\cellcolor[HTML]{E9E5F1}} \color[HTML]{000000} 0.6403 & {\cellcolor[HTML]{E2DFEE}} \color[HTML]{000000} 0.6711 \\
P & Detection-Longformer & {\cellcolor[HTML]{F6EFF7}} \color[HTML]{000000} 0.5615 & {\cellcolor[HTML]{E5E1EF}} \color[HTML]{000000} 0.6601 & {\cellcolor[HTML]{F0EAF4}} \color[HTML]{000000} 0.6045 & {\cellcolor[HTML]{FCF4FA}} \color[HTML]{000000} 0.5209 & {\cellcolor[HTML]{FEF6FB}} \color[HTML]{000000} 0.5045 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4613 & {\cellcolor[HTML]{F8F1F8}} \color[HTML]{000000} 0.5453 & {\cellcolor[HTML]{ECE7F2}} \color[HTML]{000000} 0.6283 & {\cellcolor[HTML]{F2ECF5}} \color[HTML]{000000} 0.5879 \\
\end{tabular}

In [55]:
results_all = pd.DataFrame()
for dataset in [to_auc_dict(df[df.domain=="news"].reset_index(), True), to_auc_dict(df[df.domain=="social_media"].reset_index(), True)]:
 for detector in tqdm(selected):
  temp = pd.DataFrame({'Dataset': dataset['domains'][0], 'Detector': detector, 'Language': '{all}', 'AUC ROC': dataset[detector]['auc'], 'TPR @ 5% FPR': dataset[detector]['tpr_5%fpr'], 'Th @ 5% FPR': dataset[detector]['th_5%fpr'], 'Th @ max(TPR-FPR)': dataset[detector]['th_optim']}, index=[0])
  results_all = pd.concat([results_all, temp])
  for test_language,val in dataset[detector].items():
    if (test_language == 'auc') or ('_' in test_language): continue
    temp = pd.DataFrame({'Dataset': dataset['domains'][0], 'Detector': detector, 'Language': test_language, 'AUC ROC': dataset[detector][test_language]['auc'], 'TPR @ 5% FPR': val['tpr_5%fpr']}, index=[0])
    results_all = pd.concat([results_all, temp])
results_all = results_all[results_all['Detector'].isin(selected)]
#only best of each finetuned model version
temp = results_all.pivot_table(['AUC ROC', 'TPR @ 5% FPR'], 'Detector', ["Dataset", "Language"])['AUC ROC']#.reorder_levels(axis='columns', order=[1,0])#.sort_index(axis='columns')#.sort_index(axis='index', ascending=False)
temp = temp.stack(level=0)
temp.rename(columns={'{all}':'All'}, inplace=True)
temp = temp.sort_index(axis='columns')
temp = temp.sort_values(by='All', ascending=False)
temp['temp'] = [x.split('_')[0] + y for x,y in zip(temp.reset_index()['Detector'], temp.reset_index()['Dataset'])]
temp = temp.drop_duplicates(subset='temp').drop(columns='temp')
#display(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0))

#temp = temp.reset_index()
#temp.index = temp.index.set_levels(pd.CategoricalIndex(temp.index.levels[1].values, categories=['news'], ordered=True), level=1)
#temp = temp.sort_index(level=1).sort_index(level=0, key=lambda x: x.map(adversarial_key))
temp = temp.reset_index()
temp['Detector'] = temp['Detector'].map(rename_detector)
temp = temp.set_index(['Dataset', 'Detector'])
temp = temp.sort_values(['Dataset', 'All'], ascending=False)
temp2 = temp.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).apply(lambda x: np.select([temp.eq(temp.groupby('Dataset').transform('max'))], ['font-weight: bold;'], default=''), axis=None).highlight_max(props='text-decoration: underline', axis=0).background_gradient(vmin=0.5, vmax=1.5, text_color_threshold=0, axis=None)
display(temp2)
print(temp2.to_latex(convert_css=True).replace('\n\multirow','\n\hline\n\multirow'))

Best FPR: xlm-roberta-base_hr-cs sk 0.072
Best FPR: xlm-roberta-base_de-hr sl 0.076
Best FPR: xlm-roberta-base_pl de 0.088
Best FPR: xlm-roberta-base_hr sk 0.092
Best FPR: xlm-roberta-base_hr sl 0.292
Best FPR: xlm-roberta-base_hr-hu sk 0.076
Best FPR: xlm-roberta-base_hr-hu sl 0.052
Best FPR: mdeberta-v3-base_hr-cs pl 0.072
Best FPR: mdeberta-v3-base_de-hr-hu-cs pl 0.052
Best FPR: xlm-roberta-base_cs de 0.052
Best FPR: xlm-roberta-base_cs hr 0.068
Best FPR: xlm-roberta-base_cs sk 0.084
Best FPR: Llama-3.2-3B_hr sl 0.1
Best FPR: Llama-3.2-3B_de-pl-hr-hu hu 0.084
Best FPR: Llama-3.2-3B_de-pl-hr-hu sl 0.06
Best FPR: gemma-2-2b_pl-cs de 0.08
Best FPR: gemma-2-2b_pl de 0.256
Best FPR: gemma-2-2b_hr sl 0.096
Best FPR: gemma-2-2b_pl-hr de 0.088
Best FPR: gemma-2-2b_pl-hr-cs de 0.056
Best FPR: Llama-3.2-3B_de-hr-cs sl 0.052
Best FPR: andreas122001-bloomz-3b-mixed-detector sl 0.116
Best FPR: xlm-roberta-base_hr-cs cs 0.064
Best FPR: xlm-roberta-base_hr-cs de 0.14
Best FPR: xlm-roberta-base_hr-cs pl 0.108
Best FPR: xlm-roberta-base_hr-cs sk 0.116
Best FPR: xlm-roberta-base_hr-cs sl 0.372
Best FPR: xlm-roberta-base_de-hu-cs cs 0.072
Best FPR: xlm-roberta-base_de-hu-cs hu 0.052
Best FPR: xlm-roberta-base_de-hu-cs pl 0.096
Best FPR: xlm-roberta-base_de-hu-cs sk 0.1
Best FPR: xlm-roberta-base_de-hu-cs sl 0.156
Best FPR: xlm-roberta-base_de-hr-hu-cs sl 0.14
Best FPR: xlm-roberta-base_de-hr sl 0.232
Best FPR: xlm-roberta-base_de-hr-hu pl 0.072
Best FPR: xlm-roberta-base_de-hr-hu sk 0.096
Best FPR: xlm-roberta-base_de-hr-hu sl 0.212
Best FPR: xlm-roberta-base_de-pl-hr-hu sl 0.108
Best FPR: xlm-roberta-base_hu-cs de 0.076
Best FPR: xlm-roberta-base_hu-cs pl 0.076
Best FPR: xlm-roberta-base_hu-cs sk 0.076
Best FPR: xlm-roberta-base_hu-cs sl 0.088
Best FPR: xlm-roberta-base_hr cs 0.052
Best FPR: xlm-roberta-base_hr de 0.112
Best FPR: xlm-roberta-base_hr hr 0.064
Best FPR: xlm-roberta-base_hr pl 0.1
Best FPR: xlm-roberta-base_hr sk 0.104
Best FPR: xlm-roberta-base_hr sl 0.468
Best FPR: xlm-roberta-base_hr-hu cs 0.06
Best FPR: xlm-roberta-base_hr-hu de 0.108
Best FPR: xlm-roberta-base_hr-hu pl 0.124
Best FPR: xlm-roberta-base_hr-hu sk 0.124
Best FPR: xlm-roberta-base_hr-hu sl 0.372
Best FPR: xlm-roberta-base_pl-cs de 0.072
Best FPR: xlm-roberta-base_pl-cs sl 0.088
Best FPR: xlm-roberta-base_pl-hu-cs de 0.06
Best FPR: xlm-roberta-base_pl-hu-cs pl 0.06
Best FPR: xlm-roberta-base_pl-hu-cs sl 0.068
Best FPR: xlm-roberta-base_pl-hr-hu-cs de 0.064
Best FPR: xlm-roberta-base_pl-hr-hu-cs sl 0.116
Best FPR: xlm-roberta-base_pl-hr sl 0.104
Best FPR: xlm-roberta-base_pl-hr-hu sl 0.092
Best FPR: mdeberta-v3-base_hr-cs sl 0.052
Best FPR: mdeberta-v3-base_de-hr-hu-cs sl 0.056
Best FPR: mdeberta-v3-base_de-hr-hu sl 0.068
Best FPR: mdeberta-v3-base_hu de 0.052
Best FPR: mdeberta-v3-base_hu sk 0.072
Best FPR: mdeberta-v3-base_hu sl 0.092
Best FPR: mdeberta-v3-base_hu-cs de 0.052
Best FPR: mdeberta-v3-base_hu-cs sl 0.064
Best FPR: xlm-roberta-base_cs de 0.076
Best FPR: xlm-roberta-base_cs pl 0.076
Best FPR: xlm-roberta-base_cs sk 0.06
Best FPR: xlm-roberta-base_cs sl 0.06
Best FPR: Llama-3.2-3B_hr-cs cs 0.06
Best FPR: Llama-3.2-3B_hr-cs hr 0.092
Best FPR: Llama-3.2-3B_hr-cs sk 0.084
Best FPR: Llama-3.2-3B_hr-cs sl 0.348
Best FPR: mdeberta-v3-base_cs sl 0.052
Best FPR: Llama-3.2-3B_pl pl 0.064
Best FPR: Llama-3.2-3B_pl sl 0.096
Best FPR: Llama-3.2-3B_hr hr 0.08
Best FPR: Llama-3.2-3B_hr sk 0.072
Best FPR: Llama-3.2-3B_hr sl 0.436
Best FPR: Llama-3.2-3B_hu hu 0.06
Best FPR: Llama-3.2-3B_hu sk 0.068
Best FPR: Llama-3.2-3B_hu sl 0.076
Best FPR: Llama-3.2-3B_de pl 0.064
Best FPR: Llama-3.2-3B_de-hr hr 0.06
Best FPR: Llama-3.2-3B_de-hr pl 0.064
Best FPR: Llama-3.2-3B_de-hr sk 0.088
Best FPR: Llama-3.2-3B_de-hr sl 0.328
Best FPR: Llama-3.2-3B_pl-hr de 0.056
Best FPR: Llama-3.2-3B_pl-hr hr 0.056
Best FPR: Llama-3.2-3B_pl-hr pl 0.068
Best FPR: Llama-3.2-3B_pl-hr sk 0.088
Best FPR: Llama-3.2-3B_pl-hr sl 0.336
Best FPR: Llama-3.2-3B_de-pl-hr sl 0.18
Best FPR: Llama-3.2-3B_pl-hr-cs sl 0.172
Best FPR: Llama-3.2-3B_hr-hu-cs cs 0.052
Best FPR: Llama-3.2-3B_hr-hu-cs hr 0.072
Best FPR: Llama-3.2-3B_hr-hu-cs pl 0.068
Best FPR: Llama-3.2-3B_hr-hu-cs sk 0.092
Best FPR: Llama-3.2-3B_hr-hu-cs sl 0.312
Best FPR: Llama-3.2-3B_de-hr-hu-cs pl 0.072
Best FPR: Llama-3.2-3B_de-hr-hu-cs sk 0.06
Best FPR: Llama-3.2-3B_de-hr-hu-cs sl 0.24
Best FPR: Llama-3.2-3B_pl-hr-hu-cs de 0.068
Best FPR: Llama-3.2-3B_pl-hr-hu-cs hr 0.084
Best FPR: Llama-3.2-3B_pl-hr-hu-cs pl 0.06
Best FPR: Llama-3.2-3B_pl-hr-hu-cs sk 0.1
Best FPR: Llama-3.2-3B_pl-hr-hu-cs sl 0.288
Best FPR: Llama-3.2-3B_de-pl-hr-hu de 0.06
Best FPR: Llama-3.2-3B_de-pl-hr-hu hr 0.06
Best FPR: Llama-3.2-3B_de-pl-hr-hu pl 0.072
Best FPR: Llama-3.2-3B_de-pl-hr-hu sk 0.096
Best FPR: Llama-3.2-3B_de-pl-hr-hu sl 0.24
Best FPR: Llama-3.2-3B_de-hu de 0.052
Best FPR: Llama-3.2-3B_de-hu hu 0.056
Best FPR: Llama-3.2-3B_de-hu pl 0.056
Best FPR: Llama-3.2-3B_de-hu sk 0.052
Best FPR: Llama-3.2-3B_pl-hu de 0.096
Best FPR: Llama-3.2-3B_pl-hu pl 0.08
Best FPR: Llama-3.2-3B_pl-hu sk 0.072
Best FPR: Llama-3.2-3B_pl-hu sl 0.152
Best FPR: Llama-3.2-3B_hr-hu cs 0.064
Best FPR: Llama-3.2-3B_hr-hu hr 0.072
Best FPR: Llama-3.2-3B_hr-hu pl 0.056
Best FPR: Llama-3.2-3B_hr-hu sk 0.108
Best FPR: Llama-3.2-3B_hr-hu sl 0.324
Best FPR: Llama-3.2-3B_de-hr-hu cs 0.068
Best FPR: Llama-3.2-3B_de-hr-hu hr 0.06
Best FPR: Llama-3.2-3B_de-hr-hu hu 0.052
Best FPR: Llama-3.2-3B_de-hr-hu pl 0.076
Best FPR: Llama-3.2-3B_de-hr-hu sk 0.096
Best FPR: Llama-3.2-3B_de-hr-hu sl 0.264
Best FPR: Llama-3.2-3B_pl-hr-hu cs 0.06
Best FPR: Llama-3.2-3B_pl-hr-hu de 0.108
Best FPR: Llama-3.2-3B_pl-hr-hu hr 0.116
Best FPR: Llama-3.2-3B_pl-hr-hu pl 0.064
Best FPR: Llama-3.2-3B_pl-hr-hu sk 0.152
Best FPR: Llama-3.2-3B_pl-hr-hu sl 0.404
Best FPR: gemma-2-2b_pl-cs de 0.092
Best FPR: gemma-2-2b_pl-hu-cs de 0.108
Best FPR: gemma-2-2b_pl-hu-cs sk 0.056
Best FPR: gemma-2-2b_pl-hu-cs sl 0.068
Best FPR: gemma-2-2b_de-pl-cs sl 0.064
Best FPR: gemma-2-2b_pl de 0.124
Best FPR: Llama-3.2-3B_cs cs 0.056
Best FPR: Llama-3.2-3B_cs sk 0.06
Best FPR: gemma-2-2b_hr hr 0.076
Best FPR: gemma-2-2b_hr sl 0.28
Best FPR: gemma-2-2b_de-hr sl 0.236
Best FPR: gemma-2-2b_pl-hr de 0.116
Best FPR: gemma-2-2b_pl-hr hr 0.052
Best FPR: gemma-2-2b_pl-hr sk 0.06
Best FPR: gemma-2-2b_pl-hr sl 0.272
Best FPR: gemma-2-2b_de-pl-hr sl 0.212
Best FPR: gemma-2-2b_de-hr-cs hr 0.056
Best FPR: gemma-2-2b_de-hr-cs pl 0.056
Best FPR: gemma-2-2b_de-hr-cs sk 0.076
Best FPR: gemma-2-2b_de-hr-cs sl 0.224
Best FPR: gemma-2-2b_pl-hr-cs de 0.064
Best FPR: gemma-2-2b_pl-hr-cs sk 0.06
Best FPR: gemma-2-2b_pl-hr-cs sl 0.232
Best FPR: gemma-2-2b_pl-hr-hu-cs de 0.08
Best FPR: gemma-2-2b_pl-hr-hu-cs pl 0.052
Best FPR: gemma-2-2b_pl-hr-hu-cs sk 0.084
Best FPR: gemma-2-2b_pl-hr-hu-cs sl 0.196
Best FPR: gemma-2-2b_cs cs 0.056
Best FPR: gemma-2-2b_cs pl 0.072
Best FPR: gemma-2-2b_cs sk 0.076
Best FPR: gemma-2-2b_de-hr-hu-cs pl 0.056
Best FPR: gemma-2-2b_de-hr-hu-cs sk 0.1
Best FPR: gemma-2-2b_de-hr-hu-cs sl 0.204
Best FPR: gemma-2-2b_de-hr-hu sl 0.204
Best FPR: gemma-2-2b_de-pl-hr-cs hr 0.052
Best FPR: gemma-2-2b_de-pl-hr-cs sk 0.072
Best FPR: gemma-2-2b_de-pl-hr-cs sl 0.2
Best FPR: gemma-2-2b_de-pl-hr-hu-cs sk 0.06
Best FPR: gemma-2-2b_de-pl-hr-hu-cs sl 0.188
Best FPR: gemma-2-2b_de-pl-hr-hu sk 0.06
Best FPR: gemma-2-2b_de-pl-hr-hu sl 0.196
Best FPR: gemma-2-2b_de-pl-hu-cs sk 0.056
Best FPR: gemma-2-2b_hr-cs de 0.084
Best FPR: gemma-2-2b_hr-cs hr 0.06
Best FPR: gemma-2-2b_hr-cs sk 0.052
Best FPR: gemma-2-2b_hr-cs sl 0.3
Best FPR: gemma-2-2b_hr-hu-cs hr 0.064
Best FPR: gemma-2-2b_hr-hu-cs sk 0.068
Best FPR: gemma-2-2b_hr-hu-cs sl 0.188
Best FPR: gemma-2-2b_hr-hu hr 0.06
Best FPR: gemma-2-2b_hr-hu sl 0.252
Best FPR: gemma-2-2b_hu-cs pl 0.052
Best FPR: gemma-2-2b_hu-cs sl 0.064
Best FPR: gemma-2-2b_pl-hr-hu de 0.068
Best FPR: gemma-2-2b_pl-hr-hu sk 0.068
Best FPR: gemma-2-2b_pl-hr-hu sl 0.26
Best FPR: gemma-2-2b_pl-hu de 0.104
Best FPR: Llama-3.2-3B_de-cs pl 0.056
Best FPR: Llama-3.2-3B_de-hr-cs sl 0.16
Best FPR: Llama-3.2-3B_de-hu-cs pl 0.064
Best FPR: Llama-3.2-3B_de-hu-cs sl 0.052
Best FPR: Llama-3.2-3B_de-pl-hr-hu-cs de 0.052
Best FPR: Llama-3.2-3B_de-pl-hr-hu-cs hr 0.052
Best FPR: Llama-3.2-3B_de-pl-hr-hu-cs pl 0.072
Best FPR: Llama-3.2-3B_de-pl-hr-hu-cs sk 0.06
Best FPR: Llama-3.2-3B_de-pl-hr-hu-cs sl 0.172
Best FPR: Llama-3.2-3B_hu-cs pl 0.068
Best FPR: Llama-3.2-3B_hu-cs sk 0.056
Best FPR: Llama-3.2-3B_hu-cs sl 0.084
Best FPR: Llama-3.2-3B_pl-hu-cs de 0.068
Best FPR: Llama-3.2-3B_pl-hu-cs pl 0.056
Best FPR: Llama-3.2-3B_pl-hu-cs sl 0.092
Best FPR: xlm-roberta-base_de-hr-cs pl 0.056
Best FPR: xlm-roberta-base_de-hr-cs sl 0.148

100%|██████████| 130/130 [00:01<00:00, 115.89it/s]
100%|██████████| 130/130 [00:01<00:00, 115.87it/s]

\begin{tabular}{llrrrrrrrr}
 & Language & All & cs & de & hr & hu & pl & sk & sl \\
Dataset & Detector &  &  &  &  &  &  &  &  \\
\hline
\multirow[c]{10}{*}{social_media} & Llama-3.2-3B (de-pl-hu) & \bfseries {\cellcolor[HTML]{88B1D4}} \color[HTML]{000000} 0.9506 & \bfseries {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9800 & {\cellcolor[HTML]{8BB2D4}} \color[HTML]{000000} 0.9427 & \bfseries {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9628 & \bfseries {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9744 & \bfseries {\cellcolor[HTML]{89B1D4}} \color[HTML]{000000} 0.9466 & \bfseries {\cellcolor[HTML]{88B1D4}} \color[HTML]{000000} 0.9527 & {\cellcolor[HTML]{96B6D7}} \color[HTML]{000000} 0.9176 \\
 & mDeBERTa-v3-base (de) & {\cellcolor[HTML]{89B1D4}} \color[HTML]{000000} 0.9476 & {\cellcolor[HTML]{86B0D3}} \color[HTML]{000000} 0.9536 & \bfseries {\cellcolor[HTML]{88B1D4}} \color[HTML]{000000} 0.9515 & {\cellcolor[HTML]{88B1D4}} \color[HTML]{000000} 0.9503 & {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9708 & {\cellcolor[HTML]{8CB3D5}} \color[HTML]{000000} 0.9413 & {\cellcolor[HTML]{8BB2D4}} \color[HTML]{000000} 0.9439 & \bfseries {\cellcolor[HTML]{8FB4D6}} \color[HTML]{000000} 0.9306 \\
 & XLM-RoBERTa-base (de-pl) & {\cellcolor[HTML]{8CB3D5}} \color[HTML]{000000} 0.9412 & {\cellcolor[HTML]{84B0D3}} \color[HTML]{000000} 0.9590 & {\cellcolor[HTML]{8EB3D5}} \color[HTML]{000000} 0.9344 & {\cellcolor[HTML]{86B0D3}} \color[HTML]{000000} 0.9548 & {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9670 & {\cellcolor[HTML]{91B5D6}} \color[HTML]{000000} 0.9282 & {\cellcolor[HTML]{8BB2D4}} \color[HTML]{000000} 0.9424 & {\cellcolor[HTML]{9EBAD9}} \color[HTML]{000000} 0.8972 \\
 & Gemma-2-2B (de-pl-hr-hu-cs) & {\cellcolor[HTML]{8FB4D6}} \color[HTML]{000000} 0.9313 & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9631 & {\cellcolor[HTML]{8FB4D6}} \color[HTML]{000000} 0.9334 & {\cellcolor[HTML]{89B1D4}} \color[HTML]{000000} 0.9468 & {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9686 & {\cellcolor[HTML]{93B5D6}} \color[HTML]{000000} 0.9240 & {\cellcolor[HTML]{8FB4D6}} \color[HTML]{000000} 0.9324 & {\cellcolor[HTML]{AFC1DD}} \color[HTML]{000000} 0.8483 \\
 & LLM-Deviation & {\cellcolor[HTML]{BDC8E1}} \color[HTML]{000000} 0.8049 & {\cellcolor[HTML]{A1BBDA}} \color[HTML]{000000} 0.8877 & {\cellcolor[HTML]{D5D5E8}} \color[HTML]{000000} 0.7279 & {\cellcolor[HTML]{BFC9E1}} \color[HTML]{000000} 0.8030 & {\cellcolor[HTML]{9CB9D9}} \color[HTML]{000000} 0.8990 & {\cellcolor[HTML]{BBC7E0}} \color[HTML]{000000} 0.8128 & {\cellcolor[HTML]{C5CCE3}} \color[HTML]{000000} 0.7818 & {\cellcolor[HTML]{D1D2E6}} \color[HTML]{000000} 0.7484 \\
 & Binoculars & {\cellcolor[HTML]{C9CEE4}} \color[HTML]{000000} 0.7699 & {\cellcolor[HTML]{C2CBE2}} \color[HTML]{000000} 0.7911 & {\cellcolor[HTML]{C2CBE2}} \color[HTML]{000000} 0.7922 & {\cellcolor[HTML]{BCC7E1}} \color[HTML]{000000} 0.8107 & {\cellcolor[HTML]{C4CBE3}} \color[HTML]{000000} 0.7856 & {\cellcolor[HTML]{CDD0E5}} \color[HTML]{000000} 0.7598 & {\cellcolor[HTML]{D2D3E7}} \color[HTML]{000000} 0.7384 & {\cellcolor[HTML]{D8D7E9}} \color[HTML]{000000} 0.7169 \\
 & BLOOMZ-3B-mixed-detector & {\cellcolor[HTML]{CCCFE5}} \color[HTML]{000000} 0.7627 & {\cellcolor[HTML]{C0C9E2}} \color[HTML]{000000} 0.7989 & {\cellcolor[HTML]{C5CCE3}} \color[HTML]{000000} 0.7843 & {\cellcolor[HTML]{C8CDE4}} \color[HTML]{000000} 0.7748 & {\cellcolor[HTML]{B3C3DE}} \color[HTML]{000000} 0.8394 & {\cellcolor[HTML]{CACEE5}} \color[HTML]{000000} 0.7661 & {\cellcolor[HTML]{CCCFE5}} \color[HTML]{000000} 0.7625 & {\cellcolor[HTML]{E8E4F0}} \color[HTML]{000000} 0.6438 \\
 & Fast-DetectGPT & {\cellcolor[HTML]{CCCFE5}} \color[HTML]{000000} 0.7617 & {\cellcolor[HTML]{CCCFE5}} \color[HTML]{000000} 0.7626 & {\cellcolor[HTML]{C5CCE3}} \color[HTML]{000000} 0.7827 & {\cellcolor[HTML]{BFC9E1}} \color[HTML]{000000} 0.8044 & {\cellcolor[HTML]{C6CCE3}} \color[HTML]{000000} 0.7780 & {\cellcolor[HTML]{D1D2E6}} \color[HTML]{000000} 0.7500 & {\cellcolor[HTML]{D1D2E6}} \color[HTML]{000000} 0.7467 & {\cellcolor[HTML]{D6D6E9}} \color[HTML]{000000} 0.7238 \\
 & ChatGPT-detector-RoBERTa-Chinese & {\cellcolor[HTML]{E1DFED}} \color[HTML]{000000} 0.6737 & {\cellcolor[HTML]{E4E1EF}} \color[HTML]{000000} 0.6605 & {\cellcolor[HTML]{C0C9E2}} \color[HTML]{000000} 0.7974 & {\cellcolor[HTML]{EDE7F2}} \color[HTML]{000000} 0.6211 & {\cellcolor[HTML]{C6CCE3}} \color[HTML]{000000} 0.7778 & {\cellcolor[HTML]{EDE8F3}} \color[HTML]{000000} 0.6179 & {\cellcolor[HTML]{EAE6F1}} \color[HTML]{000000} 0.6345 & {\cellcolor[HTML]{E7E3F0}} \color[HTML]{000000} 0.6480 \\
 & Detection-Longformer & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4757 & {\cellcolor[HTML]{FEF6FB}} \color[HTML]{000000} 0.5054 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3848 & {\cellcolor[HTML]{F8F1F8}} \color[HTML]{000000} 0.5480 & {\cellcolor[HTML]{FBF3F9}} \color[HTML]{000000} 0.5288 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4772 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4293 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4382 \\
\hline
\multirow[c]{10}{*}{news} & Llama-3.2-3B (hr-hu-cs) & \bfseries \bfseries {\cellcolor[HTML]{76AAD0}} \color[HTML]{000000} 0.9952 & {\cellcolor[HTML]{75A9CF}} \color[HTML]{000000} 0.9976 & \bfseries \bfseries {\cellcolor[HTML]{76AAD0}} \color[HTML]{000000} 0.9926 & \bfseries \bfseries {\cellcolor[HTML]{75A9CF}} \color[HTML]{000000} 0.9994 & \bfseries \bfseries {\cellcolor[HTML]{75A9CF}} \color[HTML]{000000} 0.9967 & \bfseries \bfseries {\cellcolor[HTML]{76AAD0}} \color[HTML]{000000} 0.9937 & {\cellcolor[HTML]{76AAD0}} \color[HTML]{000000} 0.9928 & {\cellcolor[HTML]{76AAD0}} \color[HTML]{000000} 0.9943 \\
 & mDeBERTa-v3-base (cs) & {\cellcolor[HTML]{76AAD0}} \color[HTML]{000000} 0.9940 & \bfseries \bfseries {\cellcolor[HTML]{75A9CF}} \color[HTML]{000000} 0.9986 & {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9921 & {\cellcolor[HTML]{76AAD0}} \color[HTML]{000000} 0.9924 & {\cellcolor[HTML]{76AAD0}} \color[HTML]{000000} 0.9925 & {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9900 & \bfseries \bfseries {\cellcolor[HTML]{75A9CF}} \color[HTML]{000000} 0.9981 & \bfseries \bfseries {\cellcolor[HTML]{75A9CF}} \color[HTML]{000000} 0.9973 \\
 & Gemma-2-2B (de-pl-cs) & {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9911 & {\cellcolor[HTML]{75A9CF}} \color[HTML]{000000} 0.9966 & {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9912 & {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9827 & {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9882 & {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9878 & {\cellcolor[HTML]{75A9CF}} \color[HTML]{000000} 0.9978 & {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9894 \\
 & XLM-RoBERTa-base (de-pl-hr-hu-cs) & {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9824 & {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9896 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9728 & {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9876 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9759 & {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9847 & {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9769 & {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9910 \\
 & Fast-DetectGPT & {\cellcolor[HTML]{AFC1DD}} \color[HTML]{000000} 0.8490 & {\cellcolor[HTML]{A5BDDB}} \color[HTML]{000000} 0.8773 & {\cellcolor[HTML]{A7BDDB}} \color[HTML]{000000} 0.8717 & {\cellcolor[HTML]{A5BDDB}} \color[HTML]{000000} 0.8777 & {\cellcolor[HTML]{C4CBE3}} \color[HTML]{000000} 0.7867 & {\cellcolor[HTML]{B4C4DF}} \color[HTML]{000000} 0.8351 & {\cellcolor[HTML]{B1C2DE}} \color[HTML]{000000} 0.8413 & {\cellcolor[HTML]{99B8D8}} \color[HTML]{000000} 0.9090 \\
 & Binoculars & {\cellcolor[HTML]{B4C4DF}} \color[HTML]{000000} 0.8341 & {\cellcolor[HTML]{A5BDDB}} \color[HTML]{000000} 0.8771 & {\cellcolor[HTML]{ADC1DD}} \color[HTML]{000000} 0.8536 & {\cellcolor[HTML]{A8BEDC}} \color[HTML]{000000} 0.8707 & {\cellcolor[HTML]{C6CCE3}} \color[HTML]{000000} 0.7809 & {\cellcolor[HTML]{B8C6E0}} \color[HTML]{000000} 0.8228 & {\cellcolor[HTML]{B5C4DF}} \color[HTML]{000000} 0.8298 & {\cellcolor[HTML]{9EBAD9}} \color[HTML]{000000} 0.8965 \\
 & LLM-Deviation & {\cellcolor[HTML]{DAD9EA}} \color[HTML]{000000} 0.7060 & {\cellcolor[HTML]{99B8D8}} \color[HTML]{000000} 0.9083 & {\cellcolor[HTML]{D5D5E8}} \color[HTML]{000000} 0.7298 & {\cellcolor[HTML]{9AB8D8}} \color[HTML]{000000} 0.9025 & {\cellcolor[HTML]{E8E4F0}} \color[HTML]{000000} 0.6429 & {\cellcolor[HTML]{D0D1E6}} \color[HTML]{000000} 0.7507 & {\cellcolor[HTML]{BDC8E1}} \color[HTML]{000000} 0.8048 & {\cellcolor[HTML]{99B8D8}} \color[HTML]{000000} 0.9072 \\
 & Detection-Longformer & {\cellcolor[HTML]{E7E3F0}} \color[HTML]{000000} 0.6503 & {\cellcolor[HTML]{EAE6F1}} \color[HTML]{000000} 0.6356 & {\cellcolor[HTML]{EFE9F3}} \color[HTML]{000000} 0.6074 & {\cellcolor[HTML]{CDD0E5}} \color[HTML]{000000} 0.7595 & {\cellcolor[HTML]{D0D1E6}} \color[HTML]{000000} 0.7507 & {\cellcolor[HTML]{DBDAEB}} \color[HTML]{000000} 0.7003 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4962 & {\cellcolor[HTML]{D8D7E9}} \color[HTML]{000000} 0.7168 \\
 & ChatGPT-detector-RoBERTa-Chinese & {\cellcolor[HTML]{EDE7F2}} \color[HTML]{000000} 0.6223 & {\cellcolor[HTML]{FAF2F8}} \color[HTML]{000000} 0.5364 & {\cellcolor[HTML]{D8D7E9}} \color[HTML]{000000} 0.7168 & {\cellcolor[HTML]{E3E0EE}} \color[HTML]{000000} 0.6672 & {\cellcolor[HTML]{E2DFEE}} \color[HTML]{000000} 0.6717 & {\cellcolor[HTML]{E6E2EF}} \color[HTML]{000000} 0.6541 & {\cellcolor[HTML]{CCCFE5}} \color[HTML]{000000} 0.7646 & {\cellcolor[HTML]{DAD9EA}} \color[HTML]{000000} 0.7038 \\
 & BLOOMZ-3B-mixed-detector & {\cellcolor[HTML]{F5EFF6}} \color[HTML]{000000} 0.5626 & {\cellcolor[HTML]{FEF6FB}} \color[HTML]{000000} 0.5049 & {\cellcolor[HTML]{F1EBF4}} \color[HTML]{000000} 0.5963 & {\cellcolor[HTML]{FBF4F9}} \color[HTML]{000000} 0.5271 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4680 & {\cellcolor[HTML]{F5EEF6}} \color[HTML]{000000} 0.5691 & {\cellcolor[HTML]{DCDAEB}} \color[HTML]{000000} 0.6970 & {\cellcolor[HTML]{F7F0F7}} \color[HTML]{000000} 0.5544 \\
\end{tabular}

In [ ]:
files = glob.glob("adversarial_*.csv.gz")
files

In [23]:
#load existing detectors
results_df = pd.DataFrame()
for file in tqdm(files):
  with gzip.open(file, 'rt') as gzf: #determine the index of last column
    reader = csv.reader(gzf, dialect=csv.excel)
    last_column_index = len(next(reader)) - 1
  if "Monoculars" in file:
    df = pd.read_csv(file)
    results_df[f"binoculars"] = pd.Series([x.replace('[','').replace(']','') for x in df['binoculars']]).astype(np.float16)
    results_df[f"fastdetectgpt"] = pd.Series([x.replace('[','').replace(']','') for x in df['fastgptdetect']]).astype(np.float16)
    results_df[f"llmdeviation"] = 1-pd.Series([x.replace('[','').replace(']','') for x in df['llmd1']]).astype(np.float16)
  else:
    df = pd.read_csv(file, usecols=[last_column_index], dtype=np.float16) #load only the last column
    model_name = file.split('/')[-1].split('adversarial_')[1].replace('_threshold', '').replace('.csv.gz', '').split('_')[-1]
    results_df[f"{model_name.replace('_','-')}"] = df[df.columns[-1]].astype(np.float16)
    if "unsup-simcse-roberta-base" == model_name: results_df[model_name] = 1-results_df[model_name]

100%|██████████| 4/4 [00:00<00:00, 47.41it/s]

In [24]:
df = pd.read_csv('adversarial_with_predictions.csv')

In [25]:
df.drop(columns=['text', 'split'], inplace=True)
df = pd.concat([df, results_df], axis=1)
selected = df.columns[4:].to_list()

In [26]:
df['obfuscator'] = [x.split('_')[-1] for x in df['multi_label']]
df.loc[(df.multi_label == "human_original"), 'obfuscator'] = "human_original"

In [27]:
df['obfuscator'].value_counts()

human_original    1400
original          1400
paraphrased       1400
homoglyph         1400
Name: obfuscator, dtype: int64

In [28]:
df.groupby('obfuscator').mean()

,label,is_machine_prob_mdeberta-v3-base,is_machine_prob_Llama-3.2-3B,is_machine_prob_xlm-roberta-base,is_machine_prob_gemma-2-2b,Hello-SimpleAI-chatgpt-detector-roberta-chinese,andreas122001-bloomz-3b-mixed-detector,binoculars,fastdetectgpt,llmdeviation,nealcly-detection-longformer
obfuscator,,,,,,,,,,,
homoglyph,1.0,0.428555,0.744980,0.290978,0.567209,0.087280,0.188110,-1.213867,-3.925781,-14.023438,0.615723
human_original,0.0,0.141293,0.097793,0.226763,0.063907,0.046539,0.232300,-1.133789,-1.230469,-13.710938,0.465332
original,1.0,0.944219,0.915888,0.909476,0.834483,0.143799,0.467529,-0.986816,0.472168,-7.375000,0.533691
paraphrased,1.0,0.972859,0.958918,0.936118,0.909662,0.155518,0.750000,-1.021484,-0.272461,-7.574219,0.474365

In [29]:
df.groupby(['obfuscator', 'language']).mean()

                         label  is_machine_prob_mdeberta-v3-base  \
obfuscator     language
homoglyph      cs          1.0                          0.461934
               de          1.0                          0.398483
               hr          1.0                          0.419340
               hu          1.0                          0.490703
               pl          1.0                          0.373685
               sk          1.0                          0.444450
               sl          1.0                          0.411289
human_original cs          0.0                          0.081430
               de          0.0                          0.186075
               hr          0.0                          0.121312
               hu          0.0                          0.107270
               pl          0.0                          0.154759
               sk          0.0                          0.131674
               sl          0.0                          0.206534
original       cs          1.0                          0.925235
               de          1.0                          0.958951
               hr          1.0                          0.901760
               hu          1.0                          0.974431
               pl          1.0                          0.949426
               sk          1.0                          0.930945
               sl          1.0                          0.968785
paraphrased    cs          1.0                          0.969491
               de          1.0                          0.978511
               hr          1.0                          0.938757
               hu          1.0                          0.986432
               pl          1.0                          0.973492
               sk          1.0                          0.983746
               sl          1.0                          0.979584

                         is_machine_prob_Llama-3.2-3B  \
obfuscator     language
homoglyph      cs                            0.862814
               de                            0.739230
               hr                            0.595987
               hu                            0.866306
               pl                            0.805376
               sk                            0.742166
               sl                            0.602980
human_original cs                            0.105103
               de                            0.098841
               hr                            0.016797
               hu                            0.121110
               pl                            0.150570
               sk                            0.118615
               sl                            0.073518
original       cs                            0.940765
               de                            0.924182
               hr                            0.867493
               hu                            0.974227
               pl                            0.950119
               sk                            0.914067
               sl                            0.840360
paraphrased    cs                            0.977161
               de                            0.969534
               hr                            0.919137
               hu                            0.981228
               pl                            0.967263
               sk                            0.973105
               sl                            0.924999

                         is_machine_prob_xlm-roberta-base  \
obfuscator     language
homoglyph      cs                                0.329866
               de                                0.221279
               hr                                0.248059
               hu                                0.390414
               pl                                0.304930
               sk                                0.309517
               sl                                0.232784
human_original cs                                0.147773
               de                                0.304814
               hr                                0.158047
               hu                                0.176401
               pl                                0.231307
               sk                                0.288384
               sl                                0.280611
original       cs                                0.903748
               de                                0.926357
               hr                                0.866849
               hu                                0.946320
               pl                                0.926221
               sk                                0.904554
               sl                                0.892283
paraphrased    cs                                0.932390
               de                                0.940559
               hr                                0.906042
               hu                                0.964045
               pl                                0.927410
               sk                                0.947544
               sl                                0.934835

                         is_machine_prob_gemma-2-2b  \
obfuscator     language
homoglyph      cs                          0.586272
               de                          0.781888
               hr                          0.274650
               hu                          0.833213
               pl                          0.678890
               sk                          0.476276
               sl                          0.339276
human_original cs                          0.045114
               de                          0.094962
               hr                          0.005950
               hu                          0.094151
               pl                          0.093303
               sk                          0.062281
               sl                          0.051586
original       cs                          0.879129
               de                          0.912066
               hr                          0.602044
               hu                          0.963536
               pl                          0.926451
               sk                          0.834684
               sl                          0.723472
paraphrased    cs                          0.938593
               de                          0.969587
               hr                          0.777738
               hu                          0.982309
               pl                          0.941200
               sk                          0.908582
               sl                          0.849626

                         Hello-SimpleAI-chatgpt-detector-roberta-chinese  \
obfuscator     language
homoglyph      cs                                               0.067505
               de                                               0.250488
               hr                                               0.045898
               hu                                               0.078308
               pl                                               0.026337
               sk                                               0.101868
               sl                                               0.040436
human_original cs                                               0.021942
               de                                               0.277344
               hr                                               0.010170
               hu                                               0.004505
               pl                                               0.008522
               sk                                               0.000792
               sl                                               0.002592
original       cs                                               0.102051
               de                                               0.560547
               hr                                               0.052368
               hu                                               0.107910
               pl                                               0.027435
               sk                                               0.117493
               sl                                               0.039062
paraphrased    cs                                               0.083801
               de                                               0.538574
               hr                                               0.092163
               hu                                               0.140137
               pl                                               0.082092
               sk                                               0.115479
               sl                                               0.035919

                         andreas122001-bloomz-3b-mixed-detector  binoculars  \
obfuscator     language
homoglyph      cs                                      0.232910   -1.187500
               de                                      0.162964   -1.244141
               hr                                      0.170166   -1.229492
               hu                                      0.178467   -1.233398
               pl                                      0.140991   -1.239258
               sk                                      0.198608   -1.176758
               sl                                      0.232422   -1.188477
human_original cs                                      0.250000   -1.128906
               de                                      0.228394   -1.116211
               hr                                      0.199341   -1.126953
               hu                                      0.200195   -1.189453
               pl                                      0.176880   -1.159180
               sk                                      0.206177   -1.120117
               sl                                      0.365234   -1.098633
original       cs                                      0.465820   -0.991211
               de                                      0.487793   -0.948242
               hr                                      0.441162   -1.003906
               hu                                      0.415283   -0.971191
               pl                                      0.366699   -0.960449
               sk                                      0.516602   -1.013672
               sl                                      0.579590   -1.018555
paraphrased    cs                                      0.775391   -1.002930
               de                                      0.741699   -0.958008
               hr                                      0.716797   -1.027344
               hu                                      0.659180   -1.090820
               pl                                      0.721680   -1.016602
               sk                                      0.802734   -1.020508
               sl                                      0.832031   -1.031250

                         fastdetectgpt  llmdeviation  \
obfuscator     language
homoglyph      cs            -3.339844    -12.812500
               de            -4.347656    -14.570312
               hr            -4.023438    -15.468750
               hu            -4.074219    -13.093750
               pl            -4.097656    -13.437500
               sk            -3.505859    -13.156250
               sl            -4.085938    -15.617188
human_original cs            -1.056641    -15.312500
               de            -1.039062    -10.507812
               hr            -1.159180    -14.945312
               hu            -1.269531    -15.554688
               pl            -1.267578    -13.906250
               sk            -1.406250    -12.406250
               sl            -1.416016    -13.328125
original       cs             0.539062     -7.078125
               de             0.939453     -6.191406
               hr             0.374756     -9.351562
               hu             0.744629     -5.445312
               pl             0.670410     -5.855469
               sk             0.038605     -7.507812
               sl            -0.002541    -10.195312
paraphrased    cs             0.138794     -7.121094
               de             0.422363     -5.710938
               hr            -0.244141     -9.195312
               hu            -1.144531     -6.906250
               pl            -0.312012     -6.542969
               sk            -0.296387     -7.316406
               sl            -0.470703    -10.226562

                         nealcly-detection-longformer
obfuscator     language
homoglyph      cs                            0.628906
               de                            0.635254
               hr                            0.580078
               hu                            0.607422
               pl                            0.670410
               sk                            0.633789
               sl                            0.554199
human_original cs                            0.455566
               de                            0.626953
               hr                            0.371094
               hu                            0.426025
               pl                            0.461670
               sk                            0.564453
               sl                            0.350830
original       cs                            0.589844
               de                            0.625977
               hr                            0.476562
               hu                            0.557617
               pl                            0.594727
               sk                            0.526855
               sl                            0.362793
paraphrased    cs                            0.499512
               de                            0.536621
               hr                            0.459961
               hu                            0.458740
               pl                            0.541504
               sk                            0.479980
               sl                            0.344727

In [30]:
results_all = pd.DataFrame()
for dataset in [to_auc_dict(df)]:
 for detector in tqdm(selected):
  temp = pd.DataFrame({'Dataset': "ALL_DATA", 'Detector': detector, 'Language': '{all}', 'AUC ROC': dataset[detector]['auc'], 'TPR @ 5% FPR': dataset[detector]['tpr_5%fpr'], 'Th @ 5% FPR': dataset[detector]['th_5%fpr'], 'Th @ max(TPR-FPR)': dataset[detector]['th_optim']}, index=[0])
  results_all = pd.concat([results_all, temp])
  for test_language,val in dataset[detector].items():
    if (test_language == 'auc') or ('_' in test_language): continue
    temp = pd.DataFrame({'Dataset': test_language, 'Detector': detector, 'Language': test_language, 'AUC ROC': dataset[detector][test_language]['auc'], 'TPR @ 5% FPR': val['tpr_5%fpr']}, index=[0])
    results_all = pd.concat([results_all, temp])
results_all = results_all[results_all['Detector'].isin(selected)]
temp = results_all.pivot_table(['AUC ROC', 'TPR @ 5% FPR'], 'Detector', "Dataset").reorder_levels(axis='columns', order=[1,0]).sort_index(axis='columns')#.sort_index(axis='index', ascending=False)
display(temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False).style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0))
print(temp.sort_values(by=('ALL_DATA','AUC ROC'), ascending=False).style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).to_latex(convert_css=True))

100%|██████████| 10/10 [00:00<00:00, 106.30it/s]

\begin{tabular}{lrrrrrrrrrrrrrrrr}
Dataset & \multicolumn{2}{r}{ALL_DATA} & \multicolumn{2}{r}{cs} & \multicolumn{2}{r}{de} & \multicolumn{2}{r}{hr} & \multicolumn{2}{r}{hu} & \multicolumn{2}{r}{pl} & \multicolumn{2}{r}{sk} & \multicolumn{2}{r}{sl} \\
 & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR \\
Detector &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
is_machine_prob_Llama-3.2-3B & \bfseries 0.9648 & \bfseries 0.8214 & \bfseries 0.9779 & \bfseries 0.8983 & \bfseries 0.9595 & 0.7867 & \bfseries 0.9858 & \bfseries 0.9333 & \bfseries 0.9734 & \bfseries 0.8900 & \bfseries 0.9674 & \bfseries 0.8683 & \bfseries 0.9609 & \bfseries 0.7867 & \bfseries 0.9546 & \bfseries 0.7650 \\
is_machine_prob_gemma-2-2b & 0.9443 & 0.7562 & 0.9679 & 0.8417 & 0.9575 & \bfseries 0.8283 & 0.9534 & 0.8100 & 0.9707 & 0.8633 & 0.9565 & 0.7950 & 0.9507 & 0.7133 & 0.9271 & 0.6383 \\
is_machine_prob_mdeberta-v3-base & 0.9098 & 0.6514 & 0.9390 & 0.7500 & 0.8761 & 0.6150 & 0.9179 & 0.6083 & 0.9300 & 0.7167 & 0.8984 & 0.6183 & 0.9260 & 0.6900 & 0.8801 & 0.5033 \\
is_machine_prob_xlm-roberta-base & 0.8141 & 0.5483 & 0.8598 & 0.6383 & 0.7599 & 0.4700 & 0.8304 & 0.6167 & 0.8643 & 0.6600 & 0.8180 & 0.5483 & 0.7977 & 0.5700 & 0.7662 & 0.4817 \\
andreas122001-bloomz-3b-mixed-detector & 0.6501 & 0.2367 & 0.6475 & 0.2533 & 0.6429 & 0.2017 & 0.6607 & 0.2767 & 0.6514 & 0.2733 & 0.6667 & 0.2317 & 0.6854 & 0.2783 & 0.6117 & 0.1800 \\
Hello-SimpleAI-chatgpt-detector-roberta-chinese & 0.6186 & 0.1357 & 0.5788 & 0.1417 & 0.6383 & 0.1150 & 0.6132 & 0.1967 & 0.6953 & 0.2067 & 0.5981 & 0.1700 & 0.6375 & 0.2600 & 0.6030 & 0.1583 \\
binoculars & 0.5856 & 0.2314 & 0.6176 & 0.2933 & 0.6037 & 0.2850 & 0.5741 & 0.2767 & 0.5761 & 0.2167 & 0.6015 & 0.2533 & 0.5864 & 0.2283 & 0.5645 & 0.2133 \\
llmdeviation & 0.5786 & 0.1017 & 0.6338 & 0.2000 & 0.5485 & 0.1433 & 0.5844 & 0.2717 & 0.5783 & 0.1000 & 0.5786 & 0.1767 & 0.5913 & 0.1450 & 0.5684 & 0.2400 \\
nealcly-detection-longformer & 0.5640 & 0.0452 & 0.5866 & 0.0467 & 0.4703 & 0.0133 & 0.6274 & 0.0967 & 0.5986 & 0.0283 & 0.6094 & 0.0633 & 0.4850 & 0.0517 & 0.5814 & 0.0417 \\
fastdetectgpt & 0.5296 & 0.2293 & 0.5598 & 0.2483 & 0.5482 & 0.2983 & 0.5273 & 0.2633 & 0.4754 & 0.2050 & 0.5306 & 0.2183 & 0.5411 & 0.2050 & 0.5419 & 0.2200 \\
\end{tabular}

In [31]:
results_all = pd.DataFrame()
for obfuscator in df.obfuscator.unique():
 for dataset in [to_auc_dict(df[df.obfuscator.isin([obfuscator, 'human_original'])].reset_index())]:
  for detector in tqdm(selected):
   temp = pd.DataFrame({'Dataset': obfuscator, 'Detector': detector, 'Language': '{all}', 'AUC ROC': dataset[detector]['auc'], 'TPR @ 5% FPR': dataset[detector]['tpr_5%fpr'], 'Th @ 5% FPR': dataset[detector]['th_5%fpr'], 'Th @ max(TPR-FPR)': dataset[detector]['th_optim']}, index=[0])
   results_all = pd.concat([results_all, temp])
   for test_language,val in dataset[detector].items():
     if (test_language == 'auc') or ('_' in test_language): continue
     temp = pd.DataFrame({'Dataset': obfuscator, 'Detector': detector, 'Language': test_language, 'AUC ROC': dataset[detector][test_language]['auc'], 'TPR @ 5% FPR': val['tpr_5%fpr']}, index=[0])
     results_all = pd.concat([results_all, temp])
#results_all = results_all[results_all['Detector'].isin(selected)]
temp = results_all[results_all['Language'] == "{all}"].pivot_table(['AUC ROC', 'TPR @ 5% FPR'], 'Detector', "Dataset").reorder_levels(axis='columns', order=[1,0]).sort_index(axis='columns')#.sort_index(axis='index', ascending=False)
display(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0))
print(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).to_latex(convert_css=True))

c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
c:\Users\User\anaconda3\lib\site-packages\sklearn\metrics\_ranking.py:999: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
100%|██████████| 10/10 [00:00<00:00, 117.65it/s]
100%|██████████| 10/10 [00:00<00:00, 105.64it/s]
100%|██████████| 10/10 [00:00<00:00, 98.23it/s]
100%|██████████| 10/10 [00:00<00:00, 95.08it/s]

\begin{tabular}{lrrrrrrrr}
Dataset & \multicolumn{2}{r}{homoglyph} & \multicolumn{2}{r}{human_original} & \multicolumn{2}{r}{original} & \multicolumn{2}{r}{paraphrased} \\
 & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR & AUC ROC & TPR @ 5% FPR \\
Detector &  &  &  &  &  &  &  &  \\
Hello-SimpleAI-chatgpt-detector-roberta-chinese & 0.5547 & 0.0986 & \bfseries -1.0000 & \bfseries -1.0000 & 0.6497 & 0.1479 & 0.6515 & 0.1607 \\
andreas122001-bloomz-3b-mixed-detector & 0.4240 & 0.0379 & \bfseries -1.0000 & \bfseries -1.0000 & 0.6778 & 0.1657 & 0.8487 & 0.5036 \\
binoculars & 0.2711 & 0.0036 & \bfseries -1.0000 & \bfseries -1.0000 & 0.7758 & 0.4307 & 0.7098 & 0.2600 \\
fastdetectgpt & 0.0815 & 0.0014 & \bfseries -1.0000 & \bfseries -1.0000 & 0.8000 & 0.4400 & 0.7074 & 0.2464 \\
is_machine_prob_Llama-3.2-3B & \bfseries 0.9354 & \bfseries 0.6357 & \bfseries -1.0000 & \bfseries -1.0000 & \bfseries 0.9739 & \bfseries 0.8821 & \bfseries 0.9851 & \bfseries 0.9464 \\
is_machine_prob_gemma-2-2b & 0.8962 & 0.5414 & \bfseries -1.0000 & \bfseries -1.0000 & 0.9588 & 0.8243 & 0.9779 & 0.9029 \\
is_machine_prob_mdeberta-v3-base & 0.7749 & 0.1936 & \bfseries -1.0000 & \bfseries -1.0000 & 0.9720 & 0.8500 & 0.9825 & 0.9107 \\
is_machine_prob_xlm-roberta-base & 0.5218 & 0.0821 & \bfseries -1.0000 & \bfseries -1.0000 & 0.9540 & 0.7529 & 0.9665 & 0.8100 \\
llmdeviation & 0.3614 & 0.0036 & \bfseries -1.0000 & \bfseries -1.0000 & 0.6968 & 0.2071 & 0.6775 & 0.0943 \\
nealcly-detection-longformer & 0.6196 & 0.0179 & \bfseries -1.0000 & \bfseries -1.0000 & 0.5616 & 0.0714 & 0.5107 & 0.0450 \\
\end{tabular}

In [32]:
print(results_all.Detector.unique().tolist())

['is_machine_prob_mdeberta-v3-base', 'is_machine_prob_Llama-3.2-3B', 'is_machine_prob_xlm-roberta-base', 'is_machine_prob_gemma-2-2b', 'Hello-SimpleAI-chatgpt-detector-roberta-chinese', 'andreas122001-bloomz-3b-mixed-detector', 'binoculars', 'fastdetectgpt', 'llmdeviation', 'nealcly-detection-longformer']

In [33]:
rename_adversarial_detector = {'is_machine_prob_Llama-3.2-3B': 'Llama-3.2-3B', 'is_machine_prob_mdeberta-v3-base': 'mDeBERTa-v3-base', 'is_machine_prob_gemma-2-2b': 'Gemma-2-2B', 'is_machine_prob_xlm-roberta-base': 'XLM-RoBERTa-base', 'fastdetectgpt': 'Fast-DetectGPT', 'binoculars': 'Binoculars', 'llmdeviation': 'LLM-Deviation', 'andreas122001-bloomz-3b-mixed-detector': 'BLOOMz-3B-mixed-detector', 'Hello-SimpleAI-chatgpt-detector-roberta-chinese': 'ChatGPT-detector-RoBERTa-Chinese', 'nealcly-detection-longformer': 'Detection-Longformer'}
adversarial_key = {v: k for k, v in dict(enumerate(rename_adversarial_detector.keys())).items()}

In [34]:
temp = results_all[results_all['Dataset'] != "human_original"].pivot_table('AUC ROC', 'Detector', ["Dataset", "Language"]).sort_index(axis='columns')#.sort_index(axis='index', ascending=False)
temp = temp.stack(level=0)
temp.rename(columns={'{all}':'All'}, inplace=True)
temp.sort_index(axis=1, inplace=True)
temp.index = temp.index.set_levels(pd.CategoricalIndex(temp.index.levels[1].values, categories=['original', 'paraphrased', 'homoglyph'], ordered=True), level=1)
temp = temp.sort_index(level=1).sort_index(level=0, key=lambda x: x.map(adversarial_key))
temp = temp.reset_index()
temp['Detector'] = temp['Detector'].map(rename_adversarial_detector)
temp = temp.set_index(['Detector', 'Dataset'])
temp2 = temp.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).apply(lambda x: np.select([temp.eq(temp.groupby('Detector').transform('max'))], ['font-weight: bold;'], default=''), axis=None).highlight_max(props='text-decoration: underline', axis=0).background_gradient(vmin=0.5, vmax=1.5, text_color_threshold=0, axis=None)
display(temp2)
print(temp2.to_latex(convert_css=True).replace('\n\multirow','\n\hline\n\multirow'))

\begin{tabular}{llrrrrrrrr}
 & Language & All & cs & de & hr & hu & pl & sk & sl \\
Detector & Dataset &  &  &  &  &  &  &  &  \\
\hline
\multirow[c]{3}{*}{Llama-3.2-3B} & original & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9739 & {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9787 & {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9717 & {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9881 & {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9825 & {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9808 & {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9703 & {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9654 \\
 & paraphrased & \bfseries \bfseries {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9851 & \bfseries \bfseries {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9921 & \bfseries {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9785 & \bfseries \bfseries {\cellcolor[HTML]{75A9CF}} \color[HTML]{000000} 0.9966 & \bfseries \bfseries {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9869 & \bfseries \bfseries {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9867 & \bfseries {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9845 & \bfseries \bfseries {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9827 \\
 & homoglyph & {\cellcolor[HTML]{8EB3D5}} \color[HTML]{000000} 0.9354 & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9630 & {\cellcolor[HTML]{91B5D6}} \color[HTML]{000000} 0.9282 & {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9726 & {\cellcolor[HTML]{88B1D4}} \color[HTML]{000000} 0.9507 & {\cellcolor[HTML]{8EB3D5}} \color[HTML]{000000} 0.9347 & {\cellcolor[HTML]{91B5D6}} \color[HTML]{000000} 0.9278 & {\cellcolor[HTML]{96B6D7}} \color[HTML]{000000} 0.9157 \\
\hline
\multirow[c]{3}{*}{mDeBERTa-v3-base} & original & {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9720 & {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9769 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9734 & {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9674 & {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9816 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9757 & {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9721 & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9636 \\
 & paraphrased & \bfseries {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9825 & \bfseries {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9881 & \bfseries \bfseries {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9813 & \bfseries {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9782 & \bfseries {\cellcolor[HTML]{79ABD0}} \color[HTML]{000000} 0.9869 & \bfseries {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9828 & \bfseries \bfseries {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9888 & \bfseries {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9744 \\
 & homoglyph & {\cellcolor[HTML]{C8CDE4}} \color[HTML]{000000} 0.7749 & {\cellcolor[HTML]{ADC1DD}} \color[HTML]{000000} 0.8519 & {\cellcolor[HTML]{E1DFED}} \color[HTML]{000000} 0.6736 & {\cellcolor[HTML]{BDC8E1}} \color[HTML]{000000} 0.8080 & {\cellcolor[HTML]{B8C6E0}} \color[HTML]{000000} 0.8215 & {\cellcolor[HTML]{D3D4E7}} \color[HTML]{000000} 0.7367 & {\cellcolor[HTML]{B9C6E0}} \color[HTML]{000000} 0.8170 & {\cellcolor[HTML]{DBDAEB}} \color[HTML]{000000} 0.7024 \\
\hline
\multirow[c]{3}{*}{Gemma-2-2B} & original & {\cellcolor[HTML]{84B0D3}} \color[HTML]{000000} 0.9588 & {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9769 & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9647 & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9634 & {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9783 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9752 & {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9677 & {\cellcolor[HTML]{89B1D4}} \color[HTML]{000000} 0.9484 \\
 & paraphrased & \bfseries {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9779 & \bfseries {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9889 & \bfseries {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9750 & \bfseries {\cellcolor[HTML]{78ABD0}} \color[HTML]{000000} 0.9908 & \bfseries {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9809 & \bfseries {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9826 & \bfseries {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9832 & \bfseries {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9741 \\
 & homoglyph & {\cellcolor[HTML]{9EBAD9}} \color[HTML]{000000} 0.8962 & {\cellcolor[HTML]{8CB3D5}} \color[HTML]{000000} 0.9377 & {\cellcolor[HTML]{8FB4D6}} \color[HTML]{000000} 0.9326 & {\cellcolor[HTML]{9AB8D8}} \color[HTML]{000000} 0.9060 & {\cellcolor[HTML]{88B1D4}} \color[HTML]{000000} 0.9530 & {\cellcolor[HTML]{97B7D7}} \color[HTML]{000000} 0.9115 & {\cellcolor[HTML]{9CB9D9}} \color[HTML]{000000} 0.9011 & {\cellcolor[HTML]{ACC0DD}} \color[HTML]{000000} 0.8589 \\
\hline
\multirow[c]{3}{*}{XLM-RoBERTa-base} & original & {\cellcolor[HTML]{86B0D3}} \color[HTML]{000000} 0.9540 & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9633 & {\cellcolor[HTML]{89B1D4}} \color[HTML]{000000} 0.9474 & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9627 & {\cellcolor[HTML]{7EADD1}} \color[HTML]{000000} 0.9736 & {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9611 & {\cellcolor[HTML]{8BB2D4}} \color[HTML]{000000} 0.9434 & {\cellcolor[HTML]{8FB4D6}} \color[HTML]{000000} 0.9322 \\
 & paraphrased & \bfseries {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9665 & \bfseries {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9769 & \bfseries {\cellcolor[HTML]{86B0D3}} \color[HTML]{000000} 0.9536 & \bfseries {\cellcolor[HTML]{7DACD1}} \color[HTML]{000000} 0.9774 & \bfseries {\cellcolor[HTML]{7BACD1}} \color[HTML]{000000} 0.9805 & \bfseries {\cellcolor[HTML]{83AFD3}} \color[HTML]{000000} 0.9629 & \bfseries {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9687 & \bfseries {\cellcolor[HTML]{86B0D3}} \color[HTML]{000000} 0.9536 \\
 & homoglyph & {\cellcolor[HTML]{FCF4FA}} \color[HTML]{000000} 0.5218 & {\cellcolor[HTML]{E9E5F1}} \color[HTML]{000000} 0.6393 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3788 & {\cellcolor[HTML]{F7F0F7}} \color[HTML]{000000} 0.5510 & {\cellcolor[HTML]{E9E5F1}} \color[HTML]{000000} 0.6389 & {\cellcolor[HTML]{FBF3F9}} \color[HTML]{000000} 0.5300 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4809 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4128 \\
\hline
\multirow[c]{3}{*}{Fast-DetectGPT} & original & \bfseries {\cellcolor[HTML]{C0C9E2}} \color[HTML]{000000} 0.8000 & \bfseries {\cellcolor[HTML]{BFC9E1}} \color[HTML]{000000} 0.8045 & \bfseries {\cellcolor[HTML]{BCC7E1}} \color[HTML]{000000} 0.8122 & \bfseries {\cellcolor[HTML]{BDC8E1}} \color[HTML]{000000} 0.8049 & \bfseries {\cellcolor[HTML]{BBC7E0}} \color[HTML]{000000} 0.8154 & \bfseries {\cellcolor[HTML]{BCC7E1}} \color[HTML]{000000} 0.8096 & \bfseries {\cellcolor[HTML]{CACEE5}} \color[HTML]{000000} 0.7658 & \bfseries {\cellcolor[HTML]{BCC7E1}} \color[HTML]{000000} 0.8112 \\
 & paraphrased & {\cellcolor[HTML]{D9D8EA}} \color[HTML]{000000} 0.7074 & {\cellcolor[HTML]{CACEE5}} \color[HTML]{000000} 0.7657 & {\cellcolor[HTML]{C2CBE2}} \color[HTML]{000000} 0.7921 & {\cellcolor[HTML]{D6D6E9}} \color[HTML]{000000} 0.7229 & {\cellcolor[HTML]{FBF3F9}} \color[HTML]{000000} 0.5298 & {\cellcolor[HTML]{DCDAEB}} \color[HTML]{000000} 0.6965 & {\cellcolor[HTML]{D4D4E8}} \color[HTML]{000000} 0.7343 & {\cellcolor[HTML]{D2D3E7}} \color[HTML]{000000} 0.7394 \\
 & homoglyph & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0815 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1093 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0403 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0542 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0808 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0857 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1232 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0750 \\
\hline
\multirow[c]{3}{*}{Binoculars} & original & \bfseries {\cellcolor[HTML]{C8CDE4}} \color[HTML]{000000} 0.7758 & \bfseries {\cellcolor[HTML]{C2CBE2}} \color[HTML]{000000} 0.7894 & \bfseries {\cellcolor[HTML]{C2CBE2}} \color[HTML]{000000} 0.7917 & \bfseries {\cellcolor[HTML]{C8CDE4}} \color[HTML]{000000} 0.7737 & \bfseries {\cellcolor[HTML]{BDC8E1}} \color[HTML]{000000} 0.8080 & \bfseries {\cellcolor[HTML]{C0C9E2}} \color[HTML]{000000} 0.7993 & \bfseries {\cellcolor[HTML]{D3D4E7}} \color[HTML]{000000} 0.7376 & \bfseries {\cellcolor[HTML]{CDD0E5}} \color[HTML]{000000} 0.7601 \\
 & paraphrased & {\cellcolor[HTML]{D9D8EA}} \color[HTML]{000000} 0.7098 & {\cellcolor[HTML]{CACEE5}} \color[HTML]{000000} 0.7683 & {\cellcolor[HTML]{C4CBE3}} \color[HTML]{000000} 0.7855 & {\cellcolor[HTML]{D8D7E9}} \color[HTML]{000000} 0.7171 & {\cellcolor[HTML]{F1EBF4}} \color[HTML]{000000} 0.5951 & {\cellcolor[HTML]{D7D6E9}} \color[HTML]{000000} 0.7188 & {\cellcolor[HTML]{D7D6E9}} \color[HTML]{000000} 0.7219 & {\cellcolor[HTML]{D9D8EA}} \color[HTML]{000000} 0.7121 \\
 & homoglyph & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2711 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2951 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2338 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2313 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3252 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2866 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2996 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2214 \\
\hline
\multirow[c]{3}{*}{LLM-Deviation} & original & \bfseries {\cellcolor[HTML]{DCDAEB}} \color[HTML]{000000} 0.6968 & \bfseries {\cellcolor[HTML]{D1D2E6}} \color[HTML]{000000} 0.7473 & {\cellcolor[HTML]{DCDAEB}} \color[HTML]{000000} 0.6958 & \bfseries {\cellcolor[HTML]{DBDAEB}} \color[HTML]{000000} 0.7030 & \bfseries {\cellcolor[HTML]{D5D5E8}} \color[HTML]{000000} 0.7288 & \bfseries {\cellcolor[HTML]{D7D6E9}} \color[HTML]{000000} 0.7208 & {\cellcolor[HTML]{D9D8EA}} \color[HTML]{000000} 0.7114 & \bfseries {\cellcolor[HTML]{DAD9EA}} \color[HTML]{000000} 0.7035 \\
 & paraphrased & {\cellcolor[HTML]{E0DEED}} \color[HTML]{000000} 0.6775 & {\cellcolor[HTML]{D4D4E8}} \color[HTML]{000000} 0.7322 & \bfseries {\cellcolor[HTML]{DAD9EA}} \color[HTML]{000000} 0.7044 & {\cellcolor[HTML]{DCDAEB}} \color[HTML]{000000} 0.6964 & {\cellcolor[HTML]{F0EAF4}} \color[HTML]{000000} 0.5978 & {\cellcolor[HTML]{E4E1EF}} \color[HTML]{000000} 0.6622 & \bfseries {\cellcolor[HTML]{D8D7E9}} \color[HTML]{000000} 0.7158 & {\cellcolor[HTML]{DEDCEC}} \color[HTML]{000000} 0.6881 \\
 & homoglyph & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3614 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4219 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2454 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3539 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4082 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3527 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3466 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3136 \\
\hline
\multirow[c]{3}{*}{BLOOMz-3B-mixed-detector} & original & {\cellcolor[HTML]{E0DEED}} \color[HTML]{000000} 0.6778 & {\cellcolor[HTML]{E5E1EF}} \color[HTML]{000000} 0.6565 & {\cellcolor[HTML]{E2DFEE}} \color[HTML]{000000} 0.6707 & {\cellcolor[HTML]{DBDAEB}} \color[HTML]{000000} 0.7015 & {\cellcolor[HTML]{DDDBEC}} \color[HTML]{000000} 0.6923 & {\cellcolor[HTML]{DEDCEC}} \color[HTML]{000000} 0.6879 & {\cellcolor[HTML]{D9D8EA}} \color[HTML]{000000} 0.7095 & {\cellcolor[HTML]{E7E3F0}} \color[HTML]{000000} 0.6450 \\
 & paraphrased & \bfseries {\cellcolor[HTML]{AFC1DD}} \color[HTML]{000000} 0.8487 & \bfseries {\cellcolor[HTML]{ADC1DD}} \color[HTML]{000000} 0.8526 & \bfseries {\cellcolor[HTML]{B3C3DE}} \color[HTML]{000000} 0.8379 & \bfseries {\cellcolor[HTML]{ADC1DD}} \color[HTML]{000000} 0.8527 & \bfseries {\cellcolor[HTML]{B4C4DF}} \color[HTML]{000000} 0.8337 & \bfseries {\cellcolor[HTML]{A5BDDB}} \color[HTML]{000000} 0.8754 & \bfseries {\cellcolor[HTML]{A1BBDA}} \color[HTML]{000000} 0.8904 & \bfseries {\cellcolor[HTML]{B7C5DF}} \color[HTML]{000000} 0.8275 \\
 & homoglyph & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4240 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4333 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4203 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4280 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4281 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4369 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4562 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3627 \\
\hline
\multirow[c]{3}{*}{ChatGPT-detector-RoBERTa-Chinese} & original & {\cellcolor[HTML]{E7E3F0}} \color[HTML]{000000} 0.6497 & \bfseries {\cellcolor[HTML]{EDE7F2}} \color[HTML]{000000} 0.6228 & \bfseries {\cellcolor[HTML]{DDDBEC}} \color[HTML]{000000} 0.6915 & {\cellcolor[HTML]{E7E3F0}} \color[HTML]{000000} 0.6473 & {\cellcolor[HTML]{D6D6E9}} \color[HTML]{000000} 0.7228 & \bfseries {\cellcolor[HTML]{EBE6F2}} \color[HTML]{000000} 0.6294 & {\cellcolor[HTML]{E3E0EE}} \color[HTML]{000000} 0.6655 & \bfseries {\cellcolor[HTML]{E0DEED}} \color[HTML]{000000} 0.6769 \\
 & paraphrased & \bfseries {\cellcolor[HTML]{E7E3F0}} \color[HTML]{000000} 0.6515 & {\cellcolor[HTML]{F0EAF4}} \color[HTML]{000000} 0.6008 & {\cellcolor[HTML]{E0DDED}} \color[HTML]{000000} 0.6829 & \bfseries {\cellcolor[HTML]{E1DFED}} \color[HTML]{000000} 0.6741 & \bfseries {\cellcolor[HTML]{D2D3E7}} \color[HTML]{000000} 0.7408 & {\cellcolor[HTML]{EDE8F3}} \color[HTML]{000000} 0.6196 & \bfseries {\cellcolor[HTML]{DCDAEB}} \color[HTML]{000000} 0.6955 & {\cellcolor[HTML]{ECE7F2}} \color[HTML]{000000} 0.6278 \\
 & homoglyph & {\cellcolor[HTML]{F7F0F7}} \color[HTML]{000000} 0.5547 & {\cellcolor[HTML]{FDF5FA}} \color[HTML]{000000} 0.5127 & {\cellcolor[HTML]{F9F2F8}} \color[HTML]{000000} 0.5404 & {\cellcolor[HTML]{FDF5FA}} \color[HTML]{000000} 0.5184 & {\cellcolor[HTML]{EDE7F2}} \color[HTML]{000000} 0.6221 & {\cellcolor[HTML]{F8F1F8}} \color[HTML]{000000} 0.5453 & {\cellcolor[HTML]{F7F0F7}} \color[HTML]{000000} 0.5516 & {\cellcolor[HTML]{FEF6FB}} \color[HTML]{000000} 0.5045 \\
\hline
\multirow[c]{3}{*}{Detection-Longformer} & original & {\cellcolor[HTML]{F6EFF7}} \color[HTML]{000000} 0.5616 & {\cellcolor[HTML]{F0EAF4}} \color[HTML]{000000} 0.6032 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.5010 & {\cellcolor[HTML]{EFE9F3}} \color[HTML]{000000} 0.6065 & {\cellcolor[HTML]{EDE8F3}} \color[HTML]{000000} 0.6179 & {\cellcolor[HTML]{EEE9F3}} \color[HTML]{000000} 0.6097 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4760 & {\cellcolor[HTML]{F9F2F8}} \color[HTML]{000000} 0.5391 \\
 & paraphrased & {\cellcolor[HTML]{FEF6FA}} \color[HTML]{000000} 0.5107 & {\cellcolor[HTML]{FBF4F9}} \color[HTML]{000000} 0.5247 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4216 & {\cellcolor[HTML]{F2ECF5}} \color[HTML]{000000} 0.5887 & {\cellcolor[HTML]{FBF3F9}} \color[HTML]{000000} 0.5287 & {\cellcolor[HTML]{F5EEF6}} \color[HTML]{000000} 0.5683 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4253 & {\cellcolor[HTML]{FBF4F9}} \color[HTML]{000000} 0.5246 \\
 & homoglyph & \bfseries {\cellcolor[HTML]{EDE8F3}} \color[HTML]{000000} 0.6196 & \bfseries {\cellcolor[HTML]{EBE6F2}} \color[HTML]{000000} 0.6319 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4883 & \bfseries {\cellcolor[HTML]{DFDDEC}} \color[HTML]{000000} 0.6870 & \bfseries {\cellcolor[HTML]{E7E3F0}} \color[HTML]{000000} 0.6492 & \bfseries {\cellcolor[HTML]{E7E3F0}} \color[HTML]{000000} 0.6504 & \bfseries {\cellcolor[HTML]{F7F0F7}} \color[HTML]{000000} 0.5537 & \bfseries {\cellcolor[HTML]{E0DDED}} \color[HTML]{000000} 0.6804 \\
\end{tabular}

In [35]:
from  matplotlib.colors import LinearSegmentedColormap
attack_cmap=LinearSegmentedColormap.from_list('rg',["r", "w"], N=256)

In [36]:
temp = results_all[results_all['Dataset'] != "human_original"].pivot_table('AUC ROC', 'Detector', ["Dataset", "Language"]).sort_index(axis='columns')#.sort_index(axis='index', ascending=False)
temp2 = (temp - temp['original']) / temp['original'] * 100

temp2 = temp2.drop(columns='original').stack(level=0)
temp2.rename(columns={'{all}':'All'}, inplace=True)
temp2.sort_index(axis=1, inplace=True)
temp2.index = temp2.index.set_levels(pd.CategoricalIndex(temp2.index.levels[1].values, categories=['original', 'paraphrased', 'homoglyph'], ordered=True), level=1)
temp2 = temp2.sort_index(level=1).sort_index(level=0, key=lambda x: x.map(adversarial_key))
temp2 = temp2.reset_index()
temp2['Detector'] = temp2['Detector'].map(rename_adversarial_detector)
temp2 = temp2.set_index(['Detector', 'Dataset'])
temp3 = temp2.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).apply(lambda x: np.select([temp2.eq(temp2.groupby('Detector').transform('max'))], ['font-weight: bold;'], default=''), axis=None).highlight_max(props='text-decoration: underline', axis=0).background_gradient(cmap="OrRd_r", vmin=-150, vmax=0, text_color_threshold=0, axis=None)#.background_gradient(cmap="Greens", vmin=0, vmax=150, text_color_threshold=0, axis=None)
display(temp3)
print(temp3.to_latex(convert_css=True).replace('\n\multirow','\n\hline\n\multirow'))

\begin{tabular}{llrrrrrrrr}
 & Language & All & cs & de & hr & hu & pl & sk & sl \\
Detector & Dataset &  &  &  &  &  &  &  &  \\
\hline
\multirow[c]{2}{*}{Llama-3.2-3B} & paraphrased & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.1478 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.3756 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.6972 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.8615 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.4465 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.5965 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.4596 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.7855 \\
 & homoglyph & {\cellcolor[HTML]{FFF4E5}} \color[HTML]{000000} -3.9598 & {\cellcolor[HTML]{FFF6EA}} \color[HTML]{000000} -1.6017 & {\cellcolor[HTML]{FFF4E4}} \color[HTML]{000000} -4.4729 & {\cellcolor[HTML]{FFF6EA}} \color[HTML]{000000} -1.5661 & {\cellcolor[HTML]{FFF5E6}} \color[HTML]{000000} -3.2416 & {\cellcolor[HTML]{FFF3E3}} \color[HTML]{000000} -4.6977 & {\cellcolor[HTML]{FFF4E4}} \color[HTML]{000000} -4.3851 & {\cellcolor[HTML]{FFF3E3}} \color[HTML]{000000} -5.1506 \\
\hline
\multirow[c]{2}{*}{mDeBERTa-v3-base} & paraphrased & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.0807 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.1490 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.8103 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.1151 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.5387 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.7277 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.7101 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.1182 \\
 & homoglyph & {\cellcolor[HTML]{FEE7C5}} \color[HTML]{000000} -20.2776 & {\cellcolor[HTML]{FEEDD4}} \color[HTML]{000000} -12.8004 & {\cellcolor[HTML]{FDDBAD}} \color[HTML]{000000} -30.8013 & {\cellcolor[HTML]{FEEACC}} \color[HTML]{000000} -16.4754 & {\cellcolor[HTML]{FEEACE}} \color[HTML]{000000} -16.3152 & {\cellcolor[HTML]{FEE2BC}} \color[HTML]{000000} -24.4904 & {\cellcolor[HTML]{FEEACE}} \color[HTML]{000000} -15.9545 & {\cellcolor[HTML]{FEDFB5}} \color[HTML]{000000} -27.1115 \\
\hline
\multirow[c]{2}{*}{Gemma-2-2B} & paraphrased & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.9915 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.2283 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.0638 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 2.8481 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.2619 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.7575 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.6004 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 2.7112 \\
 & homoglyph & {\cellcolor[HTML]{FFF2E0}} \color[HTML]{000000} -6.5255 & {\cellcolor[HTML]{FFF4E5}} \color[HTML]{000000} -4.0138 & {\cellcolor[HTML]{FFF5E6}} \color[HTML]{000000} -3.3260 & {\cellcolor[HTML]{FFF2E1}} \color[HTML]{000000} -5.9583 & {\cellcolor[HTML]{FFF5E7}} \color[HTML]{000000} -2.5900 & {\cellcolor[HTML]{FFF2E0}} \color[HTML]{000000} -6.5343 & {\cellcolor[HTML]{FFF2E0}} \color[HTML]{000000} -6.8872 & {\cellcolor[HTML]{FEEFDA}} \color[HTML]{000000} -9.4358 \\
\hline
\multirow[c]{2}{*}{XLM-RoBERTa-base} & paraphrased & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.3034 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.4131 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.6518 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.5217 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.7100 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.1951 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 2.6804 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 2.2970 \\
 & homoglyph & {\cellcolor[HTML]{FDCA93}} \color[HTML]{000000} -45.3002 & {\cellcolor[HTML]{FDD8A7}} \color[HTML]{000000} -33.6366 & {\cellcolor[HTML]{FDB27B}} \color[HTML]{000000} -60.0206 & {\cellcolor[HTML]{FDCE97}} \color[HTML]{000000} -42.7661 & {\cellcolor[HTML]{FDD8A6}} \color[HTML]{000000} -34.3776 & {\cellcolor[HTML]{FDCA94}} \color[HTML]{000000} -44.8501 & {\cellcolor[HTML]{FDC58E}} \color[HTML]{000000} -49.0268 & {\cellcolor[HTML]{FDBB85}} \color[HTML]{000000} -55.7142 \\
\hline
\multirow[c]{2}{*}{Fast-DetectGPT} & paraphrased & \bfseries {\cellcolor[HTML]{FEEED7}} \color[HTML]{000000} -11.5706 & \bfseries {\cellcolor[HTML]{FFF3E3}} \color[HTML]{000000} -4.8167 & \bfseries {\cellcolor[HTML]{FFF5E7}} \color[HTML]{000000} -2.4718 & \bfseries {\cellcolor[HTML]{FEEFD9}} \color[HTML]{000000} -10.1836 & \bfseries {\cellcolor[HTML]{FDD7A4}} \color[HTML]{000000} -35.0241 & \bfseries {\cellcolor[HTML]{FEECD2}} \color[HTML]{000000} -13.9639 & \bfseries {\cellcolor[HTML]{FFF4E4}} \color[HTML]{000000} -4.1148 & \bfseries {\cellcolor[HTML]{FFF0DB}} \color[HTML]{000000} -8.8522 \\
 & homoglyph & {\cellcolor[HTML]{F26D4B}} \color[HTML]{000000} -89.8062 & {\cellcolor[HTML]{F4754F}} \color[HTML]{000000} -86.4184 & {\cellcolor[HTML]{ED6145}} \color[HTML]{000000} -95.0409 & {\cellcolor[HTML]{EF6548}} \color[HTML]{000000} -93.2612 & {\cellcolor[HTML]{F26D4B}} \color[HTML]{000000} -90.0897 & {\cellcolor[HTML]{F26E4C}} \color[HTML]{000000} -89.4144 & {\cellcolor[HTML]{F67A51}} \color[HTML]{000000} -83.9193 & {\cellcolor[HTML]{F16C4B}} \color[HTML]{000000} -90.7533 \\
\hline
\multirow[c]{2}{*}{Binoculars} & paraphrased & \bfseries {\cellcolor[HTML]{FFF0DC}} \color[HTML]{000000} -8.5022 & \bfseries {\cellcolor[HTML]{FFF5E7}} \color[HTML]{000000} -2.6775 & \bfseries {\cellcolor[HTML]{FFF7EB}} \color[HTML]{000000} -0.7753 & \bfseries {\cellcolor[HTML]{FFF1DE}} \color[HTML]{000000} -7.3183 & \bfseries {\cellcolor[HTML]{FEE0B8}} \color[HTML]{000000} -26.3440 & \bfseries {\cellcolor[HTML]{FEEFD9}} \color[HTML]{000000} -10.0776 & \bfseries {\cellcolor[HTML]{FFF6E9}} \color[HTML]{000000} -2.1252 & \bfseries {\cellcolor[HTML]{FFF2E1}} \color[HTML]{000000} -6.3132 \\
 & homoglyph & {\cellcolor[HTML]{FDA56F}} \color[HTML]{000000} -65.0519 & {\cellcolor[HTML]{FDAC76}} \color[HTML]{000000} -62.6195 & {\cellcolor[HTML]{FC9863}} \color[HTML]{000000} -70.4672 & {\cellcolor[HTML]{FC9964}} \color[HTML]{000000} -70.1066 & {\cellcolor[HTML]{FDB37D}} \color[HTML]{000000} -59.7577 & {\cellcolor[HTML]{FDA872}} \color[HTML]{000000} -64.1452 & {\cellcolor[HTML]{FDB37D}} \color[HTML]{000000} -59.3729 & {\cellcolor[HTML]{FC9863}} \color[HTML]{000000} -70.8711 \\
\hline
\multirow[c]{2}{*}{LLM-Deviation} & paraphrased & \bfseries {\cellcolor[HTML]{FFF5E7}} \color[HTML]{000000} -2.7774 & \bfseries {\cellcolor[HTML]{FFF6E9}} \color[HTML]{000000} -2.0273 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.2324 & \bfseries {\cellcolor[HTML]{FFF7EB}} \color[HTML]{000000} -0.9388 & \bfseries {\cellcolor[HTML]{FEE9CA}} \color[HTML]{000000} -17.9738 & \bfseries {\cellcolor[HTML]{FFF1DD}} \color[HTML]{000000} -8.1312 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.6255 & \bfseries {\cellcolor[HTML]{FFF6E9}} \color[HTML]{000000} -2.1857 \\
 & homoglyph & {\cellcolor[HTML]{FDC68F}} \color[HTML]{000000} -48.1313 & {\cellcolor[HTML]{FDCC96}} \color[HTML]{000000} -43.5384 & {\cellcolor[HTML]{FDA671}} \color[HTML]{000000} -64.7306 & {\cellcolor[HTML]{FDC48D}} \color[HTML]{000000} -49.6675 & {\cellcolor[HTML]{FDCB95}} \color[HTML]{000000} -43.9930 & {\cellcolor[HTML]{FDC28B}} \color[HTML]{000000} -51.0777 & {\cellcolor[HTML]{FDC28B}} \color[HTML]{000000} -51.2818 & {\cellcolor[HTML]{FDBC85}} \color[HTML]{000000} -55.4268 \\
\hline
\multirow[c]{2}{*}{BLOOMz-3B-mixed-detector} & paraphrased & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 25.2145 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 29.8580 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 24.9264 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 21.5639 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 20.4258 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 27.2610 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 25.5008 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 28.2813 \\
 & homoglyph & {\cellcolor[HTML]{FDD49F}} \color[HTML]{000000} -37.4430 & {\cellcolor[HTML]{FDD8A6}} \color[HTML]{000000} -33.9972 & {\cellcolor[HTML]{FDD49F}} \color[HTML]{000000} -37.3355 & {\cellcolor[HTML]{FDD29C}} \color[HTML]{000000} -38.9864 & {\cellcolor[HTML]{FDD39D}} \color[HTML]{000000} -38.1557 & {\cellcolor[HTML]{FDD5A0}} \color[HTML]{000000} -36.4922 & {\cellcolor[HTML]{FDD6A3}} \color[HTML]{000000} -35.7036 & {\cellcolor[HTML]{FDCC96}} \color[HTML]{000000} -43.7688 \\
\hline
\multirow[c]{2}{*}{ChatGPT-detector-RoBERTa-Chinese} & paraphrased & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.2833 & \bfseries {\cellcolor[HTML]{FFF4E5}} \color[HTML]{000000} -3.5264 & \bfseries {\cellcolor[HTML]{FFF6EA}} \color[HTML]{000000} -1.2455 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 4.1424 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 2.4885 & \bfseries {\cellcolor[HTML]{FFF6EA}} \color[HTML]{000000} -1.5669 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 4.5022 & \bfseries {\cellcolor[HTML]{FFF1DE}} \color[HTML]{000000} -7.2485 \\
 & homoglyph & {\cellcolor[HTML]{FEECD1}} \color[HTML]{000000} -14.6194 & {\cellcolor[HTML]{FEE9CA}} \color[HTML]{000000} -17.6742 & {\cellcolor[HTML]{FEE5C1}} \color[HTML]{000000} -21.8579 & {\cellcolor[HTML]{FEE7C7}} \color[HTML]{000000} -19.9088 & {\cellcolor[HTML]{FEECD2}} \color[HTML]{000000} -13.9314 & {\cellcolor[HTML]{FEEDD3}} \color[HTML]{000000} -13.3594 & {\cellcolor[HTML]{FEE9CB}} \color[HTML]{000000} -17.1165 & {\cellcolor[HTML]{FEE1B9}} \color[HTML]{000000} -25.4668 \\
\hline
\multirow[c]{2}{*}{Detection-Longformer} & paraphrased & {\cellcolor[HTML]{FFF0DB}} \color[HTML]{000000} -9.0621 & {\cellcolor[HTML]{FEEDD3}} \color[HTML]{000000} -13.0217 & {\cellcolor[HTML]{FEEACE}} \color[HTML]{000000} -15.8487 & {\cellcolor[HTML]{FFF5E6}} \color[HTML]{000000} -2.9369 & {\cellcolor[HTML]{FEECD1}} \color[HTML]{000000} -14.4351 & {\cellcolor[HTML]{FFF2E0}} \color[HTML]{000000} -6.7924 & {\cellcolor[HTML]{FEEFD8}} \color[HTML]{000000} -10.6439 & {\cellcolor[HTML]{FFF5E7}} \color[HTML]{000000} -2.6852 \\
 & homoglyph & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 10.3109 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 4.7557 & \bfseries {\cellcolor[HTML]{FFF5E7}} \color[HTML]{000000} -2.5400 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 13.2644 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 5.0531 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 6.6735 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 16.3349 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 26.2238 \\
\end{tabular}

In [37]:
temp = results_all[results_all['Dataset'] != "human_original"].pivot_table('TPR @ 5% FPR', 'Detector', ["Dataset", "Language"]).sort_index(axis='columns')#.sort_index(axis='index', ascending=False)
temp = temp.stack(level=0)
temp.rename(columns={'{all}':'All'}, inplace=True)
temp.sort_index(axis=1, inplace=True)
temp.index = temp.index.set_levels(pd.CategoricalIndex(temp.index.levels[1].values, categories=['original', 'paraphrased', 'homoglyph'], ordered=True), level=1)
temp = temp.sort_index(level=1).sort_index(level=0, key=lambda x: x.map(adversarial_key))
temp = temp.reset_index()
temp['Detector'] = temp['Detector'].map(rename_adversarial_detector)
temp = temp.set_index(['Detector', 'Dataset'])
temp2 = temp.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).apply(lambda x: np.select([temp.eq(temp.groupby('Detector').transform('max'))], ['font-weight: bold;'], default=''), axis=None).highlight_max(props='text-decoration: underline', axis=0).background_gradient(vmin=0.5, vmax=1.5, text_color_threshold=0, axis=None)
display(temp2)
print(temp2.to_latex(convert_css=True).replace('\n\multirow','\n\hline\n\multirow'))

\begin{tabular}{llrrrrrrrr}
 & Language & All & cs & de & hr & hu & pl & sk & sl \\
Detector & Dataset &  &  &  &  &  &  &  &  \\
\hline
\multirow[c]{3}{*}{Llama-3.2-3B} & original & {\cellcolor[HTML]{A4BCDA}} \color[HTML]{000000} 0.8821 & {\cellcolor[HTML]{94B6D7}} \color[HTML]{000000} 0.9200 & {\cellcolor[HTML]{A2BCDA}} \color[HTML]{000000} 0.8850 & {\cellcolor[HTML]{86B0D3}} \color[HTML]{000000} 0.9550 & {\cellcolor[HTML]{88B1D4}} \color[HTML]{000000} 0.9500 & {\cellcolor[HTML]{8FB4D6}} \color[HTML]{000000} 0.9300 & {\cellcolor[HTML]{B4C4DF}} \color[HTML]{000000} 0.8350 & {\cellcolor[HTML]{B1C2DE}} \color[HTML]{000000} 0.8400 \\
 & paraphrased & \bfseries \bfseries {\cellcolor[HTML]{89B1D4}} \color[HTML]{000000} 0.9464 & \bfseries \bfseries {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9700 & \bfseries {\cellcolor[HTML]{8CB3D5}} \color[HTML]{000000} 0.9400 & \bfseries \bfseries {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9700 & \bfseries \bfseries {\cellcolor[HTML]{80AED2}} \color[HTML]{000000} 0.9700 & \bfseries \bfseries {\cellcolor[HTML]{86B0D3}} \color[HTML]{000000} 0.9550 & \bfseries {\cellcolor[HTML]{8CB3D5}} \color[HTML]{000000} 0.9400 & \bfseries \bfseries {\cellcolor[HTML]{94B6D7}} \color[HTML]{000000} 0.9200 \\
 & homoglyph & {\cellcolor[HTML]{EAE6F1}} \color[HTML]{000000} 0.6357 & {\cellcolor[HTML]{BDC8E1}} \color[HTML]{000000} 0.8050 & {\cellcolor[HTML]{FAF3F9}} \color[HTML]{000000} 0.5350 & {\cellcolor[HTML]{A5BDDB}} \color[HTML]{000000} 0.8750 & {\cellcolor[HTML]{D0D1E6}} \color[HTML]{000000} 0.7500 & {\cellcolor[HTML]{D7D6E9}} \color[HTML]{000000} 0.7200 & {\cellcolor[HTML]{F2ECF5}} \color[HTML]{000000} 0.5850 & {\cellcolor[HTML]{FAF3F9}} \color[HTML]{000000} 0.5350 \\
\hline
\multirow[c]{3}{*}{mDeBERTa-v3-base} & original & {\cellcolor[HTML]{AFC1DD}} \color[HTML]{000000} 0.8500 & {\cellcolor[HTML]{99B8D8}} \color[HTML]{000000} 0.9100 & {\cellcolor[HTML]{B1C2DE}} \color[HTML]{000000} 0.8400 & {\cellcolor[HTML]{CDD0E5}} \color[HTML]{000000} 0.7600 & {\cellcolor[HTML]{8BB2D4}} \color[HTML]{000000} 0.9450 & {\cellcolor[HTML]{B5C4DF}} \color[HTML]{000000} 0.8300 & {\cellcolor[HTML]{ADC1DD}} \color[HTML]{000000} 0.8550 & {\cellcolor[HTML]{DBDAEB}} \color[HTML]{000000} 0.7000 \\
 & paraphrased & \bfseries {\cellcolor[HTML]{97B7D7}} \color[HTML]{000000} 0.9107 & \bfseries {\cellcolor[HTML]{84B0D3}} \color[HTML]{000000} 0.9600 & \bfseries {\cellcolor[HTML]{9CB9D9}} \color[HTML]{000000} 0.9000 & \bfseries {\cellcolor[HTML]{A8BEDC}} \color[HTML]{000000} 0.8700 & \bfseries {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9650 & \bfseries {\cellcolor[HTML]{A2BCDA}} \color[HTML]{000000} 0.8850 & \bfseries \bfseries {\cellcolor[HTML]{86B0D3}} \color[HTML]{000000} 0.9550 & \bfseries {\cellcolor[HTML]{C6CCE3}} \color[HTML]{000000} 0.7800 \\
 & homoglyph & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1936 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3800 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1050 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1950 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2400 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1400 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2600 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0300 \\
\hline
\multirow[c]{3}{*}{Gemma-2-2B} & original & {\cellcolor[HTML]{B7C5DF}} \color[HTML]{000000} 0.8243 & {\cellcolor[HTML]{9EBAD9}} \color[HTML]{000000} 0.8950 & {\cellcolor[HTML]{A4BCDA}} \color[HTML]{000000} 0.8800 & {\cellcolor[HTML]{ABBFDC}} \color[HTML]{000000} 0.8600 & {\cellcolor[HTML]{8FB4D6}} \color[HTML]{000000} 0.9300 & \bfseries {\cellcolor[HTML]{99B8D8}} \color[HTML]{000000} 0.9100 & {\cellcolor[HTML]{BBC7E0}} \color[HTML]{000000} 0.8150 & {\cellcolor[HTML]{D5D5E8}} \color[HTML]{000000} 0.7300 \\
 & paraphrased & \bfseries {\cellcolor[HTML]{9AB8D8}} \color[HTML]{000000} 0.9029 & \bfseries {\cellcolor[HTML]{84B0D3}} \color[HTML]{000000} 0.9600 & \bfseries \bfseries {\cellcolor[HTML]{8BB2D4}} \color[HTML]{000000} 0.9450 & \bfseries {\cellcolor[HTML]{88B1D4}} \color[HTML]{000000} 0.9500 & \bfseries {\cellcolor[HTML]{81AED2}} \color[HTML]{000000} 0.9650 & \bfseries {\cellcolor[HTML]{99B8D8}} \color[HTML]{000000} 0.9100 & \bfseries {\cellcolor[HTML]{9CB9D9}} \color[HTML]{000000} 0.9000 & \bfseries {\cellcolor[HTML]{B0C2DE}} \color[HTML]{000000} 0.8450 \\
 & homoglyph & {\cellcolor[HTML]{F9F2F8}} \color[HTML]{000000} 0.5414 & {\cellcolor[HTML]{E2DFEE}} \color[HTML]{000000} 0.6700 & {\cellcolor[HTML]{E5E1EF}} \color[HTML]{000000} 0.6600 & {\cellcolor[HTML]{EDE8F3}} \color[HTML]{000000} 0.6200 & {\cellcolor[HTML]{DDDBEC}} \color[HTML]{000000} 0.6950 & {\cellcolor[HTML]{F5EFF6}} \color[HTML]{000000} 0.5650 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4250 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3400 \\
\hline
\multirow[c]{3}{*}{XLM-RoBERTa-base} & original & {\cellcolor[HTML]{D0D1E6}} \color[HTML]{000000} 0.7529 & {\cellcolor[HTML]{ADC1DD}} \color[HTML]{000000} 0.8550 & {\cellcolor[HTML]{E1DFED}} \color[HTML]{000000} 0.6750 & {\cellcolor[HTML]{AFC1DD}} \color[HTML]{000000} 0.8500 & {\cellcolor[HTML]{A4BCDA}} \color[HTML]{000000} 0.8800 & {\cellcolor[HTML]{C9CEE4}} \color[HTML]{000000} 0.7700 & {\cellcolor[HTML]{C6CCE3}} \color[HTML]{000000} 0.7800 & {\cellcolor[HTML]{E3E0EE}} \color[HTML]{000000} 0.6650 \\
 & paraphrased & \bfseries {\cellcolor[HTML]{BCC7E1}} \color[HTML]{000000} 0.8100 & \bfseries {\cellcolor[HTML]{A2BCDA}} \color[HTML]{000000} 0.8850 & \bfseries {\cellcolor[HTML]{D9D8EA}} \color[HTML]{000000} 0.7100 & \bfseries {\cellcolor[HTML]{A1BBDA}} \color[HTML]{000000} 0.8900 & \bfseries {\cellcolor[HTML]{8EB3D5}} \color[HTML]{000000} 0.9350 & \bfseries {\cellcolor[HTML]{C1CAE2}} \color[HTML]{000000} 0.7950 & \bfseries {\cellcolor[HTML]{A9BFDC}} \color[HTML]{000000} 0.8650 & \bfseries {\cellcolor[HTML]{D6D6E9}} \color[HTML]{000000} 0.7250 \\
 & homoglyph & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0821 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1750 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0250 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1100 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1650 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0800 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0650 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0550 \\
\hline
\multirow[c]{3}{*}{Fast-DetectGPT} & original & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4400 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4550 & \bfseries {\cellcolor[HTML]{FAF3F9}} \color[HTML]{000000} 0.5350 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4900 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4850 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4600 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3450 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4000 \\
 & paraphrased & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2464 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2900 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3600 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2950 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1300 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1900 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2650 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2550 \\
 & homoglyph & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0014 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0000 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0000 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0050 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0000 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0050 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0050 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0050 \\
\hline
\multirow[c]{3}{*}{Binoculars} & original & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4307 & \bfseries {\cellcolor[HTML]{FDF5FA}} \color[HTML]{000000} 0.5150 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4950 & \bfseries {\cellcolor[HTML]{FDF5FA}} \color[HTML]{000000} 0.5150 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4900 & \bfseries {\cellcolor[HTML]{FEF6FA}} \color[HTML]{000000} 0.5100 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3650 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3900 \\
 & paraphrased & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2600 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3600 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3600 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3100 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1600 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2400 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3150 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2450 \\
 & homoglyph & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0036 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0050 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0000 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0050 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0000 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0100 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0050 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0050 \\
\hline
\multirow[c]{3}{*}{LLM-Deviation} & original & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2071 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3550 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2850 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4400 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2650 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3700 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2250 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4050 \\
 & paraphrased & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0943 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2450 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1450 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3600 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0350 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1600 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2000 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.3050 \\
 & homoglyph & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0036 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0000 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0000 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0150 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0000 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0000 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0100 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0100 \\
\hline
\multirow[c]{3}{*}{BLOOMz-3B-mixed-detector} & original & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1657 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1850 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1600 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2250 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2200 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1300 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2150 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1250 \\
 & paraphrased & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.5036 & \bfseries {\cellcolor[HTML]{FBF4F9}} \color[HTML]{000000} 0.5250 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4250 & \bfseries {\cellcolor[HTML]{F7F0F7}} \color[HTML]{000000} 0.5550 & \bfseries {\cellcolor[HTML]{FAF3F9}} \color[HTML]{000000} 0.5350 & \bfseries {\cellcolor[HTML]{FDF5FA}} \color[HTML]{000000} 0.5150 & \bfseries {\cellcolor[HTML]{F6EFF7}} \color[HTML]{000000} 0.5600 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.4100 \\
 & homoglyph & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0379 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0500 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0200 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0500 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0650 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0500 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0600 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0050 \\
\hline
\multirow[c]{3}{*}{ChatGPT-detector-RoBERTa-Chinese} & original & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1479 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1750 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1850 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2050 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1950 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1850 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2750 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1900 \\
 & paraphrased & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1607 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1300 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1300 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2250 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2700 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2000 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2950 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1450 \\
 & homoglyph & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0986 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1200 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0300 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1600 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1550 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1250 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.2100 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1400 \\
\hline
\multirow[c]{3}{*}{Detection-Longformer} & original & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0714 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0550 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0250 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.1350 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0550 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0800 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0900 & \bfseries {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0600 \\
 & paraphrased & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0450 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0500 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0150 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0900 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0300 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0750 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0500 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0450 \\
 & homoglyph & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0179 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0350 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0000 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0650 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0000 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0350 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0150 & {\cellcolor[HTML]{FFF7FB}} \color[HTML]{000000} 0.0200 \\
\end{tabular}

In [38]:
temp = results_all[results_all['Dataset'] != "human_original"].pivot_table('TPR @ 5% FPR', 'Detector', ["Dataset", "Language"]).sort_index(axis='columns')#.sort_index(axis='index', ascending=False)
temp2 = (temp - temp['original']) / temp['original'] * 100

temp2 = temp2.drop(columns='original').stack(level=0)
temp2.rename(columns={'{all}':'All'}, inplace=True)
temp2.sort_index(axis=1, inplace=True)
temp2.index = temp2.index.set_levels(pd.CategoricalIndex(temp2.index.levels[1].values, categories=['original', 'paraphrased', 'homoglyph'], ordered=True), level=1)
temp2 = temp2.sort_index(level=1).sort_index(level=0, key=lambda x: x.map(adversarial_key))
temp2 = temp2.reset_index()
temp2['Detector'] = temp2['Detector'].map(rename_adversarial_detector)
temp2 = temp2.set_index(['Detector', 'Dataset'])
temp3 = temp2.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).apply(lambda x: np.select([temp2.eq(temp2.groupby('Detector').transform('max'))], ['font-weight: bold;'], default=''), axis=None).highlight_max(props='text-decoration: underline', axis=0).background_gradient(cmap="OrRd_r", vmin=-150, vmax=0, text_color_threshold=0, axis=None)#.background_gradient(cmap="Greens", vmin=0, vmax=150, text_color_threshold=0, axis=None)
display(temp3)
print(temp3.to_latex(convert_css=True).replace('\n\multirow','\n\hline\n\multirow'))

\begin{tabular}{llrrrrrrrr}
 & Language & All & cs & de & hr & hu & pl & sk & sl \\
Detector & Dataset &  &  &  &  &  &  &  &  \\
\hline
\multirow[c]{2}{*}{Llama-3.2-3B} & paraphrased & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 7.2874 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 5.4348 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 6.2147 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 1.5707 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 2.1053 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 2.6882 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 12.5749 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 9.5238 \\
 & homoglyph & {\cellcolor[HTML]{FEDFB4}} \color[HTML]{000000} -27.9352 & {\cellcolor[HTML]{FEEDD4}} \color[HTML]{000000} -12.5000 & {\cellcolor[HTML]{FDD19B}} \color[HTML]{000000} -39.5480 & {\cellcolor[HTML]{FFF0DC}} \color[HTML]{000000} -8.3770 & {\cellcolor[HTML]{FEE6C4}} \color[HTML]{000000} -21.0526 & {\cellcolor[HTML]{FEE4C0}} \color[HTML]{000000} -22.5806 & {\cellcolor[HTML]{FDDCAF}} \color[HTML]{000000} -29.9401 & {\cellcolor[HTML]{FDD6A2}} \color[HTML]{000000} -36.3095 \\
\hline
\multirow[c]{2}{*}{mDeBERTa-v3-base} & paraphrased & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 7.1429 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 5.4945 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 7.1429 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 14.4737 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 2.1164 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 6.6265 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 11.6959 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 11.4286 \\
 & homoglyph & {\cellcolor[HTML]{FB8957}} \color[HTML]{000000} -77.2269 & {\cellcolor[HTML]{FDB67F}} \color[HTML]{000000} -58.2418 & {\cellcolor[HTML]{F3724E}} \color[HTML]{000000} -87.5000 & {\cellcolor[HTML]{FC8F5B}} \color[HTML]{000000} -74.3421 & {\cellcolor[HTML]{FC8E5A}} \color[HTML]{000000} -74.6032 & {\cellcolor[HTML]{F67C52}} \color[HTML]{000000} -83.1325 & {\cellcolor[HTML]{FC9B66}} \color[HTML]{000000} -69.5906 & {\cellcolor[HTML]{EC5F43}} \color[HTML]{000000} -95.7143 \\
\hline
\multirow[c]{2}{*}{Gemma-2-2B} & paraphrased & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 9.5321 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 7.2626 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 7.3864 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 10.4651 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 3.7634 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 0.0000 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 10.4294 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 15.7534 \\
 & homoglyph & {\cellcolor[HTML]{FDD8A6}} \color[HTML]{000000} -34.3154 & {\cellcolor[HTML]{FEE2BB}} \color[HTML]{000000} -25.1397 & {\cellcolor[HTML]{FEE2BB}} \color[HTML]{000000} -25.0000 & {\cellcolor[HTML]{FEDFB4}} \color[HTML]{000000} -27.9070 & {\cellcolor[HTML]{FEE1B9}} \color[HTML]{000000} -25.2688 & {\cellcolor[HTML]{FDD49E}} \color[HTML]{000000} -37.9121 & {\cellcolor[HTML]{FDC690}} \color[HTML]{000000} -47.8528 & {\cellcolor[HTML]{FDBF88}} \color[HTML]{000000} -53.4247 \\
\hline
\multirow[c]{2}{*}{XLM-RoBERTa-base} & paraphrased & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 7.5901 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 3.5088 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 5.1852 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 4.7059 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 6.2500 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 3.2468 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 10.8974 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 9.0226 \\
 & homoglyph & {\cellcolor[HTML]{F26E4C}} \color[HTML]{000000} -89.0892 & {\cellcolor[HTML]{F98455}} \color[HTML]{000000} -79.5322 & {\cellcolor[HTML]{EC5D42}} \color[HTML]{000000} -96.2963 & {\cellcolor[HTML]{F4734E}} \color[HTML]{000000} -87.0588 & {\cellcolor[HTML]{F88053}} \color[HTML]{000000} -81.2500 & {\cellcolor[HTML]{F26E4C}} \color[HTML]{000000} -89.6104 & {\cellcolor[HTML]{F0694A}} \color[HTML]{000000} -91.6667 & {\cellcolor[HTML]{F0694A}} \color[HTML]{000000} -91.7293 \\
\hline
\multirow[c]{2}{*}{Fast-DetectGPT} & paraphrased & \bfseries {\cellcolor[HTML]{FDCB95}} \color[HTML]{000000} -43.9935 & \bfseries {\cellcolor[HTML]{FDD6A2}} \color[HTML]{000000} -36.2637 & \bfseries {\cellcolor[HTML]{FDD9AA}} \color[HTML]{000000} -32.7103 & \bfseries {\cellcolor[HTML]{FDD19B}} \color[HTML]{000000} -39.7959 & \bfseries {\cellcolor[HTML]{FC925E}} \color[HTML]{000000} -73.1959 & \bfseries {\cellcolor[HTML]{FDB57E}} \color[HTML]{000000} -58.6957 & \bfseries {\cellcolor[HTML]{FEE4BF}} \color[HTML]{000000} -23.1884 & \bfseries {\cellcolor[HTML]{FDD6A2}} \color[HTML]{000000} -36.2500 \\
 & homoglyph & {\cellcolor[HTML]{E7533A}} \color[HTML]{000000} -99.6753 & {\cellcolor[HTML]{E7533A}} \color[HTML]{000000} -100.0000 & {\cellcolor[HTML]{E7533A}} \color[HTML]{000000} -100.0000 & {\cellcolor[HTML]{E9573D}} \color[HTML]{000000} -98.9796 & {\cellcolor[HTML]{E7533A}} \color[HTML]{000000} -100.0000 & {\cellcolor[HTML]{E9573D}} \color[HTML]{000000} -98.9130 & {\cellcolor[HTML]{E9573D}} \color[HTML]{000000} -98.5507 & {\cellcolor[HTML]{E9573D}} \color[HTML]{000000} -98.7500 \\
\hline
\multirow[c]{2}{*}{Binoculars} & paraphrased & \bfseries {\cellcolor[HTML]{FDD19B}} \color[HTML]{000000} -39.6352 & \bfseries {\cellcolor[HTML]{FDDCAF}} \color[HTML]{000000} -30.0971 & \bfseries {\cellcolor[HTML]{FEDFB5}} \color[HTML]{000000} -27.2727 & \bfseries {\cellcolor[HTML]{FDD19B}} \color[HTML]{000000} -39.8058 & \bfseries {\cellcolor[HTML]{FCA06B}} \color[HTML]{000000} -67.3469 & \bfseries {\cellcolor[HTML]{FDBF89}} \color[HTML]{000000} -52.9412 & \bfseries {\cellcolor[HTML]{FEECD2}} \color[HTML]{000000} -13.6986 & \bfseries {\cellcolor[HTML]{FDD49F}} \color[HTML]{000000} -37.1795 \\
 & homoglyph & {\cellcolor[HTML]{E8553C}} \color[HTML]{000000} -99.1708 & {\cellcolor[HTML]{E8553C}} \color[HTML]{000000} -99.0291 & {\cellcolor[HTML]{E7533A}} \color[HTML]{000000} -100.0000 & {\cellcolor[HTML]{E8553C}} \color[HTML]{000000} -99.0291 & {\cellcolor[HTML]{E7533A}} \color[HTML]{000000} -100.0000 & {\cellcolor[HTML]{E9583E}} \color[HTML]{000000} -98.0392 & {\cellcolor[HTML]{E9573D}} \color[HTML]{000000} -98.6301 & {\cellcolor[HTML]{E9573D}} \color[HTML]{000000} -98.7179 \\
\hline
\multirow[c]{2}{*}{LLM-Deviation} & paraphrased & \bfseries {\cellcolor[HTML]{FDBE87}} \color[HTML]{000000} -54.4828 & \bfseries {\cellcolor[HTML]{FDDBAD}} \color[HTML]{000000} -30.9859 & \bfseries {\cellcolor[HTML]{FDC58E}} \color[HTML]{000000} -49.1228 & \bfseries {\cellcolor[HTML]{FEE8C9}} \color[HTML]{000000} -18.1818 & \bfseries {\cellcolor[HTML]{F4734E}} \color[HTML]{000000} -86.7925 & \bfseries {\cellcolor[HTML]{FDBA83}} \color[HTML]{000000} -56.7568 & \bfseries {\cellcolor[HTML]{FEEFD8}} \color[HTML]{000000} -11.1111 & \bfseries {\cellcolor[HTML]{FEE2BB}} \color[HTML]{000000} -24.6914 \\
 & homoglyph & {\cellcolor[HTML]{E9583E}} \color[HTML]{000000} -98.2759 & {\cellcolor[HTML]{E7533A}} \color[HTML]{000000} -100.0000 & {\cellcolor[HTML]{E7533A}} \color[HTML]{000000} -100.0000 & {\cellcolor[HTML]{EC5D42}} \color[HTML]{000000} -96.5909 & {\cellcolor[HTML]{E7533A}} \color[HTML]{000000} -100.0000 & {\cellcolor[HTML]{E7533A}} \color[HTML]{000000} -100.0000 & {\cellcolor[HTML]{EC5F43}} \color[HTML]{000000} -95.5556 & {\cellcolor[HTML]{EA5A3F}} \color[HTML]{000000} -97.5309 \\
\hline
\multirow[c]{2}{*}{BLOOMz-3B-mixed-detector} & paraphrased & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 203.8793 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 183.7838 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 165.6250 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 146.6667 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 143.1818 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 296.1538 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 160.4651 & \bfseries \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 228.0000 \\
 & homoglyph & {\cellcolor[HTML]{FB8957}} \color[HTML]{000000} -77.1552 & {\cellcolor[HTML]{FC925E}} \color[HTML]{000000} -72.9730 & {\cellcolor[HTML]{F3724E}} \color[HTML]{000000} -87.5000 & {\cellcolor[HTML]{FA8757}} \color[HTML]{000000} -77.7778 & {\cellcolor[HTML]{FC9863}} \color[HTML]{000000} -70.4545 & {\cellcolor[HTML]{FDAD77}} \color[HTML]{000000} -61.5385 & {\cellcolor[HTML]{FC935F}} \color[HTML]{000000} -72.0930 & {\cellcolor[HTML]{EC5F43}} \color[HTML]{000000} -96.0000 \\
\hline
\multirow[c]{2}{*}{ChatGPT-detector-RoBERTa-Chinese} & paraphrased & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 8.6957 & \bfseries {\cellcolor[HTML]{FEE1B9}} \color[HTML]{000000} -25.7143 & \bfseries {\cellcolor[HTML]{FDDDB0}} \color[HTML]{000000} -29.7297 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 9.7561 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 38.4615 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 8.1081 & \bfseries {\cellcolor[HTML]{FFF7EC}} \color[HTML]{000000} 7.2727 & \bfseries {\cellcolor[HTML]{FEE3BD}} \color[HTML]{000000} -23.6842 \\
 & homoglyph & {\cellcolor[HTML]{FDD9A8}} \color[HTML]{000000} -33.3333 & {\cellcolor[HTML]{FDDBAC}} \color[HTML]{000000} -31.4286 & {\cellcolor[HTML]{F67B51}} \color[HTML]{000000} -83.7838 & {\cellcolor[HTML]{FEE5C1}} \color[HTML]{000000} -21.9512 & {\cellcolor[HTML]{FEE6C4}} \color[HTML]{000000} -20.5128 & {\cellcolor[HTML]{FDD9AA}} \color[HTML]{000000} -32.4324 & {\cellcolor[HTML]{FEE3BD}} \color[HTML]{000000} -23.6364 & {\cellcolor[HTML]{FEE0B8}} \color[HTML]{000000} -26.3158 \\
\hline
\multirow[c]{2}{*}{Detection-Longformer} & paraphrased & \bfseries {\cellcolor[HTML]{FDD49F}} \color[HTML]{000000} -37.0000 & \bfseries {\cellcolor[HTML]{FFF0DB}} \color[HTML]{000000} -9.0909 & \bfseries {\cellcolor[HTML]{FDD19B}} \color[HTML]{000000} -40.0000 & \bfseries {\cellcolor[HTML]{FDD9A8}} \color[HTML]{000000} -33.3333 & \bfseries {\cellcolor[HTML]{FDCA93}} \color[HTML]{000000} -45.4545 & \bfseries {\cellcolor[HTML]{FFF2E1}} \color[HTML]{000000} -6.2500 & \bfseries {\cellcolor[HTML]{FDCB95}} \color[HTML]{000000} -44.4444 & \bfseries {\cellcolor[HTML]{FEE2BB}} \color[HTML]{000000} -25.0000 \\
 & homoglyph & {\cellcolor[HTML]{FC8E5A}} \color[HTML]{000000} -75.0000 & {\cellcolor[HTML]{FDD5A0}} \color[HTML]{000000} -36.3636 & {\cellcolor[HTML]{E7533A}} \color[HTML]{000000} -100.0000 & {\cellcolor[HTML]{FDC18A}} \color[HTML]{000000} -51.8519 & {\cellcolor[HTML]{E7533A}} \color[HTML]{000000} -100.0000 & {\cellcolor[HTML]{FDBB85}} \color[HTML]{000000} -56.2500 & {\cellcolor[HTML]{F67B51}} \color[HTML]{000000} -83.3333 & {\cellcolor[HTML]{FCA26D}} \color[HTML]{000000} -66.6667 \\
\end{tabular}

In [15]:
adversarial=['original', 'paraphrased', 'homoglyph']
adversarial_key = {v: k for k, v in dict(enumerate(adversarial)).items()}

In [110]:
temp = results_all[results_all['Dataset'] != "human_original"].pivot_table('TPR @ 5% FPR', 'Detector', ["Dataset", "Language"]).sort_index(axis='columns')#.sort_index(axis='index', ascending=False)
display(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0))
print(temp.style.format(precision=4).highlight_max(props='font-weight: bold;', axis=0).to_latex(convert_css=True))

\begin{tabular}{lrrrrrrrrrrrrrrrrrrrrrrrr}
Dataset & \multicolumn{8}{r}{homoglyph} & \multicolumn{8}{r}{original} & \multicolumn{8}{r}{paraphrased} \\
Language & cs & de & hr & hu & pl & sk & sl & {all} & cs & de & hr & hu & pl & sk & sl & {all} & cs & de & hr & hu & pl & sk & sl & {all} \\
Detector &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
Hello-SimpleAI-chatgpt-detector-roberta-chinese & 0.1200 & 0.0300 & 0.1600 & 0.1550 & 0.1250 & 0.2100 & 0.1400 & 0.0986 & 0.1750 & 0.1850 & 0.2050 & 0.1950 & 0.1850 & 0.2750 & 0.1900 & 0.1479 & 0.1300 & 0.1300 & 0.2250 & 0.2700 & 0.2000 & 0.2950 & 0.1450 & 0.1607 \\
andreas122001-bloomz-3b-mixed-detector & 0.0500 & 0.0200 & 0.0500 & 0.0650 & 0.0500 & 0.0600 & 0.0050 & 0.0379 & 0.1850 & 0.1600 & 0.2250 & 0.2200 & 0.1300 & 0.2150 & 0.1250 & 0.1657 & 0.5250 & 0.4250 & 0.5550 & 0.5350 & 0.5150 & 0.5600 & 0.4100 & 0.5036 \\
binoculars & 0.0050 & 0.0000 & 0.0050 & 0.0000 & 0.0100 & 0.0050 & 0.0050 & 0.0036 & 0.5150 & 0.4950 & 0.5150 & 0.4900 & 0.5100 & 0.3650 & 0.3900 & 0.4307 & 0.3600 & 0.3600 & 0.3100 & 0.1600 & 0.2400 & 0.3150 & 0.2450 & 0.2600 \\
fastdetectgpt & 0.0000 & 0.0000 & 0.0050 & 0.0000 & 0.0050 & 0.0050 & 0.0050 & 0.0014 & 0.4550 & 0.5350 & 0.4900 & 0.4850 & 0.4600 & 0.3450 & 0.4000 & 0.4400 & 0.2900 & 0.3600 & 0.2950 & 0.1300 & 0.1900 & 0.2650 & 0.2550 & 0.2464 \\
is_machine_prob_Llama-3.2-3B & \bfseries 0.8050 & 0.5350 & \bfseries 0.8750 & \bfseries 0.7500 & \bfseries 0.7200 & \bfseries 0.5850 & \bfseries 0.5350 & \bfseries 0.6357 & \bfseries 0.9200 & \bfseries 0.8850 & \bfseries 0.9550 & \bfseries 0.9500 & \bfseries 0.9300 & 0.8350 & \bfseries 0.8400 & \bfseries 0.8821 & \bfseries 0.9700 & 0.9400 & \bfseries 0.9700 & \bfseries 0.9700 & \bfseries 0.9550 & 0.9400 & \bfseries 0.9200 & \bfseries 0.9464 \\
is_machine_prob_gemma-2-2b & 0.6700 & \bfseries 0.6600 & 0.6200 & 0.6950 & 0.5650 & 0.4250 & 0.3400 & 0.5414 & 0.8950 & 0.8800 & 0.8600 & 0.9300 & 0.9100 & 0.8150 & 0.7300 & 0.8243 & 0.9600 & \bfseries 0.9450 & 0.9500 & 0.9650 & 0.9100 & 0.9000 & 0.8450 & 0.9029 \\
is_machine_prob_mdeberta-v3-base & 0.3800 & 0.1050 & 0.1950 & 0.2400 & 0.1400 & 0.2600 & 0.0300 & 0.1936 & 0.9100 & 0.8400 & 0.7600 & 0.9450 & 0.8300 & \bfseries 0.8550 & 0.7000 & 0.8500 & 0.9600 & 0.9000 & 0.8700 & 0.9650 & 0.8850 & \bfseries 0.9550 & 0.7800 & 0.9107 \\
is_machine_prob_xlm-roberta-base & 0.1750 & 0.0250 & 0.1100 & 0.1650 & 0.0800 & 0.0650 & 0.0550 & 0.0821 & 0.8550 & 0.6750 & 0.8500 & 0.8800 & 0.7700 & 0.7800 & 0.6650 & 0.7529 & 0.8850 & 0.7100 & 0.8900 & 0.9350 & 0.7950 & 0.8650 & 0.7250 & 0.8100 \\
llmdeviation & 0.0000 & 0.0000 & 0.0150 & 0.0000 & 0.0000 & 0.0100 & 0.0100 & 0.0036 & 0.3550 & 0.2850 & 0.4400 & 0.2650 & 0.3700 & 0.2250 & 0.4050 & 0.2071 & 0.2450 & 0.1450 & 0.3600 & 0.0350 & 0.1600 & 0.2000 & 0.3050 & 0.0943 \\
nealcly-detection-longformer & 0.0350 & 0.0000 & 0.0650 & 0.0000 & 0.0350 & 0.0150 & 0.0200 & 0.0179 & 0.0550 & 0.0250 & 0.1350 & 0.0550 & 0.0800 & 0.0900 & 0.0600 & 0.0714 & 0.0500 & 0.0150 & 0.0900 & 0.0300 & 0.0750 & 0.0500 & 0.0450 & 0.0450 \\
\end{tabular}

In [85]:
temp2 = (temp - temp['original']) / temp['original'] * 100
display(temp2.drop(columns='original').stack(level=0).style.format(precision=2).highlight_min(props='font-weight: bold;', axis=0))

In [3]:
df = pd.read_feather('multidomain_test_ce_subset_adversarial.feather')

In [4]:
df['obfuscator'] = [x.split('_')[-1] for x in df['multi_label']]

In [7]:
temp = df.groupby(['obfuscator'])[['meteor', 'bertscore', 'ngram', 'tf', 'ED-norm', 'diff_charlen', 'changed_language']].agg(['mean', 'std'])
#temp['changed_language'] = len(df[df.language != df.fasttext]) / len(df)
temp.drop(columns=('changed_language', 'std'), inplace=True)
temp.loc[['paraphrased', 'homoglyph'], :]

               meteor          bertscore               ngram            \
                 mean      std      mean       std      mean       std
obfuscator
paraphrased  0.477070  0.22984  0.823716  0.085168  0.428555  0.198052
homoglyph    0.215982  0.23831  0.872342  0.053368  0.618921  0.082184

                   tf             ED-norm            diff_charlen             \
                 mean       std      mean        std         mean        std
obfuscator
paraphrased  0.683546  0.224773  1.488706  16.150951     1.988181  16.175087
homoglyph    0.311312  0.247448  0.099092   0.029065     1.060717   0.348781

            changed_language
                        mean
obfuscator
paraphrased         0.176429
homoglyph           0.146429

In [14]:
temp = temp.loc[['paraphrased', 'homoglyph'], :].copy()
temp2 = temp.copy()
for col in temp.columns.get_level_values(0).unique()[:-1]:
  temp2[col] = [f"{str('%.3f' % x)} (±{str('%.2f' % y)})" for x,y in zip(temp[(col, 'mean')], temp[(col, 'std')])]
temp2.columns = temp2.columns.droplevel(level=1)
temp2 = temp2.T.drop_duplicates().T
#temp2.rename(index=rename_obfuscators, inplace=True)
temp2.columns = ['METEOR', 'BERTScore', 'ngram', 'TF', 'LD', 'CharLenDiff', 'LangCheck']
temp2.T.style.highlight_max(props='font-weight: bold;', axis=1).format({'LangCheck': '{:,.2%}'.format}, na_rep=0, precision=4)

In [16]:
print(temp2.T.style.highlight_max(props='font-weight: bold;', axis=1).format({'LangCheck': '{:,.2%}'.format}, na_rep=0, precision=4).applymap_index(lambda v: "font-weight: bold;", axis=0).applymap_index(lambda v: "font-weight: bold;", axis=1).to_latex(convert_css=True).replace('%', '\%'))

\begin{tabular}{lll}
obfuscator & \bfseries paraphrased & \bfseries homoglyph \\
\bfseries METEOR & \bfseries 0.477 (±0.23) & 0.216 (±0.24) \\
\bfseries BERTScore & 0.824 (±0.09) & \bfseries 0.872 (±0.05) \\
\bfseries ngram & 0.429 (±0.20) & \bfseries 0.619 (±0.08) \\
\bfseries TF & \bfseries 0.684 (±0.22) & 0.311 (±0.25) \\
\bfseries LD & \bfseries 1.489 (±16.15) & 0.099 (±0.03) \\
\bfseries CharLenDiff & \bfseries 1.988 (±16.18) & 1.061 (±0.35) \\
\bfseries LangCheck & \bfseries 0.1764 & 0.1464 \\
\end{tabular}